/* ============================================================
   STUNTS KÖLLE 4D — Data: tracks, cars, archetypes, quotes
   ============================================================ */
(function (root) {
  'use strict';

  // ---------------- CARS ----------------
  // stats 1..5 (Tempo, Beschleunigung, Handling, Nitro) drive the physics numbers below
  const CARS = [
    { id: 'gti', name: 'Taunus GT', sub: 'Ford Taunus aus Niehl, 1970. Rot, laut, Kölner Werk.', color: 0xd62828, stripe: 0xffffff, shape: 'hatch',
      accel: 16, top: 60, brake: 32, grip: 1.15, steer: 1.2, nitro: 3, stats: [3, 4, 5, 3], plate: 'K-GTI 4D' },
    { id: 'turbo', name: 'Capri 2.8i', sub: 'Der Kölner Mustang. Beige wie de Tapete im Lovers Club.', color: 0xe0b060, stripe: 0x111111, shape: 'coupe',
      accel: 15, top: 66, brake: 30, grip: 1.0, steer: 1.0, nitro: 4, stats: [4, 4, 4, 4], plate: 'K-EF 28' },
    { id: 'rocket', name: 'Rheinland Rocket', sub: 'Bayerisches Coupé, Kölner Kennzeichen, Zocker-Streifen.', color: 0xf2f2f2, stripe: 0x1c3f95, shape: 'coupe2',
      accel: 13, top: 74, brake: 28, grip: 0.95, steer: 0.9, nitro: 4, stats: [5, 3, 3, 4], plate: 'K-RR 635' },
    { id: 'special', name: 'Milieu-Benz 280 SE', sub: 'Schwarz, lang, Chrom. Dat Auto vum Ring. Fahrer: dä Lange vum Ring.', color: 0x0e0e12, stripe: 0xff2d95, shape: 'limo',
      accel: 14, top: 78, brake: 26, grip: 0.9, steer: 0.95, nitro: 5, stats: [5, 4, 3, 5], plate: 'K-LT 1' }
  ];

  // ---------------- DRIVERS / RACERS ----------------
  // The first four can be picked as your own driver (difficulty). All of them race.
  const DRIVERS = [
    { id: 'tuennes', name: 'Tünnes', diff: 'LEICHT', diffN: 0, quote: 'Et jitt nix, wat et nit jitt!', sub: 'Der jecke Herz am Rhein.',
      skill: 0.86, wobble: 0.5, color: 0x2a4a8a, car: 'gti', aiMul: 0.9,
      lines: { start: ['Et jitt nix, wat et nit jitt!', 'Loss jonn, Jung!'], overtake: ['Ha! Do bes zo langsam, Kolleg!', 'Vörbei wie de Zoch!', 'Kölle vörre, wie et sich jehört!', 'Ming Oma fährt schneller. Un die hät kein Auto.'], overtaken: ['Nä, wat is dat dann?', 'Ich hann dich jesinn!', 'Dat wor de Rhingnebel!', 'Ich hab dich vorjelosse. Aus Höflichkeit.'], crash: ['Dat wor der Schäl, nit ich!', 'Autsch. Ävver et hätt jot jejange.', 'Wer wor dat? Der Schäl! Immer der Schäl.'], win: ['Tünnes vörre! Alaaf!', 'Ne Kölsche jewinnt, wie immer.'], lose: ['Nächste Woch, Jung.', 'Dat wor ming Schonrund.'] } },
    { id: 'schael', name: 'Schäl', diff: 'MITTEL', diffN: 1, quote: 'Ich weiß eine Abkürzung!', sub: 'Et hätt noch immer jot jejange.',
      skill: 0.9, wobble: 0.35, color: 0x6a4a2a, car: 'turbo', aiMul: 0.95,
      lines: { start: ['Ich weiß eine Abkürzung!', 'Tünnes, du bes zo lang för dat Auto.'], overtake: ['Do hab ich jar nit hinjeguckt.', 'Links oder rechts, för mich is dat ejal.', 'Die Abkürzung jeht durch de Dom. Frag nit.', 'Ich seh dich doppelt, also überhol ich zweimal.'], overtaken: ['Dat wor ne optische Täuschung.', 'Ich seh zwei von dir. Un beide sin langsam.', 'Dat wor der linke Auge. Der rechte hät dich jesinn.'], crash: ['Wor dat de Wand oder de Rhing?', 'Ich hab de Kurve doppelt jesehn.', 'Die Kurve wor jestern noch woanders.'], win: ['Schäl jewinnt. Tünnes zahlt.', 'Die Abkürzung wor jot!'], lose: ['Ich hab de Ziellinie zweimal jesehn un die falsche jenomme.', 'Nächstes Mol mit Brille.'] } },
    { id: 'heinzel', name: 'Heinzel', diff: 'SCHWER', diffN: 2, quote: 'Mer stelle alles op Kopp!', sub: 'Nachts baut er, tags pennt er.',
      skill: 0.94, wobble: 0.22, color: 0xc1121f, car: 'rocket', aiMul: 1.0,
      lines: { start: ['Mer stelle alles op Kopp!', 'Ich hab de Motor heut Nacht jebaut.'], overtake: ['Schraubenschlüssel raus, vorbei!', 'Dat Heinzelmännche is schneller als du kucks.', 'Nachts jebaut, jetz jeschoben. Tschö!'], overtaken: ['Hä? Wer wor dat?', 'Da fehlt ne Schraube. Bei dir.', 'Du hast ne Schraube locker. Ich hab se heut Nacht jesucht.'], crash: ['Dat repariere ich heut Nacht.', 'Kein Problem, ich hab Ersatzteile.', 'Blech. Ich hol de Hammer.'], win: ['Heinzel vörre, un keiner hät et jesehn.', 'Nachts jebaut, tags jewonne.'], lose: ['Ich wor müd. Tagschicht.', 'Nächstes Mol schraub ich am Nitro.'] } },
    { id: 'langer', name: 'Dä Lange', diff: 'EXPERTE', diffN: 3, quote: 'Du kütts hee nit rein!', sub: 'Türsteher, Zocker, Legende. Seit 1961 op de Ringe.',
      skill: 0.985, wobble: 0.1, color: 0x111111, car: 'special', aiMul: 1.06,
      lines: { start: ['Du kütts hee nit rein! Ausnahmsweise doch. Fahr.', 'Seit 1961 stonn ich an der Tür. Heut fahr ich vorbei.', 'Chicago am Rhein, Jung. Hee jilt nur eins: schneller sin.'], overtake: ['Du fährs wie en Ratssitzung: lang un ohne Ergebnis.', 'Ich schick dir de Rechnung för de Bremsspur.', 'Du kütts hee nit vorbei. Ich schon.', 'Zwei Meter zehn Vorsprung. Jenau ming Größe.'], overtaken: ['Dat wor Klüngel, dat zählt nit!', 'Jenieß et, Jung. Dat hält nit lang.', 'Hät ich dich rinjelosse? Nä. Trotzdem bes de drin.'], crash: ['Et hätt noch immer jot jejange. Bes jetz.', 'Ich kenn ne juten Blechschmied. Ming Schwager.', 'Blechschmied. Ming Schwager. Kost extra.'], win: ['Wie immer. Der Lange T. verliert nit in singer Stadt.', 'Kumm, ich jeb dir ene us. Zum Tröste.'], lose: ['Dat wor Zufall. Ich hatt den Zylinder im Auge.', 'Jut. Du kriss en Job. Fahrer. Bei mir.'] } },
    { id: 'anna', name: 'Fräulein Anna', sub: 'Funkenmariechen mit Bleifuß.',
      skill: 0.9, wobble: 0.3, color: 0xff5fa2, car: 'gti',
      lines: { start: ['Alaaf, ihr Jecke!', 'Wer zuletzt kütt, zahlt de Kölsch.'], overtake: ['Bützje! Un tschüss!', 'Dat wor ne Tanzschritt, Jung.', 'Tanzmariechen vörre! Hebe, Jung, hebe!'], overtaken: ['Nit so frech!', 'Ich komm wieder, wie de Fastelovend.', 'Frech! Dat jibt kein Bützje.'], crash: ['Ups. Dat wor de Absatz.', 'Kamelle! Ich mein: Bremse!', 'Ming Schuh! Der Absatz hing am Gas.'], win: ['Anna vörre! Strüßjer för alle!', 'Ne Mariechen jewinnt.'], lose: ['Ming Schuh wor zo hoch.', 'Nächstes Mol im Zoch.'] } },
    { id: 'tom', name: 'Klüngel Tom', sub: 'Man kennt sich, man hilft sich.',
      skill: 0.92, wobble: 0.2, color: 0x444444, car: 'special',
      lines: { start: ['Man kennt sich, man hilft sich.', 'Die Pole Position hab ich schon vorm Rennen gewonnen.'], overtake: ['Das wurde im Ausschuss so beschlossen.', 'Nicht persönlich nehmen. Rein geschäftlich.', 'Man kennt sich. Man überholt sich.'], overtaken: ['Dazu gibt es einen Untersuchungsausschuss.', 'Das Protokoll wird angepasst.', 'Das wird noch geprüft. Vom Ausschuss.'], crash: ['Das war ein Bauprojekt. Wie die Oper.', 'Wir kannten das Ergebnis schon vorher.', 'Das ist kein Unfall. Das ist eine Baumaßnahme.'], win: ['Wie vereinbart. Danke, Tünn.', 'Ein Sieg für die Stadt. Also für mich.'], lose: ['Wir lassen das Ergebnis prüfen.', 'Die Kosten explodieren übrigens.'] } },
    { id: 'willi', name: 'Taxi Willi', sub: '30 Jahre Nachtschicht am Ring.',
      skill: 0.9, wobble: 0.3, color: 0xf2e6b1, car: 'turbo',
      lines: { start: ['Zoobrücke gesperrt, ich kenn ne Abkürzung.', 'Taxameter läuft, Kollege.'], overtake: ['Kurzstrecke. Sieben Euro.', 'Nachtzuschlag kommt noch dazu.', 'Taxi! Sie sind zu langsam für Köln.'], overtaken: ['Ich lass dich vor. Trinkgeld?', 'Fahrgast drin, ruhig fahren.', 'Fahrgast, festhalten. Der da vorne ist neu.'], crash: ['Das war der Fahrgast, nicht ich.', 'Kein Problem, Bruder, alles Blech.', 'Das zahlt die Versicherung. Also der Fahrgast.'], win: ['Ziel erreicht. Zahlen bitte.', 'Sieg. Rückfahrt kostet extra.'], lose: ['Ich hatte noch Fahrgast drin.', 'Nächstes Mal ohne Taxameter.'] } },
    { id: 'koebes', name: 'Köbes Hermann', sub: 'Grantig, schnell, bringt ungefragt Nachschub.',
      skill: 0.88, wobble: 0.4, color: 0x3a6ea5, car: 'rocket',
      lines: { start: ['Wat willste? Kölsch oder Pokal?', 'Trink doch ene met. Nach dem Rennen.'], overtake: ['Ich bring dir jleich ene Kranz Rückspiejel.', 'Dat is kein Bier, dat is Beschleunigung.', 'Ene met? Nä, ich fahr vorbei.'], overtaken: ['Do verdiens dir keine Deckel bei mir.', 'Ich hab noch drei Tische. Wart ab.', 'Kein Deckel för dich. Nie mehr.'], crash: ['Einer jeht noch. Einer jeht noch rein.', 'Dat jibt Bierdeckel-Striche för dich.', 'Dat Kölsch is heil. Dat Auto nit.'], win: ['Der Kellner jewinnt. Trinkgeld optional.', 'Dat macht 23,50. Plus Sieg.'], lose: ['Ich wor nur Deckel holen.', 'Bei mir jab et Stau am Tresen.'] } }
  ];
  const RIVALS = DRIVERS; // backwards compat

  // ---------------- TRACKS ----------------
  // All angles: + = left. Distances in metres. Each track closes on itself.
  const TRACKS = [
    {
      id: 'dom', name: 'Domblitz 4D', district: 'Dom & Rhein Stunts', tag: 'TAG', order: 2,
      waypoints: ['Dom', 'Heumarkt', 'Hohenzollernbrücke', 'Rheinsprung'],
      diff: 2, laps: 3, scale: 1.45,
      desc: 'Vom Dom zum Rhein und wieder zurück. Über die Hohenzollernbrücke nach Deutz, mit Rheinsprung und dickem Po. Tauben inklusive.',
      theme: { sky: 0x6fb2ff, fog: 0xcfe4ff, ground: 0xa99b86, sun: 0xfff2d0, road: [0x6a6a70, 0x5c5c62], night: false, water: 0x3f7fc0, street: 'altstadt',
        streets: ['HOHE STRASSE', 'AM HOF', 'TRANKGASSE', 'UNTER FETTENHENNEN', 'FRANKENWERFT', 'DEUTZER FREIHEIT', 'ALTER MARKT', 'HEUMARKT'],
        shops: ['BRAUHAUS', 'HALVE HAHN', 'RIEVKOOCHE', 'EAU DE COLOGNE', 'KÖLSCH', 'FC FANSHOP', 'DOM-SOUVENIRS'],
        far: [{ type: 'colonius', angle: 200, dist: 260 }, { type: 'triangle', angle: 20, dist: 80 }, { type: 'archbridge', angle: 300, dist: 60 }, { type: 'flatbridge', angle: 330, dist: 80 }] },
      // seg: 0 start straight, 1 L, 2 str, 3 hill, 4 str, 5 L, 6 str, 7 R, 8 str, 9 L, 10 bridge, 11 L, 12 str, 13 L, 14 str
      segments: [
        { t: 'straight', len: 140 },
        { t: 'curve', angle: 90, r: 45 },
        { t: 'straight', len: 60 },
        { t: 'loop', r: 13, shift: 14 },
        { t: 'hill', len: 70, pitch: 12 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 45, bank: 10 },
        { t: 'straight', len: 80 },
        { t: 'curve', angle: -90, r: 35 },
        { t: 'straight', len: 50 },
        { t: 'curve', angle: 90, r: 35 },
        { t: 'bridge', len: 160 },
        { t: 'curve', angle: 90, r: 50, bank: 12 },
        { t: 'straight', len: 40 },
        { t: 'jump', ramp: 30, angle: 16, gap: 34 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 50, bank: 12 },
        { t: 'straight', len: 80 }
      ],
      props: [
        { type: 'tuenn', seg: 0, u: 0.02, side: 1, dist: 9 },
        { type: 'schael', seg: 0, u: 0.02, side: -1, dist: 9 },
        { type: 'crowd', seg: 0, u: 0.06, side: 1, dist: 10 },
        { type: 'crowd', seg: 0, u: 0.06, side: -1, dist: 10 },
        { type: 'dom', seg: 0, u: 0.5, side: -1, dist: 78, keep: 120, story: 'Der Dom. 632 Johr jebaut. Länger als ming Tour. Un immer noch nit fertig, wie de Kölner Oper.' },
        { type: 'denkmal', seg: 5, u: 0.35, side: -1, dist: 14, story: 'Tünnes un Schäl. Der eine ehrlich un e bessje dumm, der andere schlau un e bessje krumm. Zesamme: Kölle.' },
        { type: 'heinzelbrunnen', seg: 2, u: 0.5, side: 1, dist: 16, keep: 22, story: 'Heinzelmännchenbrunnen. Nachts han se jeschafft, bis de Frau vum Schneider Erbse jestreut hät. Seitdem schafft in Kölle keiner mieh nachts. Außer mir.' },
        { type: 'hbf', seg: 1, u: 0.5, side: -1, dist: 95, keep: 90, story: 'Hauptbahnhof. 1975: Banküberfall met Geiseln, direkt am Dom. Chicago am Rhein, Jung. Heut nur noch Taube un Verspätung.' },
        { type: 'museum', seg: 0, u: 0.85, side: 1, dist: 42 },
        { type: 'musicaldome', seg: 2, u: 0.3, side: 1, dist: 70 },
        { type: 'stmartin', seg: 5, u: 0.5, side: -1, dist: 48, keep: 70 },
        { type: 'altstadt', seg: 4, u: 0.5, side: 1, dist: 24, seed: 3, n: 8 },
        { type: 'altstadt', seg: 7, u: 0.4, side: -1, dist: 24, seed: 8, n: 8 },
        { type: 'buedchen', seg: 7, u: 0.8, side: 1, dist: 11 },
        { type: 'bude', seg: 0, u: 0.35, side: 1, dist: 12, text: 'RIEVKOOCHE AM DOM' },
        { type: 'marktstand', seg: 5, u: 0.3, side: 1, dist: 13 }, { type: 'marktstand', seg: 5, u: 0.4, side: 1, dist: 13 }, { type: 'marktstand', seg: 5, u: 0.5, side: 1, dist: 13 },
        { type: 'blitzer', seg: 2, u: 0.9, side: -1, dist: 8 },
        { type: 'moewen', seg: 11, u: 0.5, side: 1, dist: 30, face: false },
        { type: 'zeppelin', seg: 11, u: 0.3, side: -1, dist: 80, face: false },
        { type: 'polizei', seg: 9, u: 0.2, side: -1, dist: 10 },
        { type: 'blitzer', seg: 15, u: 0.8, side: 1, dist: 8 },
        { type: 'haltestelle', seg: 9, u: 0.4, side: 1, dist: 10 },
        { type: 'tram', seg: 9, u: 0.7, side: 1, dist: 12 },
        { type: 'billboard', seg: 2, u: 0.7, side: -1, dist: 14, text: 'RING KÖLSCH – ET LÄUFT' },
        { type: 'rgm', seg: 0, u: 0.7, side: -1, dist: 40, keep: 60 },
        { type: 'eaudecologne', seg: 2, u: 0.75, side: -1, dist: 28, keep: 40 },
        { type: 'rathaus', seg: 5, u: 0.5, side: 1, dist: 42, keep: 70, story: 'Rathaus. Hee wohnt der Klüngel. Man kennt sich, man hilft sich. Un wer keinen kennt, wartet.' },
        { type: 'reiter', seg: 7, u: 0.15, side: -1, dist: 16 },
        { type: 'cafe', seg: 4, u: 0.2, side: 1, dist: 13 },
        { type: 'cafe', seg: 7, u: 0.55, side: -1, dist: 13 },
        { type: 'tramline', seg: 0, u: 0.5, side: -1, dist: 14, len: 180, face: false },
        { type: 'rhineSide', seg: 7, u: 0.5, side: 1, dist: 170, l: 700, w: 240 },
        { type: 'promenade', seg: 7, u: 0.5, side: 1, dist: 44 },
        { type: 'rhine', seg: 11, u: 0.5, side: 0, dist: 0 },
        { type: 'hbarch', seg: 11, u: 0.5, side: 0, dist: 0, story: 'Hohenzollernbrücke. 500.000 Liebesschlösser. Un e paar Schlüssel im Rhing, die han ich selbst jeworfe.' },
        { type: 'boat', seg: 11, u: 0.3, side: 1, dist: 60 },
        { type: 'barge', seg: 11, u: 0.7, side: -1, dist: 70 },
        { type: 'triangle', seg: 12, u: 0.6, side: -1, dist: 75, keep: 60 },
        { type: 'hyatt', seg: 12, u: 0.9, side: -1, dist: 60, keep: 50 },
        { type: 'messeturm', seg: 15, u: 0.5, side: 1, dist: 70 },
        { type: 'tanzbrunnen', seg: 15, u: 0.15, side: -1, dist: 45, keep: 40 },
        { type: 'rhine', seg: 14, u: 0.55, side: 0, dist: 0 },
        { type: 'boat', seg: 14, u: 0.5, side: 1, dist: 55 },
        { type: 'rheinsprung', seg: 13, u: 0.6, side: 1, dist: 10 },
        { type: 'tramline', seg: 15, u: 0.5, side: 1, dist: 14, len: 120, face: false },
        { type: 'row', seg: 15, u: 0.3, side: -1, dist: 24, style: 'concrete', seed: 4, n: 5 },
        { type: 'koelsch', seg: 15, u: 0.9, side: 1, dist: 18 },
        { type: 'billboard', seg: 17, u: 0.3, side: -1, dist: 14, text: 'CHICAGO AM RHEIN – MAN KENNT SICH' },
        { type: 'flag', seg: 17, u: 0.6, side: 1, dist: 9 }
      ]
    },
    {
      id: 'rheinauhafen', name: 'Rheinauhafen 4D', district: 'Kranhäuser to the Limit', tag: 'ABEND', order: 6,
      waypoints: ['Agrippinawerft', 'Holzmarkt', 'Kranhäuser', 'Rheinsprung'],
      diff: 3, laps: 3, scale: 1.45,
      desc: 'Volle Pulle die Rheinuferstraße runter, Sprung über das Hafenbecken zwischen den Kranhäusern, Schokoladenmuseum, Severinsbrücke. Wer zu kurz springt, badet im Rhing.',
      theme: { sky: 0x6a2a8a, fog: 0xff8a9a, ground: 0x8a8890, sun: 0xffb0c0, road: [0x5a5560, 0x4c4852], night: false, sunset: true, miami: true, water: 0x2f6fa8, street: 'modern',
        posters: ['RHEINSTRAND', 'VICE KÖLLE', 'KRANHAUS-PARTY', 'SCHOKOLADE', 'LAMBOGINA'],
        streets: ['RHEINUFERSTR.', 'IM ZOLLHAFEN', 'AGRIPPINAWERFT', 'BAYENSTRASSE', 'HOLZMARKT', 'SEVERINSTRASSE', 'CHLODWIGPLATZ'],
        shops: ['HAFENBAR', 'SCHOKOLADE', 'CAFÉ AM HAFEN', 'KÖLSCH', 'SUSHI', 'GALERIE', 'YACHTSERVICE'],
        far: [{ type: 'dom', angle: 100, dist: 160 }, { type: 'colonius', angle: 140, dist: 200 }, { type: 'archbridge', angle: 60, dist: 40 }, { type: 'stmartin', angle: 90, dist: 120 }] },
      // 0 str,1 R,2 str,3 jump,4 str,5 R,6 str,7 L,8 str,9 R,10 hill,11 str,12 R,13 str,14 jump,15 str,16 R,17 str
      segments: [
        { t: 'straight', len: 120 },
        { t: 'curve', angle: -90, r: 40 },
        { t: 'straight', len: 40 },
        { t: 'jump', ramp: 30, angle: 16, gap: 32 },
        { t: 'straight', len: 60 },
        { t: 'loop', r: 13, shift: 14 },
        { t: 'curve', angle: -90, r: 40, bank: 10 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: 90, r: 30 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: -90, r: 30 },
        { t: 'hill', len: 60, pitch: 14 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: -90, r: 40, bank: 12 },
        { t: 'straight', len: 45 },
        { t: 'jump', ramp: 24, angle: 14, gap: 24 },
        { t: 'straight', len: 60 },
        { t: 'curve', angle: -90, r: 40 },
        { t: 'straight', len: 12 }
      ],
      props: [
        { type: 'tuenn', seg: 0, u: 0.02, side: 1, dist: 9 },
        { type: 'crowd', seg: 0, u: 0.06, side: -1, dist: 10 },
        { type: 'kranhaus', seg: 0, u: 0.3, side: 1, dist: 42, keep: 40, story: 'Kranhäuser. Früher Hafen, Schmuggel un Zoll. Heut Penthouse, Latte un Zoll. Hät sich nix jeändert, nur de Preise.' },
        { type: 'kranhaus', seg: 0, u: 0.55, side: 1, dist: 42, keep: 40 },
        { type: 'kranhaus', seg: 0, u: 0.8, side: 1, dist: 42, keep: 40 },
        { type: 'palm', seg: 0, u: 0.2, side: 1, dist: 12, h: 8 }, { type: 'palm', seg: 0, u: 0.35, side: 1, dist: 12, h: 7, seed: 2 }, { type: 'palm', seg: 0, u: 0.5, side: 1, dist: 12, h: 9, seed: 3 }, { type: 'palm', seg: 0, u: 0.65, side: 1, dist: 12, h: 7, seed: 4 }, { type: 'palm', seg: 0, u: 0.8, side: 1, dist: 12, h: 8, seed: 5 },
        { type: 'palm', seg: 0, u: 0.25, side: -1, dist: 11, h: 6, seed: 6 }, { type: 'palm', seg: 0, u: 0.55, side: -1, dist: 11, h: 7, seed: 7 },
        { type: 'speedboat', seg: 0, u: 0.5, side: 1, dist: 110, face: false },
        { type: 'moewen', seg: 0, u: 0.6, side: 1, dist: 70, face: false },
        { type: 'blitzer', seg: 0, u: 0.92, side: -1, dist: 8 },
        { type: 'riesenrad', seg: 6, u: 0.5, side: -1, dist: 60, keep: 50 },
        { type: 'beach', seg: 7, u: 0.5, side: 1, dist: 62, keep: 60 },
        { type: 'palm', seg: 7, u: 0.3, side: 1, dist: 12, h: 8, seed: 11 }, { type: 'palm', seg: 7, u: 0.7, side: 1, dist: 12, h: 7, seed: 12 },
        { type: 'neon', seg: 7, u: 0.2, side: -1, dist: 13, text: 'FLAMINGO BAR', color: '#ff2d95', small: true, light: false },
        { type: 'bude', seg: 9, u: 0.5, side: -1, dist: 11, text: 'FISCHBRÖTCHEN · KÖLSCH' },
        { type: 'palm', seg: 16, u: 0.3, side: -1, dist: 11, h: 8, seed: 8 }, { type: 'palm', seg: 16, u: 0.6, side: -1, dist: 11, h: 7, seed: 9 },
        { type: 'polizei', seg: 16, u: 0.8, side: 1, dist: 10 },
        { type: 'rhineSide', seg: 0, u: 0.25, side: 1, dist: 140, l: 300, w: 160 },
        { type: 'promenade', seg: 0, u: 0.4, side: 1, dist: 62 },
        { type: 'barge', seg: 0, u: 0.4, side: 1, dist: 120 },
        { type: 'boat', seg: 0, u: 0.9, side: 1, dist: 100 },
        { type: 'rhine', seg: 3, u: 0.55, side: 0, dist: 0 },
        { type: 'boat', seg: 3, u: 0.5, side: 1, dist: 45 },
        { type: 'schoko', seg: 4, u: 0.5, side: 1, dist: 40, keep: 50 },
        { type: 'severinsbruecke', seg: 4, u: 0.9, side: 1, dist: 150, face: false },
        { type: 'billboard', seg: 7, u: 0.5, side: 1, dist: 14, text: 'HALVE HAHN GRILL – SEIT 1928' },
        { type: 'severinstor', seg: 9, u: 0.5, side: 1, dist: 30 },
        { type: 'kirche', seg: 10, u: 0.5, side: -1, dist: 40, h: 45, color: 0xb9a184 },
        { type: 'row', seg: 12, u: 0.5, side: -1, dist: 24, style: 'gruenderzeit', seed: 12, n: 5 },
        { type: 'tramline', seg: 12, u: 0.5, side: 1, dist: 14, len: 90, face: false },
        { type: 'cafe', seg: 11, u: 0.8, side: 1, dist: 13 },
        { type: 'buedchen', seg: 12, u: 0.2, side: 1, dist: 11 },
        { type: 'koelsch', seg: 14, u: 0.5, side: -1, dist: 18 },
        { type: 'rhine', seg: 15, u: 0.55, side: 0, dist: 0 },
        { type: 'barge', seg: 15, u: 0.5, side: -1, dist: 60 },
        { type: 'row', seg: 16, u: 0.5, side: -1, dist: 24, style: 'modern', seed: 2, n: 4 },
        { type: 'billboard', seg: 16, u: 0.8, side: 1, dist: 14, text: 'DÄ LANGE – KÖLSCH & KREDIT' },
        { type: 'haltestelle', seg: 18, u: 0.4, side: -1, dist: 10 }
      ]
    },
    {
      id: 'zoo', name: 'Schäl Sick Schraube', district: 'Deutz & Mülheim', tag: 'TAG', order: 3,
      waypoints: ['Deutzer Freiheit', 'Messe', 'Rheinpark', 'Mülheimer Hafen'],
      diff: 4, laps: 3, scale: 1.45,
      desc: 'Deutz, Messe, Rheinpark, Mülheimer Hafen. Die Schraube an der Flora, unter der Seilbahn durch, Kräne im Hafen. Wer hier nicht schaltet, verliert alles.',
      theme: { sky: 0x5fa8ff, fog: 0xcfe6ff, ground: 0x5e9a4a, sun: 0xffffff, road: [0x585858, 0x4a4a4a], night: false, water: 0x3f7fc0, street: 'park',
        streets: ['RIEHLER STRASSE', 'ZOOBRÜCKE', 'AUENWEG', 'MÜLHEIMER FREIHEIT', 'AM BOTANISCHEN GARTEN'],
        far: [{ type: 'dom', angle: 230, dist: 140 }, { type: 'colonius', angle: 260, dist: 220 }, { type: 'triangle', angle: 210, dist: 80 }, { type: 'flatbridge', angle: 180, dist: 60 }] },
      // 0 str,1 L,2 str,3 loop,4 str,5 L,6 bridge,7 R,8 str,9 L,10 hill,11 L,12 str,13 R,14 str,15 L,16 str,17 L,18 str
      segments: [
        { t: 'straight', len: 150 },
        { t: 'curve', angle: 90, r: 50, bank: 15 },
        { t: 'straight', len: 50 },
        { t: 'loop', r: 14, shift: 14 },
        { t: 'straight', len: 60 },
        { t: 'curve', angle: 90, r: 40 },
        { t: 'bridge', len: 130 },
        { t: 'curve', angle: -90, r: 35 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: 90, r: 35 },
        { t: 'hill', len: 60, pitch: 16 },
        { t: 'curve', angle: 90, r: 45, bank: 15 },
        { t: 'straight', len: 100 },
        { t: 'jump', ramp: 26, angle: 15, gap: 26 },
        { t: 'curve', angle: -90, r: 30 },
        { t: 'straight', len: 20 },
        { t: 'curve', angle: 90, r: 30 },
        { t: 'straight', len: 20 },
        { t: 'curve', angle: 90, r: 30 },
        { t: 'straight', len: 30 }
      ],
      props: [
        { type: 'tuenn', seg: 0, u: 0.02, side: -1, dist: 9 },
        { type: 'zootor', seg: 0, u: 0.22, side: 1, dist: 18, keep: 40 },
        { type: 'giraffe', seg: 0, u: 0.32, side: 1, dist: 30 },
        { type: 'elephant', seg: 0, u: 0.4, side: 1, dist: 26 },
        { type: 'elephant', seg: 0, u: 0.5, side: 1, dist: 34 },
        { type: 'elephant', seg: 0, u: 0.6, side: 1, dist: 24 },
        { type: 'row', seg: 0, u: 0.7, side: -1, dist: 26, style: 'gruenderzeit', seed: 5, n: 4 },
        { type: 'flora', seg: 2, u: 0.5, side: -1, dist: 40, keep: 50, story: 'Schäl Sick. De falsche Rheinseite, sagen de Kölner. Ich sag: hee kennt mich keiner. Dat is och wat wert.' },
        { type: 'crowd', seg: 4, u: 0.3, side: 1, dist: 12 },
        { type: 'rhine', seg: 6, u: 0.5, side: 0, dist: 0 },
        { type: 'seilbahn', seg: 6, u: 0.15, side: 0, dist: 0 },
        { type: 'suspension', seg: 6, u: 0.5, side: 1, dist: 170, face: false },
        { type: 'boat', seg: 6, u: 0.35, side: -1, dist: 50 },
        { type: 'barge', seg: 6, u: 0.7, side: 1, dist: 70 },
        { type: 'messeturm', seg: 8, u: 0.5, side: -1, dist: 60 },
        { type: 'hafenkran', seg: 12, u: 0.85, side: 1, dist: 40 },
        { type: 'speedboat', seg: 14, u: 0.5, side: 1, dist: 80, face: false },
        { type: 'moewen', seg: 6, u: 0.6, side: -1, dist: 40, face: false },
        { type: 'blitzer', seg: 0, u: 0.85, side: -1, dist: 8 },
        { type: 'bude', seg: 12, u: 0.2, side: -1, dist: 11, text: 'HAFEN-IMBISS · FLÖNZ' },
        { type: 'blitzer', seg: 12, u: 0.7, side: 1, dist: 8 },
        { type: 'hafenkran', seg: 14, u: 0.5, side: 1, dist: 48 },
        { type: 'barge', seg: 14, u: 0.5, side: 1, dist: 80 },
        { type: 'rhineSide', seg: 14, u: 0.5, side: 1, dist: 170, l: 300, w: 200 },
        { type: 'tanzbrunnen', seg: 7, u: 0.5, side: 1, dist: 50, keep: 40 },
        { type: 'kirche', seg: 12, u: 0.2, side: -1, dist: 50, h: 32 },
        { type: 'koelsch', seg: 12, u: 0.3, side: 1, dist: 20 },
        { type: 'billboard', seg: 12, u: 0.7, side: -1, dist: 14, text: 'MÜLHEIM – HEE FÄNGT DER OSTEN AN' },
        { type: 'row', seg: 12, u: 0.6, side: 1, dist: 26, style: 'concrete', seed: 7, n: 5 },
        { type: 'buedchen', seg: 17, u: 0.5, side: -1, dist: 11 },
        { type: 'crowd', seg: 19, u: 0.5, side: 1, dist: 10 }
      ]
    },
    {
      id: 'ehrenfeld', name: 'Ehrenfeld Tape Run', district: 'Venloer Straße', tag: 'ABEND', order: 4,
      waypoints: ['Venloer', 'Odonien', 'Bahnbögen', 'Subbelrath', 'Köln West'],
      diff: 2, laps: 3, scale: 1.45,
      desc: 'Zwischen Bahnbögen, Kiosk und Kassettenladen. Enge Haken durch die Venloer Straße, Odonien, Colonius. Rau, schnell, ehrlich.',
      theme: { sky: 0x9fbfe0, fog: 0xd8e2ea, ground: 0x8a8a84, sun: 0xfff6e0, road: [0x4e4e4e, 0x424242], night: false, water: 0x3f7fc0, street: 'gruenderzeit', catenary: true,
        streets: ['VENLOER STRASSE', 'KÖRNERSTRASSE', 'SUBBELRATHER STR.', 'VOGELSANGER STR.', 'EHRENFELDGÜRTEL', 'HELIOSSTRASSE', 'LEYENDECKERSTR.'],
        shops: ['DÖNER', 'CAFÉ HAFERMILCH', 'PLATTENLADEN', 'BARBIER', 'LASTENRAD-VERLEIH', 'KIOSK', 'FALAFEL', 'TATTOO', 'BÜDCHE'],
        far: [{ type: 'dom', angle: 30, dist: 200 }, { type: 'triangle', angle: 15, dist: 300 }] },
      // 0 str,1 R,2 str,3 L,4 str,5 L,6 str,7 R,8 hill,9 R,10 str,11 R,12 str,13 L,14 str,15 R,16 tunnel,17 R,18 str,19 R,20 str
      segments: [
        { t: 'straight', len: 90 },
        { t: 'curve', angle: -90, r: 28, bank: 8 },
        { t: 'straight', len: 16 },
        { t: 'curve', angle: 90, r: 28, bank: 8 },
        { t: 'straight', len: 16 },
        { t: 'curve', angle: 90, r: 28, bank: 8 },
        { t: 'straight', len: 16 },
        { t: 'curve', angle: -90, r: 28, bank: 8 },
        { t: 'hill', len: 50, pitch: 12 },
        { t: 'curve', angle: -90, r: 30, bank: 8 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: -90, r: 30, bank: 8 },
        { t: 'straight', len: 60 },
        { t: 'loop', r: 13, shift: 14 },
        { t: 'curve', angle: 90, r: 28, bank: 6 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: -90, r: 28, bank: 6 },
        { t: 'tunnel', len: 60 },
        { t: 'curve', angle: -90, r: 35, bank: 10 },
        { t: 'jump', ramp: 26, angle: 15, gap: 26 },
        { t: 'straight', len: 90 },
        { t: 'curve', angle: -90, r: 35, bank: 10 },
        { t: 'straight', len: 14 }
      ],
      props: [
        { type: 'tuenn', seg: 0, u: 0.02, side: 1, dist: 9 },
        { type: 'colonius', seg: 0, u: 0.5, side: -1, dist: 90, keep: 40 },
        { type: 'billboard', seg: 0, u: 0.25, side: 1, dist: 14, text: 'VENLOER STR. – HAFERMILCH TO GO' },
        { type: 'haltestelle', seg: 0, u: 0.6, side: 1, dist: 10 },
        { type: 'tram', seg: 0, u: 0.8, side: 1, dist: 12 },
        { type: 'graffiti', seg: 2, u: 0.5, side: 1, dist: 12, text: 'EHRENFELD' },
        { type: 'lastenrad', seg: 4, u: 0.5, side: 1, dist: 10 },
        { type: 'buedchen', seg: 6, u: 0.5, side: -1, dist: 11 },
        { type: 'viaduct', seg: 12, u: 0.5, side: 1, dist: 26, keep: 90 },
        { type: 'moschee', seg: 8, u: 0.5, side: 1, dist: 60, keep: 60, story: 'Ehrenfeld. Hee hät jeder Straße ihre eijene Sprache un jeder Kiosk sing eijene Reejele. Ming Reejel: Kölsch jeht immer.' },
        { type: 'odonien', seg: 10, u: 0.5, side: 1, dist: 30, keep: 40 },
        { type: 'bude', seg: 0, u: 0.4, side: -1, dist: 11, text: 'DÖNER · HAFERMILCH' },
        { type: 'blitzer', seg: 0, u: 0.7, side: 1, dist: 8 },
        { type: 'blitzer', seg: 20, u: 0.5, side: -1, dist: 8 },
        { type: 'polizei', seg: 12, u: 0.2, side: 1, dist: 10 },
        { type: 'neon', seg: 4, u: 0.5, side: -1, dist: 13, text: 'KASSETTENLADEN', color: '#ff2d95', light: false },
        { type: 'vulkanhalle', seg: 17, u: 0.5, side: -1, dist: 45, keep: 60 },
        { type: 'tramline', seg: 0, u: 0.5, side: -1, dist: 14, len: 120, face: false },
        { type: 'cafe', seg: 2, u: 0.5, side: -1, dist: 13 },
        { type: 'graffiti', seg: 10, u: 0.5, side: -1, dist: 12, text: 'CHICAGO AM RHEIN', color: '#00e5ff' },
        { type: 'row', seg: 12, u: 0.5, side: -1, dist: 24, style: 'industrial', seed: 21, n: 5 },
        { type: 'koelsch', seg: 15, u: 0.5, side: 1, dist: 18 },
        { type: 'lastenrad', seg: 15, u: 0.2, side: -1, dist: 10 },
        { type: 'helios', seg: 18, u: 0.5, side: 1, dist: 34 },
        { type: 'billboard', seg: 20, u: 0.3, side: 1, dist: 14, text: 'HELIOS-TURM – NUR ECHT MIT LEUCHTTURM' },
        { type: 'graffiti', seg: 20, u: 0.7, side: -1, dist: 12, text: 'DÄ LANGE WOR HEE', color: '#7fff00' },
        { type: 'buedchen', seg: 20, u: 0.9, side: 1, dist: 11 },
        { type: 'crowd', seg: 22, u: 0.5, side: 1, dist: 10 }
      ]
    },
    {
      id: 'kalk', name: 'Chicago am Rhein', district: 'Ringe Nachtfahrt', tag: 'NACHT', order: 1,
      waypoints: ['Residenz-Kino', 'Friesenstraße', 'Klein Köln', 'Sartory', 'Lovers Club', 'Hansaring'],
      diff: 5, laps: 3, scale: 1.45,
      desc: 'Die Nachttour vum Lange vum Ring als Rennen: vom Residenz-Kino über die Friesenstraße am Klein Köln vorbei, Sartory, Lovers Club, Hansaring. Nacht, Neon, nasse Straßen, Zocker, Türsteher, Kripo. 1968. Nix für Sonntagsfahrer.',
      theme: { sky: 0x070a24, fog: 0x2a1a4a, ground: 0x23232e, sun: 0x9fb4ff, road: [0x2c2e3a, 0x25272f], night: true, wet: true, water: 0x102040, street: 'gruenderzeit', catenary: true,
        streets: ['HOHENZOLLERNRING', 'FRIESENSTRASSE', 'CHRISTOPHSTRASSE', 'FRIESENPLATZ', 'HANSARING', 'KAISER-WILHELM-RING', 'EBERTPLATZ', 'RUDOLFPLATZ'],
        shops: ['BOXKELLER', 'TANZ LOKAL', 'KIOSK', 'BRAUHAUS', 'NACHTCAFÉ', 'CASINO', 'IMBISS', 'BAR ZUM LANGEN', 'BILLARD', 'SPÄTI', 'DISCO', 'KÖLSCH', 'FLAMINGO BAR', 'VICE LOUNGE', 'KLÜNGEL & CO'],
        posters: ['BOXKELLER', 'DÄ LANGE LIVE', 'KÖLSCH-NACHT', 'VICE KÖLLE', 'FC HEIMSPIEL'],
        far: [{ type: 'dom', angle: 20, dist: 160 }, { type: 'colonius', angle: 200, dist: 120 }, { type: 'triangle', angle: 40, dist: 200 }] },
      // 0 str,1 L,2 str,3 loop,4 str,5 L,6 str,7 jump,8 str,9 R,10 str,11 L,12 loop,13 str,14 L,15 tunnel,16 L,17 str,18 R,19 str,20 L,21 str
      segments: [
        { t: 'straight', len: 130 },
        { t: 'curve', angle: 90, r: 40, bank: 12 },
        { t: 'straight', len: 30 },
        { t: 'loop', r: 13, shift: 14 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 40, bank: 12 },
        { t: 'straight', len: 30 },
        { t: 'jump', ramp: 28, angle: 15, gap: 28 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: -90, r: 30 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: 90, r: 30 },
        { t: 'loop', r: 13, shift: 14 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: 90, r: 45, bank: 15 },
        { t: 'tunnel', len: 80 },
        { t: 'curve', angle: 90, r: 45, bank: 15 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: -90, r: 30 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: 90, r: 30 },
        { t: 'straight', len: 35 }
      ],
      props: [
        { type: 'tuenn', seg: 0, u: 0.02, side: 1, dist: 9 },
        { type: 'residenz', seg: 0, u: 0.12, side: -1, dist: 24, keep: 40, story: 'Hee fängt ming Tour an: Residenz-Kino, Christophstraße. 1961 stond ich zum erste Mol an ner Tür. Un ich stonn immer noch.' },
        { type: 'neon', seg: 0, u: 0.1, side: 1, dist: 14, text: 'CHICAGO AM RHEIN', color: '#ff2d95' },
        { type: 'expresskiosk', seg: 0, u: 0.22, side: 1, dist: 11, text: 'EXPRESS: KÖLN – CHICAGO AM RHEIN!' },
        { type: 'kleinkoeln', seg: 0, u: 0.35, side: -1, dist: 24, keep: 40, story: 'Links: Klein Köln, Friesenstraße. Seit 1926 Nachtlizenz. Hee han sich de Boxer jewoge. Un ich mich och, nach dem dritten Kölsch.' },
        { type: 'boxring', seg: 0, u: 0.5, side: -1, dist: 16, keep: 20 },
        { type: 'hansahochhaus', seg: 0, u: 0.7, side: 1, dist: 50, keep: 60, story: 'Dat Hansahochhaus. 1925 dat höchste Haus in Europa. Heut nur noch dat höchste am Ring. Wie ich.' },
        { type: 'spielclub', seg: 0, u: 0.62, side: -1, dist: 24, keep: 40, story: 'Spiel-Club. Hee hab ich ming Vermögen jemaat. Un hee hab ich et och wieder verzockt. Alles op Rot. Wie de Ampel.' },
        { type: 'neon', seg: 0, u: 0.8, side: -1, dist: 14, text: 'ZUM LANGEN – KÖLSCH & KREDIT', color: '#ffd400' },
        { type: 'gangster', seg: 0, u: 0.85, side: -1, dist: 9 },
        { type: 'gangster', seg: 0, u: 0.87, side: -1, dist: 11 },
        { type: 'kripo', seg: 0, u: 0.6, side: 1, dist: 10, story: 'Kripo Köln. 50.000 Straftaten im Johr, e Drittel jeklärt. Der Rest fährt heut met dir im Rennen.' },
        { type: 'blitzer', seg: 0, u: 0.9, side: 1, dist: 8 },
        { type: 'bude', seg: 0, u: 0.5, side: 1, dist: 11, text: 'NACHTIMBISS · HALVE HAHN' },
        { type: 'zeppelin', seg: 0, u: 0.5, side: 1, dist: 60, face: false },
        { type: 'rain', seg: 0, u: 0.5, side: 0, dist: 0, face: false },
        { type: 'fireworks', seg: 5, u: 0.5, side: 1, dist: 100, face: false },
        { type: 'palm', seg: 0, u: 0.3, side: -1, dist: 9, h: 8 },
        { type: 'palm', seg: 0, u: 0.36, side: -1, dist: 9, h: 7 },
        { type: 'hahnentor', seg: 2, u: 0.5, side: 1, dist: 26, keep: 40, story: 'Hahnentor, Rudolfplatz. Da kome früher de Könige durch. Heut de Jecke. Un du, wenn de nit bremst.' },
        { type: 'sartory', seg: 4, u: 0.5, side: 1, dist: 30, keep: 50, story: 'Sartory-Säle. Boxnächte, Prunksitzunge, Schlägereien. Manchmal alles an einem Abend.' },
        { type: 'neon', seg: 4, u: 0.5, side: -1, dist: 13, text: 'KIOSK', color: '#00e5ff', light: false },
        { type: 'koelnturm', seg: 5, u: 0.5, side: -1, dist: 90, keep: 60 },
        { type: 'rails', seg: 7, u: 0.55, side: 0, dist: 0 },
        { type: 'loversclub', seg: 8, u: 0.5, side: 1, dist: 24, keep: 40, story: 'Lovers Club. Ming erste Tür, 1961. Reejel Nummer eins: Wer hee nit reinkütt, kütt nirjendwo rein. Du kütts rein. Ausnahmsweise.' },
        { type: 'tram', seg: 8, u: 0.5, side: -1, dist: 14 },
        { type: 'neon', seg: 8, u: 0.8, side: -1, dist: 14, text: 'KLÜNGEL & SÖHNE – BAU · RAT · ZOCH', color: '#00e5ff' },
        { type: 'neon', seg: 10, u: 0.5, side: 1, dist: 13, text: 'CASINO', color: '#ffd400' },
        { type: 'blitzer', seg: 10, u: 0.8, side: -1, dist: 8 },
        { type: 'kripo', seg: 11, u: 0.5, side: 1, dist: 10 },
        { type: 'neon', seg: 13, u: 0.3, side: -1, dist: 13, text: 'VICE · KÖLLE', color: '#00e5ff', small: true },
        { type: 'neon', seg: 13, u: 0.7, side: 1, dist: 13, text: 'FLAMINGO BAR', color: '#ff2d95', small: true },
        { type: 'koelsch', seg: 13, u: 0.5, side: 1, dist: 20 },
        { type: 'eigelsteintor', seg: 14, u: 0.5, side: -1, dist: 28, keep: 40, story: 'Eigelsteintor. Hee hört de Ring op un de Eigelstein fängt an. Da wor et noch e bessje ehrlicher. Also weniger.' },
        { type: 'expresskiosk', seg: 17, u: 0.2, side: -1, dist: 11, text: 'EXPRESS: DOMSCHATZ JEKLAUT – WER WOR ET?' },
        { type: 'neon', seg: 17, u: 0.3, side: 1, dist: 14, text: 'MAN KENNT SICH · MAN HILFT SICH', color: '#ff2d95' },
        { type: 'neon', seg: 17, u: 0.7, side: -1, dist: 13, text: 'DISCO', color: '#c04dff', light: false },
        { type: 'buedchen', seg: 17, u: 0.85, side: 1, dist: 11 },
        { type: 'tramline', seg: 17, u: 0.5, side: 1, dist: 14, len: 100, face: false },
        { type: 'gangster', seg: 19, u: 0.5, side: 1, dist: 9 },
        { type: 'blitzer', seg: 19, u: 0.8, side: 1, dist: 8 },
        { type: 'bude', seg: 21, u: 0.2, side: 1, dist: 11, text: 'CURRYWURST BEI JUPP' },
        { type: 'neon', seg: 21, u: 0.4, side: -1, dist: 14, text: 'ET HÄTT NOCH IMMER JOT JEJANGE', color: '#7fff00', light: false },
        { type: 'crowd', seg: 21, u: 0.8, side: -1, dist: 10 }
      ]
    },
    {
      id: 'zoch', name: 'Karneval Krawall', district: 'Altstadt Rallye', tag: 'TAG', order: 5,
      waypoints: ['Heumarkt', 'Alter Markt', 'Rathaus', 'Schmitzengasse'],
      diff: 3, laps: 3, scale: 1.45,
      desc: 'Der Zochweg als Rennstrecke: Heumarkt, Alter Markt, Rathaus, durchs Severinstor. Hügel, Sprung, Konfetti, Kamelle. Alaaf! Die Bahn ist gesperrt, die Jecken nicht.',
      theme: { sky: 0x8fc0ff, fog: 0xffe6f5, ground: 0xb5ada0, sun: 0xfff0ff, road: [0x5a5a5a, 0x4c4c4c], night: false, water: 0x3f7fc0, confetti: true, street: 'gruenderzeit', catenary: true,
        streets: ['SEVERINSTRASSE', 'CHLODWIGPLATZ', 'NEUMARKT', 'SCHILDERGASSE', 'HOHE STRASSE', 'RUDOLFPLATZ', 'ZOCHWEG'],
        shops: ['KAMELLE', 'KOSTÜME', 'STRÜSSJER', 'KÖLSCH', 'BÜTZJE-BAR', 'FUNKENMARIECHEN', 'ALAAF-SHOP', 'BRAUHAUS'],
        far: [{ type: 'dom', angle: 80, dist: 160 }, { type: 'colonius', angle: 150, dist: 260 }] },
      // 0 str,1 hill,2 L,3 str,4 jump,5 str,6 L,7 hill,8 R,9 str,10 L,11 hill,12 L,13 str,14 R,15 dip,16 L,17 str,18 L,19 str
      segments: [
        { t: 'straight', len: 100 },
        { t: 'hill', len: 50, pitch: 14 },
        { t: 'curve', angle: 90, r: 40, bank: 10 },
        { t: 'straight', len: 30 },
        { t: 'jump', ramp: 26, angle: 15, gap: 26 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 40, bank: 10 },
        { t: 'hill', len: 50, pitch: 14 },
        { t: 'curve', angle: -90, r: 30 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 30 },
        { t: 'hill', len: 40, pitch: 12 },
        { t: 'curve', angle: 90, r: 30 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: -90, r: 30 },
        { t: 'dip', len: 40, pitch: 12 },
        { t: 'curve', angle: 90, r: 40, bank: 10 },
        { t: 'straight', len: 80 },
        { t: 'loop', r: 13, shift: 14 },
        { t: 'curve', angle: 90, r: 40, bank: 10 },
        { t: 'straight', len: 40 }
      ],
      props: [
        { type: 'tuenn', seg: 0, u: 0.02, side: 1, dist: 9 },
        { type: 'crowd', seg: 0, u: 0.15, side: -1, dist: 10 },
        { type: 'tribuene', seg: 0, u: 0.3, side: 1, dist: 12, keep: 30 },
        { type: 'zochwagen', seg: 0, u: 0.5, side: -1, dist: 13 },
        { type: 'tribuene', seg: 9, u: 0.3, side: -1, dist: 12, keep: 30 },
        { type: 'zochwagen', seg: 13, u: 0.6, side: 1, dist: 13 },
        { type: 'tribuene', seg: 17, u: 0.5, side: -1, dist: 12, keep: 30 },
        { type: 'kirche', seg: 8, u: 0.5, side: 1, dist: 45, h: 40 },
        { type: 'bunting', seg: 0, u: 0.4, side: 0, dist: 0 },
        { type: 'billboard', seg: 0, u: 0.6, side: -1, dist: 14, text: 'KÖLLE ALAAF – KAMELLE!' },
        { type: 'haltestelle', seg: 0, u: 0.8, side: 1, dist: 10 },
        { type: 'severinstor', seg: 3, u: 0.5, side: 0, dist: 0, face: false, story: 'Severinstor. Hee kütt der Zoch durch. Un an Rosenmontag bin ich ausnahmsweise nüchtern. Nä, Spaß.' },
        { type: 'bude', seg: 0, u: 0.7, side: 1, dist: 11, text: 'KAMELLE & KÖLSCH' },
        { type: 'blitzer', seg: 0, u: 0.9, side: -1, dist: 8 },
        { type: 'zeppelin', seg: 5, u: 0.5, side: 1, dist: 60, face: false },
        { type: 'polizei', seg: 9, u: 0.2, side: -1, dist: 10 },
        { type: 'blitzer', seg: 17, u: 0.5, side: 1, dist: 8 },
        { type: 'crowd', seg: 5, u: 0.4, side: 1, dist: 10 },
        { type: 'crowd', seg: 5, u: 0.7, side: -1, dist: 10 },
        { type: 'bunting', seg: 5, u: 0.55, side: 0, dist: 0 },
        { type: 'altstadt', seg: 9, u: 0.5, side: 1, dist: 24, seed: 11, n: 6 },
        { type: 'koelsch', seg: 9, u: 0.5, side: -1, dist: 18 },
        { type: 'bunting', seg: 9, u: 0.5, side: 0, dist: 0 },
        { type: 'billboard', seg: 13, u: 0.5, side: 1, dist: 14, text: 'D’R ZOCH KÜTT!' },
        { type: 'crowd', seg: 13, u: 0.3, side: -1, dist: 10 },
        { type: 'crowd', seg: 13, u: 0.7, side: 1, dist: 10 },
        { type: 'bunting', seg: 13, u: 0.5, side: 0, dist: 0 },
        { type: 'hahnentor', seg: 17, u: 0.5, side: 1, dist: 30 },
        { type: 'billboard', seg: 17, u: 0.3, side: -1, dist: 14, text: 'RING KÖLSCH – DRINK DOCH ENE MET' },
        { type: 'bunting', seg: 17, u: 0.7, side: 0, dist: 0 },
        { type: 'crowd', seg: 17, u: 0.8, side: 1, dist: 10 },
        { type: 'crowd', seg: 20, u: 0.5, side: -1, dist: 10 },
        { type: 'bunting', seg: 20, u: 0.4, side: 0, dist: 0 }
      ]
    },
    {
      id: 'poller', name: 'Poller Wiesen Stunt-Park', district: 'Deutz Stunt-Arena', tag: 'TAG', order: 7,
      waypoints: ['Poller Wiesen', 'Lanxess Arena', 'Deutzer Werft', 'Rheinpark'],
      diff: 5, laps: 3, scale: 1.45,
      desc: 'Drei Loopings, zwei Sprünge, ein Tunnel unter der Deutzer Brücke und Steilkurven wie im Boxring. Die Poller Wiesen als Stunt-Arena: Tribünen, Kölsch-Stände, Riesenrad, Rhing. Wer hier bremst, hat verloren.',
      theme: { sky: 0x5fa8ff, fog: 0xd0e6ff, ground: 0x5e9a4a, sun: 0xffffff, road: [0x585858, 0x4a4a4a], night: false, water: 0x3f7fc0, street: 'park', arena: true,
        streets: ['POLLER WIESEN', 'ALFRED-SCHÜTTE-ALLEE', 'DEUTZER WERFT', 'AM RHEINPARK', 'ARENASTRASSE'],
        posters: ['STUNT-NACHT', 'LOOPING-CUP', 'KÖLSCH-FEST', 'LAMBOGINA', 'FC HEIMSPIEL'],
        far: [{ type: 'dom', angle: 200, dist: 150 }, { type: 'stmartin', angle: 215, dist: 120 }, { type: 'colonius', angle: 240, dist: 260 }, { type: 'archbridge', angle: 180, dist: 60 }, { type: 'kranhaus', angle: 160, dist: 100 }, { type: 'triangle', angle: 190, dist: 90 }] },
      // 0 str,1 L,2 str,3 loop,4 str,5 jump,6 str,7 L,8 hill,9 R,10 str,11 loop,12 str,13 L,14 tunnel,15 L,16 str,17 jump,18 str,19 L,20 str,21 loop,22 str,23 L,24 str
      segments: [
        { t: 'straight', len: 160 },
        { t: 'curve', angle: 90, r: 45, bank: 15 },
        { t: 'straight', len: 40 },
        { t: 'loop', r: 14, shift: 14 },
        { t: 'straight', len: 60 },
        { t: 'jump', ramp: 28, angle: 15, gap: 28 },
        { t: 'straight', len: 50 },
        { t: 'curve', angle: 90, r: 40, bank: 15 },
        { t: 'hill', len: 60, pitch: 16 },
        { t: 'curve', angle: -90, r: 40 },
        { t: 'straight', len: 30 },
        { t: 'loop', r: 13, shift: 14 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 40, bank: 15 },
        { t: 'tunnel', len: 70 },
        { t: 'curve', angle: 90, r: 40, bank: 15 },
        { t: 'straight', len: 60 },
        { t: 'jump', ramp: 30, angle: 16, gap: 32 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 45, bank: 15 },
        { t: 'straight', len: 30 },
        { t: 'loop', r: 14, shift: 14 },
        { t: 'straight', len: 60 },
        { t: 'straight', len: 40 },
        { t: 'straight', len: 40 }
      ],
      props: [
        { type: 'tuenn', seg: 0, u: 0.02, side: 1, dist: 9 },
        { type: 'tribuene', seg: 0, u: 0.3, side: -1, dist: 14, story: 'Poller Wiesen. Hee hann se fröher Fußball jespillt, jetz flieje hee Autos. Beides ohne Regeln.' },
        { type: 'crowd', seg: 0, u: 0.5, side: 1, dist: 10 },
        { type: 'koelsch', seg: 0, u: 0.7, side: -1, dist: 18 },
        { type: 'billboard', seg: 0, u: 0.85, side: 1, dist: 14, text: 'STUNT-PARK POLLER WIESEN – ET JEHT OP UN AV' },
        { type: 'arena', seg: 1, u: 0.5, side: -1, dist: 95, keep: 80, story: 'Die Arena. 18.000 Lück un alle wolle an mir vorbei. Hee kütt keiner rein ohne Kaat. Ich hann se alle jezählt.' },
        { type: 'crowd', seg: 2, u: 0.5, side: -1, dist: 10 },
        { type: 'tribuene', seg: 4, u: 0.3, side: 1, dist: 14, story: 'Looping. Einmol rund wie ne Zocker-Abend: oben bes de König, unten fällt et Kölsch us der Täsch.' },
        { type: 'marktstand', seg: 4, u: 0.8, side: -1, dist: 12 },
        { type: 'moewen', seg: 5, u: 0.5, side: 1, dist: 20 },
        { type: 'bude', seg: 6, u: 0.4, side: 1, dist: 11, text: 'KÖLSCH & KAMELLE' },
        { type: 'riesenrad', seg: 6, u: 0.7, side: -1, dist: 40, keep: 40, story: 'Riesenrad. Do sitz der Schäl drin un wartet, dat de Wagen rund kütt. Wie im Looping, nur langsamer.' },
        { type: 'zeppelin', seg: 8, u: 0.5, side: -1, dist: 40 },
        { type: 'flag', seg: 8, u: 0.2, side: 1, dist: 9 },
        { type: 'polizei', seg: 10, u: 0.5, side: 1, dist: 10 },
        { type: 'crowd', seg: 12, u: 0.3, side: -1, dist: 10 },
        { type: 'blitzer', seg: 12, u: 0.8, side: 1, dist: 8 },
        { type: 'rhineSide', seg: 16, u: 0.5, side: 1, dist: 110, w: 200, l: 700 },
        { type: 'promenade', seg: 16, u: 0.5, side: 1, dist: 30 },
        { type: 'boat', seg: 16, u: 0.4, side: 1, dist: 130 },
        { type: 'barge', seg: 16, u: 0.7, side: 1, dist: 110 },
        { type: 'litfass', seg: 16, u: 0.2, side: -1, dist: 10 },
        { type: 'haltestelle', seg: 18, u: 0.5, side: -1, dist: 10 },
        { type: 'bude', seg: 20, u: 0.5, side: 1, dist: 11, text: 'RIEVKOOCHE · APFELMUS · KÖLSCH' },
        { type: 'tanzbrunnen', seg: 22, u: 0.5, side: -1, dist: 30, story: 'Tanzbrunnen. 1957 hann se hee jetanzt, ich hann an der Tür jestanden. Manche stonn immer noch dovör.' },
        { type: 'koelsch', seg: 22, u: 0.8, side: 1, dist: 18 },
        { type: 'crowd', seg: 22, u: 0.3, side: 1, dist: 10 },
        { type: 'billboard', seg: 24, u: 0.5, side: -1, dist: 14, text: 'WER BREMST, ZAHLT DE KÖLSCH' },
        { type: 'tribuene', seg: 24, u: 0.8, side: 1, dist: 14 }
      ]
    }
  ];

  // ---------------- the host: dä Lange, doorman of the Ringe (no real names) ----------------
  const TUENN = {
    name: 'Dä Lange', emoji: '🎩',
    intro: [
      'He, wor et wirklich gefährlich es, da wächsste über dich hinaus. Also: Gas, Hätz un Verstand.',
      'Willkomme in Chicago am Rhein, Jung. Hee jilt nur eins: schneller sin als ich.',
      'Ich bin dä Lange. Zwei Meter zehn an der Tür. Mir jehört die Streck, der Asphalt un dat Kölsch danach.',
      'Kölle is keine Stadt. Kölle is e Jeföhl. Un heut Nacht is et schnell.'
    ],
    countdown: ['Drei…', 'Zwei…', 'Eins…', 'FOTT DOMET!'],
    crash: [
      'Jung, dat wor nix.',
      'Do fährs wie ne Kamellebüggel im Wind.',
      'Ich kenn ne juten Blechschmied. Ming Schwager. Kost extra.',
      'Et hätz schlecht, ävver et kütt! Weiter, Jung.',
      'Mer nennt dat Klüngel-Kurve: alle wissen et, keiner fährt se richtig.',
      'Schäl hätt dat besser jemaat. Un der sieht doppelt.'
    ],
    water: ['Un plumps in der Rhing. Der Schokoladenmuseum-Kapitän fischt dich raus.', 'Dat wor kein Sprung, dat wor ne Taufe.', 'Du solls über de Rhing, nit in de Rhing, Jung!'],
    loopFall: ['Vom Looping jefalle wie ne Kamellebüggel. Jas jeben, Jung!', 'Im Looping bremst mer nit. Dat is wie Kölsch ohne Deckel.', 'Die Elefanten im Zoo han jelacht. Beide.'],
    loopOk: ['Sauber durch de Looping! Dat kriegt en Deckelstrich.', 'Alaaf! Kopfüber un trotzdem jerade.'],
    jumpOk: ['Dat wor ne Sprung! Chicago am Rhein hat en neuen Stuntman.', 'Jeflogen wie ne Taube vum Dom. Nur mit mieh Stil.'],
    lap: ['Noch en Rund, Jung. Kölsch is kalt jestellt.', 'Rund vorbei. Der Köbes zählt mit.', 'Letzte Rund! Fott domet!'],
    win: ['Jewonne! Do bes jetz offiziell en Kölsche Jung. Oder Mädche. Ejal, Kölsch is för alle.', 'Ne Sieg in Chicago am Rhein. Ich hätt mich fast jefreut.', 'Alaaf, Jung! Dat kütt in de Express. Un ich kassier de Wette.'],
    lose: ['Verlore. Aber et hätt noch immer jot jejange. Meistens.', 'Et hätz schlecht, ävver et kütt! Nächstes Mol.', 'Nächstes Mol, Jung. Ming Streck läuft nit fott.'],
    overtake: ['Do bes vorbei! Jetz nit einschlofe.', 'Überholt wie de KVB am Ebertplatz.'],
    overtaken: ['Un fott is er. Wie ming Steuererklärung.', 'Der zieht an dir vorbei wie de Rhing bei Hochwasser.'],
    record: ['NEUE BESTZEIT! Dat schreib ich uff de Deckel.', 'Streckenrekord! Ich lass dich uff ne Bierdeckel drucke.'],
    turbo: ['Turbo! Jetz brennt de Asphalt.', 'Nitro, Jung! Dat riecht nach Kölsch un Benzin.'],
    damage: ['Totalschaden. Heinzel schraubt dich nachts wieder zesamme.', 'Dat Auto is fott. Dat nächste is uff Deckel.'],
    events: [
      'Ne Taube op der Windschutzscheibe. Typisch Domplatte.',
      'Der Köbes reicht dir im Vorbeifahre e Kölsch. Deckelstrich!',
      'Baustelle! Seit 1998. Fertig: irjendwann.',
      'Fräulein Anna wirft Kamelle. Direkt in dinge Kühler.',
      'Ne Möwe klaut dir de Fischbrötchen. Willkomme am Rhing.',
      'Klüngel Tom winkt. Dat kost dich später wat.'
    ],
    door: ['Du kütts hee nit rein! ... Ausnahmsweise doch.', 'Krawatte? Nä. Kölsch? Jo. Dann kütts de rein.', 'Ich hab 40 Johr an der Tür jestande. Ich kenn dich. Rein.', 'Turnschuh, Jung? Ejal. Heut Nacht is Rennen.'],
    tuennsTelefon: ['Man kennt sich, man hilft sich. Ming Türsteher stonn jetz op der Streck. Die andere kumme hee nit durch.', 'Ich hab telefoniert. Sechs Sekunde Ruhe vor dä Jecke. Kost dich e Kölsch.', 'Klüngel, Jung. De Ampeln sin jrün, nur för dich.'],
    express: [
      'EXPRESS: KÖLN – CHICAGO AM RHEIN! 50.000 Straftaten, e Drittel jeklärt.',
      'EXPRESS: Domschatz jeklaut! Der Lange T. hät e Alibi: Kölsch.',
      'EXPRESS: Banküberfall am Dom! Geiseln, Kripo, Kamelle.',
      'EXPRESS: Zocker verliert Villa in Marienburg. Jewinnt se an der Tür zurück.',
      'EXPRESS: Boxnacht im Sartory – Sieger: dä Köbes met dem Kranz.',
      'EXPRESS: Türsteher-Legende schreibt Kolumne. Redaktion hät Angst.',
      'EXPRESS: FC Johnny – de Zuhälter han eijene Fußballclub. Abstieg wie der FC.',
      'EXPRESS: Kölner Klüngel: Ampeln op der Ringe seit 1968 jrün för Bekannte.'
    ],
    grundgesetz: [
      'Artikel 1: Et es wie et es. Also fahr.',
      'Artikel 2: Et kütt wie et kütt. Meistens Klüngel Tom.',
      'Artikel 3: Et hätt noch immer jot jejange. Bes jetz.',
      'Artikel 4: Wat fott es, es fott. Dinge Führerschein zum Beispiel.',
      'Artikel 5: Et bliev nix wie et wor. Außer de Baustelle.',
      'Artikel 6: Kenne mer nit, bruche mer nit, fott domet. Sagt der Türsteher.',
      'Artikel 7: Wat wells de maache? Jas jeben.',
      'Artikel 8: Mach et jot, ävver nit zo off. Der Turbo.',
      'Artikel 9: Wat soll dä Quatsch? Der Blitzer.',
      'Artikel 10: Drinks de eine met? Kölsch = Turbo.',
      'Artikel 11: Do laachs de dich kapott. Über de Rhing jesprunge un in de Rhing jelandet.'
    ],
    radio: [
      'RADIO KÖLLE: Stau am Ebertplatz. Wie immer. Seit 1974.',
      'RADIO KÖLLE: Blitzer op der Zoobrücke. Dä Lange vum Ring hät ihn selbst opjestellt.',
      'RADIO KÖLLE: Der FC hät jewonne. Nä, Spaß. Weiter im Programm.',
      'RADIO KÖLLE: Die Oper is fertig! Ha, ha. Verkehrsmeldung: nä.',
      'RADIO KÖLLE: KVB-Streik. Die Bahn steht, die Jecke laufe.',
      'RADIO KÖLLE: Tauben op der Domplatte. Fahrt bitte vorsichtig durch de Kamelle.',
      'RADIO KÖLLE: Hochwasser. Der Rhing kütt. Der Schäl och.',
      'RADIO KÖLLE: Jetz LamboGina, danach de Verkehr. Oder umjekehrt.',
      'RADIO KÖLLE: Klüngel Tom hät de Ampeln jekauft. Alle jrün. Für ihn.',
      'RADIO KÖLLE: Wetter: Kölsch. Aussicht: noch mieh Kölsch.',
      'RADIO KÖLLE: Ne Zeppelin über dem Dom. Nä, dat is der Köbes met ner Runde.',
      'RADIO KÖLLE: Fräulein Anna fährt op der Ringe. Rettet üch, Jecke.',
      'RADIO KÖLLE: Die Polizei bittet: fahrt nit schneller als dä Lange an der Tür. Der hät Freunde.',
      'RADIO KÖLLE: In Düsseldorf hät et jeregnet. Wie schade.',
      'RADIO KÖLLE: Neonlicht op der Ringe, Palmen am Rhing. Miami? Nä. Kölle.'
    ],
    blitzer: [
      'BLITZ! Dat Foto kütt an de Bierdeckel. Knöllchen: 60 Euro.',
      'BLITZ! Klüngel Tom regelt dat. Für 40 Euro un e Kölsch.',
      'BLITZ! Lächel, Jung. Dat Bild hängt bald am Dom.',
      'BLITZ! De Stadt bedankt sich. Die Oper muss ja bezahlt werde.'
    ],
    tips: [
      'TIPP: Im Looping nit bremse. Dat is wie Kölsch ohne Deckel.',
      'TIPP: Turbo lädt beim Drifte. Also: quer is mieh.',
      'TIPP: Blitzer blitze ab 120. Klüngel Tom kennt jemand, der jemand kennt.',
      'TIPP: Steilkurve = Gas. Flachkurve = Hätz. Sonntagsfahrer = Tünnes.',
      'TIPP: Bei 100 % Schaden schraubt Heinzel nachts. Kost dich 3 Sekunde.',
      'TIPP: Kamera C: Cockpit. Fühlt sich an wie Taxi Willi um drei Uhr nachts.',
      'TIPP: Rheinsprung mit unter 90 = Rheinbad. Handtuch nit verjesse.'
    ],
    // place anecdotes: told when you pass a Brauhaus, Büdchen, Blitzer, church ... (the doorman knows every door in town)
    places: {
      brauhaus: ['Brauhaus. Der Köbes bringt Kölsch, bis de ne Deckel op et Glas lächs. Ich hann noch nie ne Deckel jebruch.', 'Hee drin hann ich mieh Lück rausjeschmisse als reinjelosse. Wor e jutes Jeschäft.', 'Kölsch is dat einzije Bier, dat mer och versteht, wenn mer et nit trinkt.', 'Der Wirt schuldet mir noch e Kölsch vun 1974. Ich wart. Ich hann Zick.', 'Die stonn vor der Tür, weil se drinne nit mieh stonn künne.'],
      buedchen: ['Büdchen. Dat Kölner Wohnzimmer. Kölsch, Zigaretten, Klüngel. Alles zum Mitnehmen.', 'Am Büdchen hann ich mieh jelernt als op der Schull. Vor allem rechne. Met Deckel.', 'Der Büdchen-Mann kennt jeden. Ich kenn ihn. Also kenn ich jeden.'],
      blitzer: ['Blitzer. Der einzije in Kölle, der pünktlich is.', 'Dat Ding hät mieh Fotos vun mir als ming Mutter.', 'Blitzer? Hee? Dat hät mir keiner jesaht. Ich kenn jemand, der dat wegmacht.'],
      polizei: ['Kripo. Die kenne mich, ich kenn die. Mer nicke sich zo. Mieh nit.', 'Peterwagen. Jrön-wieß wie de Ampel: erst jrön, dann wieß mer nix mieh.', 'Die Polizei is ming Freund un Helfer. Meistens Helfer. Beim Rausjonn.'],
      kirche: ['Kirch. Do jeht mer sonntags rein, wenn mer samstags nit reinjekumme is.', 'Zwölf romanische Kirche hät Kölle. Ich hann an elf Türe jestanden. Die zwölfte hät ne Pastor.', 'Der Pastor un ich hann dat selbe Jeschäft: mer entscheide, wer reinkütt.'],
      haltestelle: ['KVB. Kütt, wann se will. Wie de Schäl.', 'Die Bahn steht, die Lück laufe. Kölle funktioniert trotzdem. Irjendwie.', 'Linie 1 nach Weiden West. Do wollt noch nie einer hin. Fährt trotzdem.'],
      park: ['Jrön in Kölle. Hee lieje sonntags de Lück, die samstags bei mir nit reinjekumme sin.', 'Bäume. Die stonn och de janze Nacht. Ohne Kölsch. Respekt.', 'Park. Hee wor mol e Spielcasino. Nä, Spaß. Ävver et hät sich so anjefühlt.'],
      taxi: ['Taxi. Der Fahrer kennt de Stadt un ding Jeheimnisse. Beides fährt er nach Hus.', 'Hellelfenbein, dat Taxi. Wie ming Zähn nach dreißig Johr Zigarre.'],
      platz: ['Ne Platz in Kölle: Marktstand, Kölsch-Stand, Büdchen. Un e Denkmal, dat keiner kennt.', 'Op dem Platz hann se mich mol jefragt, ob ich der Bürjermeister bin. Ich hann nä jesaht. Wor jelogen.'],
      tram: ['Die Bahn. Wieß-rut wie der FC. Un jenau so pünktlich.'],
      tunnel: ['Tunnel. Dunkel, eng, laut. Wie der Boxkeller om Samstag.'],
      loop: ['Looping. Einmol rund, wie ne Zocker-Abend: oben bes de König, unten fällt et Kölsch us der Täsch.', 'Kopp unge, Jas oben. Dat es dat einzije, wat ich in der Schull jelernt hann.'],
      jump: ['Sprung. Wer hee bremst, badet. Wer nit bremst, badet vielleicht och. Ävver met Stil.']
    },
    // wall wisdom for graffiti, billboards and posters
    walls: ['DU KÜTTS HEE NIT REIN', 'MAN KENNT SICH · MAN HILFT SICH', 'ET HÄTT NOCH IMMER JOT JEJANGE', 'WER ZOLETZ KÜTT, ZAHLT DE KÖLSCH', 'KREDIT? NUR OP DECKEL', 'SEIT 1961 AN DER TÜR', 'KÖLSCH IS KEIN BIER, KÖLSCH IS NE HALTUNG', 'CHICAGO AM RHEIN – MER SIN DIE JUTE', 'GLÜCKSSPIEL: JEWINNE DEIT NUR DER TÜRSTEHER', 'DRINK DOCH ENE MET', 'HÄTZ UN VERSTAND – MEISTENS HÄTZ', 'KÖLLE IS E JEFÖHL', 'HEE RÄJIERT DER KLÜNGEL', 'DIE OPER KÜTT. IRJENDWANN.', 'JECK BLIEV JECK', 'KEIN EINLASS FÜR DÜSSELDORF', 'ZWEI METER ZEHN – UN KEINER KÜTT VORBEI', 'ET ES WIE ET ES', 'WAT FOTT ES, ES FOTT'],
    // shop signs with a wink
    shops: ['TÜRSTEHER-BEDARF', 'ZOCKERSTUBE', 'KLÜNGEL & SÖHNE', 'NACHTPORTIER-SCHULE', 'KREDIT & KÖLSCH', 'DECKEL-VERLEIH', 'ANWALT FÜR KNÖLLCHEN', 'BLECHSCHMIED · MING SCHWAGER', 'BÜTZJE-SERVICE', 'HÄTZ & VERSTAND GBR', 'FRISEUR ZUM LANGEN · 2,10 M', 'KAMELLE-GROSSHANDEL', 'HALVE HAHN – OHNE HAHN', 'DÜSSELDORF? NÄ.', 'AN- UND VERKAUF · FRAGEN SIE NICHT', 'CHANGE · WECHSELSTUBE · 1968', 'BOXSCHULE AM RING', 'SPIELCLUB · EINTRITT NUR MIT MIR'],
    // Kripo Kölle: the Peterwagen that shows up after three Knöllchen
    kripo: {
      start: ['Kripo Kölle! Drei Knöllchen, Jung. Jetz kütt der Peterwagen.', 'Hier spricht die Polizei Köln. Rechts ranfahren. Oder schneller werden, wie de wells.', 'Dat is die Kripo. Dä Lange hät nix jesaht. Noch nit.'],
      hit: ['Rammstoß! Dat jibt Punkte in Flensburg. Un ne Beule.', 'Der Peterwagen küsst dich. Ohne Bützje.', 'Kripo: „Anhalten!“ Du: „Später.“'],
      off: ['Ich hab met dem Kommissar telefoniert. Mer kenne uns vum Kegeln. Die Kripo dreht ab.', 'Klüngel, Jung. Der Peterwagen hät plötzlich Feierabend.', 'Dat wor der Hauptkommissar. Ich hann ihm 1974 an der Tür jeholfe. Erledigt.'],
      giveup: ['Kripo: „Schichtwechsel.“ Der Peterwagen dreht ab. Dat wor knapp.', 'Die Kripo hät dich verlore. Oder Hunger. Beides jut för dich.'],
      caught: ['Die Kripo hät dich zerlegt. Der Blechschmied freut sich. Ming Schwager.']
    },
    // the doorman's bet before the race
    wette: {
      offer: ['Ich wett {n} Kölsch, dat de vor {r} ins Ziel kütts. Zocker-Ehrenwort.', 'Wette? {n} Kölsch, du bes vor {r}. Ich hab ne jute Nas för sowat.', 'Op de Ringe wett mer. {n} Kölsch op dich jejen {r}. Enttäusch mich nit.'],
      won: ['Wette jewonne! {r} hinter dir. Ich schuld dir {n} Kölsch – kütt op der Deckel.', 'Jesaht, jetan: vor {r}. {n} Kölsch für dich. Ich zahl. Ausnahmsweise.'],
      lost: ['Wette verlore. {r} wor vor dir. Du schuldest mir {n} Kölsch. Ich hann Zick, ävver ich verjess nix.', '{r} vor dir. Dat kost dich {n} Kölsch. Der Zocker jewinnt immer. Dat bin ich.']
    },
    // Köbes hands you a Kölsch on the road
    koelschPick: ['Kölsch! Deckelstrich.', 'Ene met? Jo. Turbo!', 'Der Köbes kütt ungefragt. Wie immer.', 'Kölsch im Vorbeifahre. Dat kann nur Kölle.', 'Prost, Jung. Nit kleckern.', 'Deckel voll? Mer mache ne neue.'],
    // the beer-mat ranks
    ranks: [[0, 'LAUFKUNDSCHAFT'], [20, 'STAMMGAST'], [60, 'DECKELKÖNIG'], [150, 'EHRENMITGLIED VUM RING'], [400, 'LEGENDE VUM RING']],
    // Kölsch-Cup
    cup: {
      next: ['Nächste Streck, Jung. Der Cup wartet nit.', 'Weiter jeht et. Sieben Strecke, ein Kölsch-Cup. Kein Ausruhen.', 'Punkte notiert. Op der Deckel. Weiter.'],
      champion: ['KÖLSCH-CUP JEWONNE! Du bes jetz Stammgast vum Ring. Die Tür steht offe. Für immer.', 'Cup-Sieger! Selbst Klüngel Tom hät jeklatscht. Kurz.'],
      podium: ['Podium im Kölsch-Cup. Fast ne Legende. Dat Kölsch jeht op mich.'],
      loser: ['Cup vorbei. Nit jewonne, ävver jefahre. Dat is mieh als de meiste.', 'Der Cup is rum. Nächstes Johr, Jung. Ich stonn dann immer noch an der Tür.']
    },
    // EXPRESS headlines about your own race
    express2: {
      record: 'EXPRESS: NEUER STRECKENREKORD {track}! DÄ LANGE: „MING SCHULD.“',
      win: 'EXPRESS: UNBEKANNTER RASER JEWINNT – KLÜNGEL TOM FORDERT UNTERSUCHUNGSAUSSCHUSS',
      kripoCaught: 'EXPRESS: KRIPO STOPPT {car} OP DE RINGE – „ET WOR NOTWEHR“',
      kripo: 'EXPRESS: VERFOLGUNGSJAGD OP DE RINGE – PETERWAGEN VERLIERT {car} IM VEEDEL',
      knoellchen: 'EXPRESS: {n} KNÖLLCHEN IN DREI RUNDE – STADTKASSE SANIERT, OPER BEZAHLT',
      water: 'EXPRESS: {car} BADET IM RHING – TAUCHER SUCHE NOCH DE DECKEL',
      crashes: 'EXPRESS: BLECHSCHMIED MELDET REKORDUMSATZ – „MING SCHWAGER“, SAGT DÄ LANGE',
      last: 'EXPRESS: LETZTER PLATZ – „ICH HANN MIR DE KÖLSCH-STÄND ANJEKUCK“',
      koelsch: 'EXPRESS: {n} KÖLSCH IM VORBEIFAHRE – KÖBES: „DER HÄT NIT MOL JEBREMST“',
      podium: 'EXPRESS: PLATZ {p} – KÖLLE HÄT EN NEUE HOFFNUNG',
      default: 'EXPRESS: PLATZ {p} – KÖLLE HÄT SCHLIMMERES JESINN'
    },
    slogans: ['KÖLLE IST KEINE STADT. KÖLLE IST EIN GEFÜHL.', 'WILLKOMME IN KÖLN. GAS, HÄTZ UN VERSTAND – DAT ES KÖLLE 4D.', 'ET HÄTZ SCHLECHT, ÄVVER ET KÜTT!', 'WENN ET NACHT WIRD IN KÖLLE, VERZÄLLT DÄ LANGE VUM RING.', 'CHICAGO AM RHEIN, 1968. DU KÜTTS HEE NIT REIN.']
  };

  root.GameData = { CARS, DRIVERS, RIVALS, TRACKS, TUENN };
})(typeof window !== 'undefined' ? window : module.exports);
