/* ============================================================
   STUNTS KÖLLE 4D — Data: tracks, cars, archetypes, quotes
   ============================================================ */
(function (root) {
  'use strict';

  // ---------------- CARS ----------------
  // stats 1..5 (Tempo, Beschleunigung, Handling, Nitro) drive the physics numbers below
  const CARS = [
    { id: 'gti', name: 'Taunus GT', sub: 'Ford Taunus aus Niehl, 1970. Rot, laut, Kölner Werk.', color: 0xd62828, stripe: 0xffffff, shape: 'hatch',
      accel: 15, top: 55, brake: 32, grip: 1.15, steer: 1.2, nitro: 3, stats: [3, 4, 5, 3], plate: 'K-GTI 4D' },
    { id: 'turbo', name: 'Capri 2.8i', sub: 'Der Kölner Mustang. Beige wie de Tapete im Lovers Club.', color: 0xe0b060, stripe: 0x111111, shape: 'coupe',
      accel: 14, top: 60, brake: 30, grip: 1.0, steer: 1.0, nitro: 4, stats: [4, 4, 4, 4], plate: 'K-EF 28' },
    { id: 'rocket', name: 'Rheinland Rocket', sub: 'Bayerisches Coupé, Kölner Kennzeichen, Zocker-Streifen.', color: 0xf2f2f2, stripe: 0x1c3f95, shape: 'coupe2',
      accel: 12.5, top: 67, brake: 28, grip: 0.95, steer: 0.9, nitro: 4, stats: [5, 3, 3, 4], plate: 'K-RR 635' },
    { id: 'special', name: 'Milieu-Benz 280 SE', sub: 'Schwarz, lang, Chrom. Dat Auto vum Ring. Fahrer: dä Lange vum Ring.', color: 0x0e0e12, stripe: 0xff2d95, shape: 'limo',
      accel: 13, top: 71, brake: 26, grip: 0.9, steer: 0.95, nitro: 5, stats: [5, 4, 3, 5], plate: 'K-LT 1' },
    { id: 'countach', name: 'LamboGina Countach', sub: 'Weißer Keil aus Sant’Agata, Kölner Kennzeichen. Hochkant-Türen, Poster im Kinderzimmer.', color: 0xf4f4f2, stripe: 0x111111, shape: 'wedge',
      accel: 15, top: 74, brake: 27, grip: 0.92, steer: 0.9, nitro: 5, stats: [5, 5, 3, 5], plate: 'K-LG 88' }
  ];

  // ---------------- DRIVERS / RACERS ----------------
  // The first four can be picked as your own driver (difficulty). All of them race.
  const DRIVERS = [
    { id: 'tuennes', name: 'Tünnes', diff: 'LEICHT', diffN: 0, quote: 'Et jitt nix, wat et nit jitt!', sub: 'Der jecke Herz am Rhein.',
      skill: 0.86, wobble: 0.5, color: 0x2a4a8a, car: 'gti', aiMul: 0.76,
      lines: { start: ['Et jitt nix, wat et nit jitt!', 'Loss jonn, Jung!'], overtake: ['Ha! Do bes zo langsam, Kolleg!', 'Vörbei wie de Zoch!', 'Kölle vörre, wie et sich jehört!', 'Ming Oma fährt schneller. Un die hät kein Auto.'], overtaken: ['Nä, wat is dat dann?', 'Ich hann dich jesinn!', 'Dat wor de Rhingnebel!', 'Ich hab dich vorjelosse. Aus Höflichkeit.'], crash: ['Dat wor der Schäl, nit ich!', 'Autsch. Ävver et hätt jot jejange.', 'Wer wor dat? Der Schäl! Immer der Schäl.'], taunt: ['Dat wor ne Sonntagsfahrer!', 'Jung, de Bremse is links. Oder rechts. Eins von beiden.'], win: ['Tünnes vörre! Alaaf!', 'Ne Kölsche jewinnt, wie immer.'], lose: ['Nächste Woch, Jung.', 'Dat wor ming Schonrund.'] } },
    { id: 'schael', name: 'Schäl', diff: 'MITTEL', diffN: 1, quote: 'Ich weiß eine Abkürzung!', sub: 'Et hätt noch immer jot jejange.',
      skill: 0.9, wobble: 0.35, color: 0x6a4a2a, car: 'turbo', aiMul: 0.83,
      lines: { start: ['Ich weiß eine Abkürzung!', 'Tünnes, du bes zo lang för dat Auto.'], overtake: ['Do hab ich jar nit hinjeguckt.', 'Links oder rechts, för mich is dat ejal.', 'Die Abkürzung jeht durch de Dom. Frag nit.', 'Ich seh dich doppelt, also überhol ich zweimal.'], overtaken: ['Dat wor ne optische Täuschung.', 'Ich seh zwei von dir. Un beide sin langsam.', 'Dat wor der linke Auge. Der rechte hät dich jesinn.'], crash: ['Wor dat de Wand oder de Rhing?', 'Ich hab de Kurve doppelt jesehn.', 'Die Kurve wor jestern noch woanders.'], taunt: ['Ich hab dat doppelt jesinn. Wor beides schlimm.', 'Die Abkürzung wor nit de Wand, Jung.'], win: ['Schäl jewinnt. Tünnes zahlt.', 'Die Abkürzung wor jot!'], lose: ['Ich hab de Ziellinie zweimal jesehn un die falsche jenomme.', 'Nächstes Mol mit Brille.'] } },
    { id: 'heinzel', name: 'Heinzel', diff: 'SCHWER', diffN: 2, quote: 'Mer stelle alles op Kopp!', sub: 'Nachts baut er, tags pennt er.',
      skill: 0.94, wobble: 0.22, color: 0xc1121f, car: 'rocket', aiMul: 0.9,
      lines: { start: ['Mer stelle alles op Kopp!', 'Ich hab de Motor heut Nacht jebaut.'], overtake: ['Schraubenschlüssel raus, vorbei!', 'Dat Heinzelmännche is schneller als du kucks.', 'Nachts jebaut, jetz jeschoben. Tschö!'], overtaken: ['Hä? Wer wor dat?', 'Da fehlt ne Schraube. Bei dir.', 'Du hast ne Schraube locker. Ich hab se heut Nacht jesucht.'], crash: ['Dat repariere ich heut Nacht.', 'Kein Problem, ich hab Ersatzteile.', 'Blech. Ich hol de Hammer.'], taunt: ['Dat repariere ich. Kost dich ne Nacht.', 'Blech. Ich hol de Hammer un de Kölsch.'], win: ['Heinzel vörre, un keiner hät et jesehn.', 'Nachts jebaut, tags jewonne.'], lose: ['Ich wor müd. Tagschicht.', 'Nächstes Mol schraub ich am Nitro.'] } },
    { id: 'langer', name: 'Dä Lange', diff: 'EXPERTE', diffN: 3, quote: 'Du kütts hee nit rein!', sub: 'Türsteher, Zocker, Legende. Seit 1961 op de Ringe.',
      skill: 0.985, wobble: 0.1, color: 0x111111, car: 'special', aiMul: 0.97,
      lines: { start: ['Du kütts hee nit rein! Ausnahmsweise doch. Fahr.', 'Seit 1961 stonn ich an der Tür. Heut fahr ich vorbei.', 'Chicago am Rhein, Jung. Hee jilt nur eins: schneller sin.'], overtake: ['Du fährs wie en Ratssitzung: lang un ohne Ergebnis.', 'Ich schick dir de Rechnung för de Bremsspur.', 'Du kütts hee nit vorbei. Ich schon.', 'Zwei Meter zehn Vorsprung. Jenau ming Größe.'], overtaken: ['Dat wor Klüngel, dat zählt nit!', 'Jenieß et, Jung. Dat hält nit lang.', 'Hät ich dich rinjelosse? Nä. Trotzdem bes de drin.'], crash: ['Et hätt noch immer jot jejange. Bes jetz.', 'Ich kenn ne juten Blechschmied. Ming Schwager.', 'Blechschmied. Ming Schwager. Kost extra.'], taunt: ['Du kütts hee nit rein. Un och nit rum.', 'Zwei Meter zehn Anlauf un dann de Wand. Respekt.'], win: ['Wie immer. Der Türsteher verliert nit in singer Stadt.', 'Kumm, ich jeb dir ene us. Zum Tröste.'], lose: ['Dat wor Zufall. Ich hatt den Zylinder im Auge.', 'Jut. Du kriss en Job. Fahrer. Bei mir.'] } },
    { id: 'anna', name: 'Fräulein Anna', sub: 'Funkenmariechen mit Bleifuß.',
      skill: 0.9, wobble: 0.3, color: 0xff5fa2, car: 'gti',
      lines: { start: ['Alaaf, ihr Jecke!', 'Wer zuletzt kütt, zahlt de Kölsch.'], overtake: ['Bützje! Un tschüss!', 'Dat wor ne Tanzschritt, Jung.', 'Tanzmariechen vörre! Hebe, Jung, hebe!'], overtaken: ['Nit so frech!', 'Ich komm wieder, wie de Fastelovend.', 'Frech! Dat jibt kein Bützje.'], crash: ['Ups. Dat wor de Absatz.', 'Kamelle! Ich mein: Bremse!', 'Ming Schuh! Der Absatz hing am Gas.'], taunt: ['Ups! Wor dat ne Tanzschritt?', 'Bützje för de Wand, Jung.'], win: ['Anna vörre! Strüßjer för alle!', 'Ne Mariechen jewinnt.'], lose: ['Ming Schuh wor zo hoch.', 'Nächstes Mol im Zoch.'] } },
    { id: 'tom', name: 'Klüngel Tom', sub: 'Man kennt sich, man hilft sich.',
      skill: 0.92, wobble: 0.2, color: 0x444444, car: 'special',
      lines: { start: ['Man kennt sich, man hilft sich.', 'Die Pole Position hab ich schon vorm Rennen gewonnen.'], overtake: ['Das wurde im Ausschuss so beschlossen.', 'Nicht persönlich nehmen. Rein geschäftlich.', 'Man kennt sich. Man überholt sich.'], overtaken: ['Dazu gibt es einen Untersuchungsausschuss.', 'Das Protokoll wird angepasst.', 'Das wird noch geprüft. Vom Ausschuss.'], crash: ['Das war ein Bauprojekt. Wie die Oper.', 'Wir kannten das Ergebnis schon vorher.', 'Das ist kein Unfall. Das ist eine Baumaßnahme.'], taunt: ['Das nehmen wir ins Protokoll. Unter Sonstiges.', 'Für den Schaden kenne ich jemanden. Kostet.'], win: ['Wie vereinbart. Danke, Tünn.', 'Ein Sieg für die Stadt. Also für mich.'], lose: ['Wir lassen das Ergebnis prüfen.', 'Die Kosten explodieren übrigens.'] } },
    { id: 'willi', name: 'Taxi Willi', sub: '30 Jahre Nachtschicht am Ring.',
      skill: 0.9, wobble: 0.3, color: 0xf2e6b1, car: 'turbo',
      lines: { start: ['Zoobrücke gesperrt, ich kenn ne Abkürzung.', 'Taxameter läuft, Kollege.'], overtake: ['Kurzstrecke. Sieben Euro.', 'Nachtzuschlag kommt noch dazu.', 'Taxi! Sie sind zu langsam für Köln.'], overtaken: ['Ich lass dich vor. Trinkgeld?', 'Fahrgast drin, ruhig fahren.', 'Fahrgast, festhalten. Der da vorne ist neu.'], crash: ['Das war der Fahrgast, nicht ich.', 'Kein Problem, Bruder, alles Blech.', 'Das zahlt die Versicherung. Also der Fahrgast.'], taunt: ['Fahrgast! Der da hat’s nicht drauf.', 'Das wäre mit Taxi nicht passiert. Sieben Euro.'], win: ['Ziel erreicht. Zahlen bitte.', 'Sieg. Rückfahrt kostet extra.'], lose: ['Ich hatte noch Fahrgast drin.', 'Nächstes Mal ohne Taxameter.'] } },
    { id: 'koebes', name: 'Köbes Hermann', sub: 'Grantig, schnell, bringt ungefragt Nachschub.',
      skill: 0.88, wobble: 0.4, color: 0x3a6ea5, car: 'rocket',
      lines: { start: ['Wat willste? Kölsch oder Pokal?', 'Trink doch ene met. Nach dem Rennen.'], overtake: ['Ich bring dir jleich ene Kranz Rückspiejel.', 'Dat is kein Bier, dat is Beschleunigung.', 'Ene met? Nä, ich fahr vorbei.'], overtaken: ['Do verdiens dir keine Deckel bei mir.', 'Ich hab noch drei Tische. Wart ab.', 'Kein Deckel för dich. Nie mehr.'], crash: ['Einer jeht noch. Einer jeht noch rein.', 'Dat jibt Bierdeckel-Striche för dich.', 'Dat Kölsch is heil. Dat Auto nit.'], taunt: ['Einer jeht noch. Bei dir wohl nit.', 'Dat jibt kein Deckel. Dat jibt ne Rechnung.'], win: ['Der Kellner jewinnt. Trinkgeld optional.', 'Dat macht 23,50. Plus Sieg.'], lose: ['Ich wor nur Deckel holen.', 'Bei mir jab et Stau am Tresen.'] } },
    { id: 'tango', name: 'Tango', diff: 'MITTEL', diffN: 1, quote: 'Verdamp lang her, dat du vorne wors.', sub: 'Dünn, schwarze Mähne, Kajal. Rock op de Ringe, seit 1984.',
      skill: 0.91, wobble: 0.28, color: 0x1a1024, car: 'turbo', aiMul: 0.85,
      lines: { start: ['Verdamp lang her, dat du vorne wors.', 'Sonic Ballroom hät zo. Also fahre mer.', 'Kajal sitzt, Motor läuft. Rock op de Ringe.'], overtake: ['Dat wor ne Gitarrensolo, Jung. Du wors der Bass.', 'Zo langsam för de erste Reih. Zo langsam för de letzte.', 'Bützje im Vorbeifahre. Nä, doch nit.', 'Ming Haare sin schneller als ding Auto.'], overtaken: ['Falsche Ton. Ich komm zoröck, wie der Refrain.', 'Dat wor nur de Strophe. Wart op der Refrain.', 'Ich hann dich durchjelosse. Aus Stil.'], crash: ['Dat wor Punk. Nit jewollt, ävver ehrlich.', 'Verdamp lang her, dat ich jecrasht bin. Bes jetz.', 'Die Mähne sitzt noch. Der Rest nit.'], taunt: ['Rock’n’Roll, Jung. Du fährs Schlager.', 'Ich seh us wie e Mädche un fahr wie der Düvel. Du siehs us wie e Auto un fährs wie e Mädche. Sorry, Anna.'], win: ['Zugabe? Nä. Kölsch.', 'Erste Reih, wie im Luxor. Un du stehs draußen.'], lose: ['Dat wor der Soundcheck. Jetz kütt et Konzert.', 'Ich hann de falsche Kassett drin jehatt.'] } },
    { id: 'taesch', name: 'Täsch', diff: 'SCHWER', diffN: 2, quote: 'Hantel, Haarspray, Hätz.', sub: 'Muskeln, blonde Lockenmähne, Kutte. Der Türsteher vum Rose Club.',
      skill: 0.93, wobble: 0.24, color: 0x3a5a8a, car: 'gti', aiMul: 0.9,
      lines: { start: ['Hantel, Haarspray, Hätz. Loss jonn.', 'Ich hann de Motor met der Hand jehalde. Jetz nit mieh.', 'Rose Club, Nachtschicht. Danach dat hee.'], overtake: ['Dat wor Muskelkraft, Jung. Ohne Nitro.', 'Locke im Wind, du im Rückspiejel.', 'Ich drück dich wie ne Hantel. Weg bes de.', 'Kutte an, Gas drop. Tschö.'], overtaken: ['Kraftraum wor jestern zo. Merkt mer.', 'Locke im Auge. Ich seh nix. Jleich wieder.', 'Dat wor ne Aufwärmsatz.'], crash: ['Dat Auto hät nachjejovve. Ich nit.', 'Ich hann de Wand jedrückt. Die Wand hät jewonne.', 'Haarspray brennt. Merk dir dat.'], taunt: ['Ich hebb dich un ding Auto op einmol. Wells de?', 'Bei mir kütt keiner rein ohne Muckis. Du och nit.'], win: ['Sieg. Un jetz Eiweiß.', 'Wer die Locke hät, hät et Pokal.'], lose: ['Muskelkater. Im Jaspedal.', 'Ich hann der Hantel zo lang jehalde un dat Lenkrad zo kurz.'] } }
  ];
  const RIVALS = DRIVERS; // backwards compat

  // ---------------- TRACKS ----------------
  // All angles: + = left. Distances in metres. Each track closes on itself.
  const TRACKS = [
    {
      id: 'dom', name: 'Domblitz 4D', district: 'Dom & Rhein im Morgengrauen', tag: 'MORJENS', order: 2,
      waypoints: ['Dom', 'Heinzelmännchenbrunnen', 'Alter Markt', 'Hohenzollernbrücke', 'Deutz', 'Rheinsprung'],
      diff: 2, laps: 3, scale: 1.45,
      desc: 'Im Morgengrauen vom Dom zum Rhein und wieder zurück. Über die Hohenzollernbrücke nach Deutz, mit Rheinsprung und dickem Po. Tauben inklusive.',
      theme: { sky: 0x5a78b8, fog: 0xffc4a0, ground: 0xa99b86, sun: 0xffd4a8, road: [0x6a6a70, 0x5c5c62], night: false, dawn: true, water: 0x5a7fb0, street: 'altstadt',
        streets: ['HOHE STRASSE', 'DOMKLOSTER', 'GLOCKENGASSE', 'OTTOPLATZ', 'AM HOF', 'TRANKGASSE', 'UNTER FETTENHENNEN', 'FRANKENWERFT', 'DEUTZER FREIHEIT', 'ALTER MARKT', 'HEUMARKT'],
        shops: ['BRAUHAUS', 'HALVE HAHN', 'RIEVKOOCHE', 'EAU DE COLOGNE', 'KÖLSCH', 'FC FANSHOP', 'DOM-SOUVENIRS', 'BÄCKEREI MERZENICH', '4711', 'KVB KUNDENCENTER'],
        far: [{ type: 'colonius', angle: 200, dist: 260 }, { type: 'triangle', angle: 20, dist: 80 }, { type: 'archbridge', angle: 300, dist: 60 }, { type: 'flatbridge', angle: 330, dist: 80 }] },
      // seg: 0 start straight, 1 L, 2 str, 3 hill, 4 str, 5 L, 6 str, 7 R, 8 str, 9 L, 10 bridge, 11 L, 12 str, 13 L, 14 str
      segments: [
        { t: 'straight', len: 140 },
        { t: 'curve', angle: 90, r: 45 },
        { t: 'straight', len: 60 },
        { t: 'loop', r: 13, shift: 14 },
        { t: 'hill', len: 70, pitch: 12 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 45, bank: 10 },
        { t: 'straight', len: 80 },
        { t: 'curve', angle: -90, r: 35 },
        { t: 'straight', len: 50 },
        { t: 'curve', angle: 90, r: 35 },
        { t: 'bridge', len: 160 },
        { t: 'curve', angle: 90, r: 50, bank: 12 },
        { t: 'straight', len: 40 },
        { t: 'jump', ramp: 30, angle: 16, gap: 34 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 50, bank: 12 },
        { t: 'straight', len: 80 }
      ],
      props: [
        { type: 'tuenn', seg: 0, u: 0.02, side: 1, dist: 9 },
        { type: 'schael', seg: 0, u: 0.02, side: -1, dist: 9 },
        { type: 'crowd', seg: 0, u: 0.06, side: 1, dist: 10 },
        { type: 'crowd', seg: 0, u: 0.06, side: -1, dist: 10 },
        { type: 'dom', seg: 0, u: 0.5, side: -1, dist: 78, keep: 120, story: 'Der Dom. 632 Johr jebaut. Länger als ming Tour. Un immer noch nit fertig, wie de Kölner Oper.' },
        { type: 'denkmal', seg: 5, u: 0.35, side: -1, dist: 14, story: 'Tünnes un Schäl. Der eine ehrlich un e bessje dumm, der andere schlau un e bessje krumm. Zesamme: Kölle.' },
        { type: 'heinzelbrunnen', seg: 2, u: 0.5, side: 1, dist: 16, keep: 22, story: 'Heinzelmännchenbrunnen. Nachts han se jeschafft, bis de Frau vum Schneider Erbse jestreut hät. Seitdem schafft in Kölle keiner mieh nachts. Außer mir.' },
        { type: 'koelsch', seg: 2, u: 0.4, side: 1, dist: 18 },
        { type: 'billboard', seg: 2, u: 0.62, side: 1, dist: 14, text: 'FRÜH AM DOM · SEIT 1904' },
        { type: 'hbf', seg: 1, u: 0.5, side: -1, dist: 95, keep: 90, story: 'Hauptbahnhof. 1975: Banküberfall met Geiseln, direkt am Dom. Chicago am Rhein, Jung. Heut nur noch Taube un Verspätung.' },
        { type: 'museum', seg: 0, u: 0.85, side: 1, dist: 42 },
        { type: 'musicaldome', seg: 2, u: 0.3, side: 1, dist: 70 },
        { type: 'stmartin', seg: 5, u: 0.5, side: -1, dist: 48, keep: 70 },
        { type: 'altstadt', seg: 4, u: 0.5, side: 1, dist: 24, seed: 3, n: 8 },
        { type: 'altstadt', seg: 7, u: 0.4, side: -1, dist: 24, seed: 8, n: 8 },
        { type: 'buedchen', seg: 7, u: 0.8, side: 1, dist: 11 },
        { type: 'bude', seg: 0, u: 0.35, side: 1, dist: 12, text: 'RIEVKOOCHE AM DOM' },
        { type: 'marktstand', seg: 5, u: 0.3, side: 1, dist: 13 }, { type: 'marktstand', seg: 5, u: 0.4, side: 1, dist: 13 }, { type: 'marktstand', seg: 5, u: 0.5, side: 1, dist: 13 },
        { type: 'blitzer', seg: 2, u: 0.9, side: -1, dist: 8 },
        { type: 'moewen', seg: 11, u: 0.5, side: 1, dist: 30, face: false },
        { type: 'zeppelin', seg: 11, u: 0.3, side: -1, dist: 80, face: false },
        { type: 'polizei', seg: 9, u: 0.2, side: -1, dist: 10 },
        { type: 'blitzer', seg: 15, u: 0.8, side: 1, dist: 8 },
        { type: 'haltestelle', seg: 9, u: 0.4, side: 1, dist: 10 },
        { type: 'tram', seg: 9, u: 0.7, side: 1, dist: 12 },
        { type: 'billboard', seg: 2, u: 0.7, side: -1, dist: 14, text: 'RING KÖLSCH – ET LÄUFT' },
        { type: 'rgm', seg: 0, u: 0.7, side: -1, dist: 40, keep: 60 },
        { type: 'eaudecologne', seg: 2, u: 0.75, side: -1, dist: 28, keep: 40 },
        { type: 'rathaus', seg: 5, u: 0.5, side: 1, dist: 42, keep: 70, story: 'Rathaus. Hee wohnt der Klüngel. Man kennt sich, man hilft sich. Un wer keinen kennt, wartet.' },
        { type: 'reiter', seg: 7, u: 0.15, side: -1, dist: 16 },
        { type: 'cafe', seg: 4, u: 0.2, side: 1, dist: 13 },
        { type: 'cafe', seg: 7, u: 0.55, side: -1, dist: 13 },
        { type: 'tramline', seg: 0, u: 0.5, side: -1, dist: 14, len: 180, face: false },
        { type: 'rhineSide', seg: 7, u: 0.5, side: 1, dist: 170, l: 700, w: 240 },
        { type: 'promenade', seg: 7, u: 0.5, side: 1, dist: 44 },
        { type: 'rhine', seg: 11, u: 0.5, side: 0, dist: 0 },
        { type: 'hbarch', seg: 11, u: 0.5, side: 0, dist: 0, story: 'Hohenzollernbrücke. 500.000 Liebesschlösser. Un e paar Schlüssel im Rhing, die han ich selbst jeworfe.' },
        { type: 'boat', seg: 11, u: 0.3, side: 1, dist: 60 },
        { type: 'barge', seg: 11, u: 0.7, side: -1, dist: 70 },
        { type: 'triangle', seg: 12, u: 0.6, side: -1, dist: 75, keep: 60 },
        { type: 'hyatt', seg: 12, u: 0.9, side: -1, dist: 60, keep: 50 },
        { type: 'messeturm', seg: 15, u: 0.5, side: 1, dist: 70 },
        { type: 'tanzbrunnen', seg: 15, u: 0.15, side: -1, dist: 45, keep: 40 },
        { type: 'rhine', seg: 14, u: 0.55, side: 0, dist: 0 },
        { type: 'boat', seg: 14, u: 0.5, side: 1, dist: 55 },
        { type: 'rheinsprung', seg: 13, u: 0.6, side: 1, dist: 10 },
        { type: 'tramline', seg: 15, u: 0.5, side: 1, dist: 14, len: 120, face: false },
        { type: 'row', seg: 15, u: 0.3, side: -1, dist: 24, style: 'concrete', seed: 4, n: 5 },
        { type: 'koelsch', seg: 15, u: 0.9, side: 1, dist: 18 },
        { type: 'billboard', seg: 17, u: 0.3, side: -1, dist: 14, text: 'CHICAGO AM RHEIN – MAN KENNT SICH' },
        { type: 'flag', seg: 17, u: 0.6, side: 1, dist: 9 }
      ]
    },
    {
      id: 'rheinauhafen', name: 'Rheinauhafen 4D', district: 'Kranhäuser to the Limit', tag: 'ABEND', order: 6,
      waypoints: ['Kranhäuser', 'Schokoladenmuseum', 'Severinsbrücke', 'Chlodwigplatz', 'Bayenturm', 'Rheinsprung'],
      diff: 3, laps: 3, scale: 1.45,
      desc: 'Volle Pulle die Rheinuferstraße runter, Sprung über das Hafenbecken zwischen den Kranhäusern, Schokoladenmuseum, Severinsbrücke. Wer zu kurz springt, badet im Rhing.',
      theme: { sky: 0x6a2a8a, fog: 0xff8a9a, ground: 0x8a8890, sun: 0xffb0c0, road: [0x5a5560, 0x4c4852], night: false, sunset: true, miami: true, water: 0x2f6fa8, street: 'modern',
        posters: ['RHEINSTRAND', 'VICE KÖLLE', 'KRANHAUS-PARTY', 'SCHOKOLADE', 'LAMBOGINA'],
        streets: ['RHEINUFERSTR.', 'UBIERRING', 'ANNA-SCHNEIDER-STEIG', 'HARRY-BLUM-PLATZ', 'IM ZOLLHAFEN', 'AGRIPPINAWERFT', 'BAYENSTRASSE', 'HOLZMARKT', 'SEVERINSTRASSE', 'CHLODWIGPLATZ'],
        shops: ['HAFENBAR', 'SCHOKOLADE', 'CAFÉ AM HAFEN', 'KÖLSCH', 'SUSHI', 'GALERIE', 'YACHTSERVICE'],
        far: [{ type: 'dom', angle: 100, dist: 160 }, { type: 'colonius', angle: 140, dist: 200 }, { type: 'archbridge', angle: 60, dist: 40 }, { type: 'stmartin', angle: 90, dist: 120 }] },
      // 0 str,1 R,2 str,3 jump,4 str,5 R,6 str,7 L,8 str,9 R,10 hill,11 str,12 R,13 str,14 jump,15 str,16 R,17 str
      segments: [
        { t: 'straight', len: 120 },
        { t: 'curve', angle: -90, r: 40 },
        { t: 'straight', len: 40 },
        { t: 'jump', ramp: 30, angle: 16, gap: 32 },
        { t: 'straight', len: 60 },
        { t: 'loop', r: 13, shift: 14 },
        { t: 'curve', angle: -90, r: 40, bank: 10 },
        { t: 'corkscrew', len: 64, r: 9, turns: 1 },
        { t: 'curve', angle: 90, r: 30 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: -90, r: 30 },
        { t: 'hill', len: 60, pitch: 14 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: -90, r: 40, bank: 12 },
        { t: 'straight', len: 45 },
        { t: 'jump', ramp: 24, angle: 14, gap: 24 },
        { t: 'straight', len: 60 },
        { t: 'curve', angle: -90, r: 40 },
        { t: 'straight', len: 12 }
      ],
      props: [
        { type: 'zockertisch', seg: 9, u: 0.25, side: 1, dist: 12, story: 'Am Hafen wird jezockt, seit et de Hafen jibt. Die Kranhäuser hann se och verspillt. Zweimal.' },
        { type: 'tuenn', seg: 0, u: 0.02, side: 1, dist: 9 },
        { type: 'crowd', seg: 0, u: 0.06, side: -1, dist: 10 },
        { type: 'kranhaus', seg: 0, u: 0.3, side: 1, dist: 42, keep: 40, story: 'Kranhäuser. Früher Hafen, Schmuggel un Zoll. Heut Penthouse, Latte un Zoll. Hät sich nix jeändert, nur de Preise.' },
        { type: 'kranhaus', seg: 0, u: 0.55, side: 1, dist: 42, keep: 40 },
        { type: 'kranhaus', seg: 0, u: 0.8, side: 1, dist: 42, keep: 40 },
        { type: 'palm', seg: 0, u: 0.2, side: 1, dist: 12, h: 8 }, { type: 'palm', seg: 0, u: 0.35, side: 1, dist: 12, h: 7, seed: 2 }, { type: 'palm', seg: 0, u: 0.5, side: 1, dist: 12, h: 9, seed: 3 }, { type: 'palm', seg: 0, u: 0.65, side: 1, dist: 12, h: 7, seed: 4 }, { type: 'palm', seg: 0, u: 0.8, side: 1, dist: 12, h: 8, seed: 5 },
        { type: 'palm', seg: 0, u: 0.25, side: -1, dist: 11, h: 6, seed: 6 }, { type: 'palm', seg: 0, u: 0.55, side: -1, dist: 11, h: 7, seed: 7 },
        { type: 'speedboat', seg: 0, u: 0.5, side: 1, dist: 110, face: false },
        { type: 'moewen', seg: 0, u: 0.6, side: 1, dist: 70, face: false },
        { type: 'blitzer', seg: 0, u: 0.92, side: -1, dist: 8 },
        { type: 'riesenrad', seg: 6, u: 0.5, side: -1, dist: 60, keep: 50 },
        { type: 'beach', seg: 7, u: 0.5, side: 1, dist: 62, keep: 60 },
        { type: 'palm', seg: 7, u: 0.3, side: 1, dist: 12, h: 8, seed: 11 }, { type: 'palm', seg: 7, u: 0.7, side: 1, dist: 12, h: 7, seed: 12 },
        { type: 'neon', seg: 7, u: 0.2, side: -1, dist: 13, text: 'FLAMINGO BAR', color: '#ff2d95', small: true, light: false },
        { type: 'bude', seg: 9, u: 0.5, side: -1, dist: 11, text: 'FISCHBRÖTCHEN · KÖLSCH' },
        { type: 'palm', seg: 16, u: 0.3, side: -1, dist: 11, h: 8, seed: 8 }, { type: 'palm', seg: 16, u: 0.6, side: -1, dist: 11, h: 7, seed: 9 },
        { type: 'polizei', seg: 16, u: 0.8, side: 1, dist: 10 },
        { type: 'rhineSide', seg: 0, u: 0.25, side: 1, dist: 140, l: 300, w: 160 },
        { type: 'promenade', seg: 0, u: 0.4, side: 1, dist: 62 },
        { type: 'barge', seg: 0, u: 0.4, side: 1, dist: 120 },
        { type: 'boat', seg: 0, u: 0.9, side: 1, dist: 100 },
        { type: 'rhine', seg: 3, u: 0.55, side: 0, dist: 0 },
        { type: 'boat', seg: 3, u: 0.5, side: 1, dist: 45 },
        { type: 'schoko', seg: 4, u: 0.5, side: 1, dist: 40, keep: 50 },
        { type: 'severinsbruecke', seg: 4, u: 0.9, side: 1, dist: 150, face: false },
        { type: 'billboard', seg: 7, u: 0.5, side: 1, dist: 14, text: 'HALVE HAHN GRILL – SEIT 1928' },
        { type: 'malakoff', seg: 4, u: 0.25, side: 1, dist: 22, keep: 20, story: 'Malakoffturm. Fröher hät der de Hafen bewacht, heut de Schokolad. Beides hann se mir nit anvertraut.' },
        { type: 'halle', seg: 0, u: 0.65, side: -1, dist: 52, keep: 50, story: 'Lagerhaus Siebengebirge. 1909, hundert Meter Backstein. Hee drin lag mieh Kaffee als in janz Düsseldorf Verstand.' },
        { type: 'bayenturm', seg: 16, u: 0.35, side: 1, dist: 24, keep: 28, story: 'Bayenturm. 1262 hann de Kölner hee de Erzbischof rusjeworfe. Der erste Türsteher-Job in Kölle. Ohne mich.' },
        { type: 'severinstor', seg: 9, u: 0.5, side: 1, dist: 30 },
        { type: 'kirche', seg: 10, u: 0.5, side: -1, dist: 40, h: 45, color: 0xb9a184 },
        { type: 'row', seg: 12, u: 0.5, side: -1, dist: 24, style: 'gruenderzeit', seed: 12, n: 5 },
        { type: 'tramline', seg: 12, u: 0.5, side: 1, dist: 14, len: 90, face: false },
        { type: 'cafe', seg: 11, u: 0.8, side: 1, dist: 13 },
        { type: 'buedchen', seg: 12, u: 0.2, side: 1, dist: 11 },
        { type: 'koelsch', seg: 14, u: 0.5, side: -1, dist: 18 },
        { type: 'rhine', seg: 15, u: 0.55, side: 0, dist: 0 },
        { type: 'barge', seg: 15, u: 0.5, side: -1, dist: 60 },
        { type: 'row', seg: 16, u: 0.5, side: -1, dist: 24, style: 'modern', seed: 2, n: 4 },
        { type: 'billboard', seg: 16, u: 0.8, side: 1, dist: 14, text: 'DÄ LANGE – KÖLSCH & KREDIT' },
        { type: 'haltestelle', seg: 18, u: 0.4, side: -1, dist: 10 }
      ]
    },
    {
      id: 'zoo', name: 'Schäl Sick Schraube', district: 'Deutz & Mülheim', tag: 'TAG', order: 3,
      waypoints: ['Zoo & Flora', 'Zoobrücke', 'Rheinpark', 'Messe', 'Mülheimer Hafen', 'Mülheimer Brücke'],
      diff: 4, laps: 3, scale: 1.45,
      desc: 'Vom Zoo über die Zoobrücke nach Deutz, Looping und Korkenzieher an der Flora: Rheinpark, Messe, Mülheimer Hafen, zurück über die Mülheimer Brücke. Die Schraube an der Flora, unter der Seilbahn durch, Kräne im Hafen. Wer hier nicht schaltet, verliert alles.',
      theme: { sky: 0x5fa8ff, fog: 0xcfe6ff, ground: 0x5e9a4a, sun: 0xffffff, road: [0x585858, 0x4a4a4a], night: false, water: 0x3f7fc0, street: 'park',
        streets: ['RIEHLER STRASSE', 'ZOOBRÜCKE', 'DEUTZ-MÜLHEIMER STR.', 'MESSEPLATZ', 'AM RHEINPARK', 'AUENWEG', 'MÜLHEIMER FREIHEIT', 'AM BOTANISCHEN GARTEN'],
        far: [{ type: 'dom', angle: 230, dist: 140 }, { type: 'colonius', angle: 260, dist: 220 }, { type: 'triangle', angle: 210, dist: 80 }, { type: 'flatbridge', angle: 180, dist: 60 }] },
      // 0 str,1 L,2 str,3 loop,4 str,5 L,6 bridge,7 R,8 str,9 L,10 hill,11 L,12 str,13 R,14 str,15 L,16 str,17 L,18 str
      segments: [
        { t: 'straight', len: 150 },
        { t: 'curve', angle: 90, r: 50, bank: 15 },
        { t: 'straight', len: 50 },
        { t: 'loop', r: 14, shift: 14 },
        { t: 'corkscrew', len: 64, r: 9, turns: 1, dir: 1 },
        { t: 'curve', angle: 90, r: 40 },
        { t: 'bridge', len: 130 },
        { t: 'curve', angle: -90, r: 35 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: 90, r: 35 },
        { t: 'hill', len: 60, pitch: 16 },
        { t: 'curve', angle: 90, r: 45, bank: 15 },
        { t: 'straight', len: 50 },
        { t: 'bridge', len: 90 },
        { t: 'jump', ramp: 26, angle: 15, gap: 26 },
        { t: 'curve', angle: -90, r: 30 },
        { t: 'straight', len: 20 },
        { t: 'curve', angle: 90, r: 30 },
        { t: 'straight', len: 20 },
        { t: 'curve', angle: 90, r: 30 },
        { t: 'straight', len: 30 }
      ],
      props: [
        { type: 'tuenn', seg: 0, u: 0.02, side: -1, dist: 9 },
        { type: 'zootor', seg: 0, u: 0.22, side: 1, dist: 18, keep: 40 },
        { type: 'giraffe', seg: 0, u: 0.32, side: 1, dist: 30 },
        { type: 'elephant', seg: 0, u: 0.4, side: 1, dist: 26 },
        { type: 'elephant', seg: 0, u: 0.5, side: 1, dist: 34 },
        { type: 'elephant', seg: 0, u: 0.6, side: 1, dist: 24 },
        { type: 'row', seg: 0, u: 0.7, side: -1, dist: 26, style: 'gruenderzeit', seed: 5, n: 4 },
        { type: 'flora', seg: 2, u: 0.5, side: -1, dist: 40, keep: 50, story: 'Schäl Sick. De falsche Rheinseite, sagen de Kölner. Ich sag: hee kennt mich keiner. Dat is och wat wert.' },
        { type: 'crowd', seg: 5, u: 0.3, side: 1, dist: 12 },
        { type: 'rhine', seg: 6, u: 0.5, side: 0, dist: 0 },
        { type: 'seilbahn', seg: 6, u: 0.15, side: 0, dist: 0 },
        { type: 'zoobruecke', seg: 6, u: 0.5, side: -1, dist: 44, face: false, story: 'Zoobrück. Drüvver de Autos, drunger de Schiffe, drüvver drüvver de Seilbahn. Kölle stapelt.' },
        { type: 'rhine', seg: 13, u: 0.5, side: 0, dist: 0 },
        { type: 'suspension', seg: 13, u: 0.5, side: 1, dist: 60, face: false, story: 'Mülheimer Brück. Jrön wie de Hoffnung un jenau so oft jesperrt.' },
        { type: 'boat', seg: 13, u: 0.4, side: -1, dist: 50 },
        { type: 'arena', seg: 8, u: 0.5, side: 1, dist: 110, keep: 80 },
        { type: 'park', seg: 8, u: 0.3, side: 1, dist: 40, seed: 5, w: 40, d: 40, keep: 30 },
        { type: 'boat', seg: 6, u: 0.35, side: -1, dist: 50 },
        { type: 'barge', seg: 6, u: 0.7, side: 1, dist: 70 },
        { type: 'messeturm', seg: 8, u: 0.5, side: -1, dist: 60 },
        { type: 'hafenkran', seg: 12, u: 0.85, side: 1, dist: 40 },
        { type: 'speedboat', seg: 15, u: 0.5, side: 1, dist: 80, face: false },
        { type: 'moewen', seg: 6, u: 0.6, side: -1, dist: 40, face: false },
        { type: 'blitzer', seg: 0, u: 0.85, side: -1, dist: 8 },
        { type: 'bude', seg: 12, u: 0.2, side: -1, dist: 11, text: 'HAFEN-IMBISS · FLÖNZ' },
        { type: 'blitzer', seg: 12, u: 0.7, side: 1, dist: 8 },
        { type: 'hafenkran', seg: 15, u: 0.5, side: 1, dist: 48 },
        { type: 'barge', seg: 15, u: 0.5, side: 1, dist: 80 },
        { type: 'rhineSide', seg: 15, u: 0.5, side: 1, dist: 170, l: 300, w: 200 },
        { type: 'tanzbrunnen', seg: 7, u: 0.5, side: 1, dist: 50, keep: 40 },
        { type: 'kirche', seg: 12, u: 0.2, side: -1, dist: 50, h: 32 },
        { type: 'koelsch', seg: 12, u: 0.3, side: 1, dist: 20 },
        { type: 'billboard', seg: 12, u: 0.7, side: -1, dist: 14, text: 'MÜLHEIM – HEE FÄNGT DER OSTEN AN' },
        { type: 'row', seg: 12, u: 0.6, side: 1, dist: 26, style: 'concrete', seed: 7, n: 5 },
        { type: 'buedchen', seg: 18, u: 0.5, side: -1, dist: 11 },
        { type: 'crowd', seg: 20, u: 0.5, side: 1, dist: 10 }
      ]
    },
    {
      id: 'ehrenfeld', name: 'Ehrenfeld Tape Run', district: 'Venloer Straße zur blauen Stunde', tag: 'ABEND', order: 4,
      waypoints: ['Venloer Straße', 'Moschee', 'Odonien', 'Bahnbögen', 'Helios-Turm', 'Vulkan'],
      diff: 2, laps: 3, scale: 1.45,
      desc: 'Zwischen Bahnbögen, Kiosk und Kassettenladen. Enge Haken durch die Venloer Straße, Odonien, Colonius. Rau, schnell, ehrlich.',
      theme: { sky: 0x1c2a5a, fog: 0xd88a68, ground: 0x4a4a52, sun: 0xffb080, road: [0x3e3e46, 0x35353c], night: true, dusk: true, water: 0x243a60, street: 'gruenderzeit', catenary: true,
        streets: ['VENLOER STRASSE', 'LICHTSTRASSE', 'HORNSTRASSE', 'NEPTUNPLATZ', 'KÖRNERSTRASSE', 'SUBBELRATHER STR.', 'VOGELSANGER STR.', 'EHRENFELDGÜRTEL', 'HELIOSSTRASSE', 'LEYENDECKERSTR.'],
        shops: ['DÖNER', 'CAFÉ HAFERMILCH', 'PLATTENLADEN', 'BARBIER', 'LASTENRAD-VERLEIH', 'KIOSK', 'FALAFEL', 'TATTOO', 'BÜDCHE', 'BÄCKEREI MERZENICH', 'REWE'],
        far: [{ type: 'dom', angle: 30, dist: 200 }, { type: 'triangle', angle: 15, dist: 300 }] },
      // 0 str,1 R,2 str,3 L,4 str,5 L,6 str,7 R,8 hill,9 R,10 str,11 R,12 str,13 L,14 str,15 R,16 tunnel,17 R,18 str,19 R,20 str
      segments: [
        { t: 'straight', len: 90 },
        { t: 'curve', angle: -90, r: 28, bank: 8 },
        { t: 'straight', len: 16 },
        { t: 'curve', angle: 90, r: 28, bank: 8 },
        { t: 'straight', len: 16 },
        { t: 'curve', angle: 90, r: 28, bank: 8 },
        { t: 'straight', len: 16 },
        { t: 'curve', angle: -90, r: 28, bank: 8 },
        { t: 'hill', len: 50, pitch: 12 },
        { t: 'curve', angle: -90, r: 30, bank: 8 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: -90, r: 30, bank: 8 },
        { t: 'straight', len: 60 },
        { t: 'loop', r: 13, shift: 14 },
        { t: 'curve', angle: 90, r: 28, bank: 6 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: -90, r: 28, bank: 6 },
        { t: 'tunnel', len: 60 },
        { t: 'curve', angle: -90, r: 35, bank: 10 },
        { t: 'jump', ramp: 26, angle: 16, gap: 30, over: 'house' },
        { t: 'straight', len: 90 },
        { t: 'curve', angle: -90, r: 35, bank: 10 },
        { t: 'straight', len: 14 }
      ],
      props: [
        { type: 'tuenn', seg: 0, u: 0.02, side: 1, dist: 9 },
        { type: 'colonius', seg: 0, u: 0.5, side: -1, dist: 90, keep: 40 },
        { type: 'billboard', seg: 0, u: 0.25, side: 1, dist: 14, text: 'VENLOER STR. – HAFERMILCH TO GO' },
        { type: 'haltestelle', seg: 0, u: 0.6, side: 1, dist: 10 },
        { type: 'tram', seg: 0, u: 0.8, side: 1, dist: 12 },
        { type: 'graffiti', seg: 2, u: 0.5, side: 1, dist: 12, text: 'EHRENFELD' },
        { type: 'lastenrad', seg: 4, u: 0.5, side: 1, dist: 10 },
        { type: 'buedchen', seg: 6, u: 0.5, side: -1, dist: 11 },
        { type: 'viaduct', seg: 12, u: 0.5, side: 1, dist: 26, keep: 90 },
        { type: 'moschee', seg: 8, u: 0.5, side: 1, dist: 60, keep: 60, story: 'Ehrenfeld. Hee hät jeder Straße ihre eijene Sprache un jeder Kiosk sing eijene Reejele. Ming Reejel: Kölsch jeht immer.' },
        { type: 'odonien', seg: 10, u: 0.5, side: 1, dist: 30, keep: 40 },
        { type: 'bude', seg: 0, u: 0.4, side: -1, dist: 11, text: 'DÖNER · HAFERMILCH' },
        { type: 'blitzer', seg: 0, u: 0.7, side: 1, dist: 8 },
        { type: 'blitzer', seg: 20, u: 0.5, side: -1, dist: 8 },
        { type: 'polizei', seg: 12, u: 0.2, side: 1, dist: 10 },
        { type: 'neon', seg: 4, u: 0.5, side: -1, dist: 13, text: 'KASSETTENLADEN', color: '#ff2d95', light: false },
        { type: 'haltestelle', seg: 12, u: 0.62, side: -1, dist: 10 },
        { type: 'neon', seg: 15, u: 0.5, side: 1, dist: 13, text: 'NEPTUNBAD', color: '#00e5ff', small: true },
        { type: 'kirche', seg: 9, u: 0.5, side: -1, dist: 46, h: 36, color: 0x9a4a34, story: 'St. Joseph. Rote Backstein wie de Fabrike drumerum. Hee jeht mer sonntags rein, wenn mer samstags im Underground wor.' },
        { type: 'vulkanhalle', seg: 17, u: 0.5, side: -1, dist: 45, keep: 60 },
        { type: 'tramline', seg: 0, u: 0.5, side: -1, dist: 14, len: 120, face: false },
        { type: 'cafe', seg: 2, u: 0.5, side: -1, dist: 13 },
        { type: 'graffiti', seg: 10, u: 0.5, side: -1, dist: 12, text: 'CHICAGO AM RHEIN', color: '#00e5ff' },
        { type: 'row', seg: 12, u: 0.5, side: -1, dist: 24, style: 'industrial', seed: 21, n: 5 },
        { type: 'koelsch', seg: 15, u: 0.5, side: 1, dist: 18 },
        { type: 'lastenrad', seg: 15, u: 0.2, side: -1, dist: 10 },
        { type: 'helios', seg: 18, u: 0.5, side: 1, dist: 34 },
        { type: 'billboard', seg: 20, u: 0.3, side: 1, dist: 14, text: 'HELIOS-TURM – NUR ECHT MIT LEUCHTTURM' },
        { type: 'graffiti', seg: 20, u: 0.7, side: -1, dist: 12, text: 'DÄ LANGE WOR HEE', color: '#7fff00' },
        { type: 'buedchen', seg: 20, u: 0.9, side: 1, dist: 11 },
        { type: 'crowd', seg: 22, u: 0.5, side: 1, dist: 10 }
      ]
    },
    {
      id: 'kalk', name: 'Chicago am Rhein', district: 'Ringe Nachtfahrt', tag: 'NACHT', order: 1,
      waypoints: ['Residenz-Kino', 'Rudolfplatz', 'Friesenstraße', 'Klein Köln', 'Sartory', 'Hansaring', 'Ebertplatz', 'Mediapark'],
      diff: 5, laps: 3, scale: 1.45,
      desc: 'Die Nachttour vum Türsteher als Rennen, mit Korkenzieher an St. Gereon und Sprung über die Büdchen: vom Residenz-Kino über die Friesenstraße am Klein Köln vorbei, Sartory, Lovers Club, Hansaring. Nacht, Neon, nasse Straßen, Zocker, Türsteher, Kripo. 1968. Nix für Sonntagsfahrer.',
      theme: { sky: 0x070a24, fog: 0x2a1a4a, ground: 0x23232e, sun: 0x9fb4ff, road: [0x2c2e3a, 0x25272f], night: true, wet: true, water: 0x102040, street: 'gruenderzeit', catenary: true,
        streets: ['HOHENZOLLERNRING', 'FRIESENSTRASSE', 'CHRISTOPHSTRASSE', 'FRIESENPLATZ', 'HANSARING', 'KAISER-WILHELM-RING', 'EBERTPLATZ', 'RUDOLFPLATZ', 'GEREONSTRASSE', 'MEDIAPARK'],
        shops: ['BOXKELLER', 'TANZ LOKAL', 'KIOSK', 'BRAUHAUS', 'NACHTCAFÉ', 'CASINO', 'IMBISS', 'BAR ZUM LANGEN', 'BILLARD', 'SPÄTI', 'DISCO', 'KÖLSCH', 'FLAMINGO BAR', 'VICE LOUNGE', 'KLÜNGEL & CO', 'SPARKASSE KÖLNBONN', 'KVB'],
        posters: ['BOXKELLER', 'DÄ LANGE LIVE', 'KÖLSCH-NACHT', 'VICE KÖLLE', 'FC HEIMSPIEL'],
        far: [{ type: 'dom', angle: 20, dist: 160 }, { type: 'colonius', angle: 200, dist: 120 }, { type: 'triangle', angle: 40, dist: 200 }] },
      // 0 str,1 L,2 str,3 loop,4 str,5 L,6 str,7 jump,8 str,9 R,10 str,11 L,12 loop,13 str,14 L,15 tunnel,16 L,17 str,18 R,19 str,20 L,21 str
      segments: [
        { t: 'straight', len: 130 },
        { t: 'curve', angle: 90, r: 40, bank: 12 },
        { t: 'straight', len: 30 },
        { t: 'loop', r: 13, shift: 14 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 40, bank: 12 },
        { t: 'straight', len: 30 },
        { t: 'jump', ramp: 28, angle: 15, gap: 30, over: 'buedchen' },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: -90, r: 30 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: 90, r: 30 },
        { t: 'loop', r: 13, shift: 14 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: 90, r: 45, bank: 15 },
        { t: 'tunnel', len: 80 },
        { t: 'curve', angle: 90, r: 45, bank: 15 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: -90, r: 30 },
        { t: 'corkscrew', len: 64, r: 9, turns: 1 },
        { t: 'curve', angle: 90, r: 30 },
        { t: 'straight', len: 35 }
      ],
      props: [
        { type: 'tuenn', seg: 0, u: 0.02, side: 1, dist: 9 },
        { type: 'residenz', seg: 0, u: 0.12, side: -1, dist: 24, keep: 40, story: 'Hee fängt ming Tour an: Residenz-Kino, Christophstraße. 1961 stond ich zum erste Mol an ner Tür. Un ich stonn immer noch.' },
        { type: 'neon', seg: 0, u: 0.1, side: 1, dist: 14, text: 'CHICAGO AM RHEIN', color: '#ff2d95' },
        { type: 'expresskiosk', seg: 0, u: 0.22, side: 1, dist: 11, text: 'DÄ SCHNELLE: KÖLN – CHICAGO AM RHEIN!' },
        { type: 'kleinkoeln', seg: 4, u: 0.2, side: -1, dist: 24, keep: 40, story: 'Links: Klein Köln, Friesenstraße. Seit 1926 Nachtlizenz. Hee han sich de Boxer jewoge. Un ich mich och, nach dem dritten Kölsch.' },
        { type: 'boxring', seg: 6, u: 0.5, side: -1, dist: 16, keep: 20 },
        { type: 'platz', seg: 4, u: 0.8, side: -1, dist: 21, seed: 7, keep: 16 },
        { type: 'zockertisch', seg: 10, u: 0.5, side: 1, dist: 11, story: 'De Zocker. Die spille um ding Auto. Un um ming Nacht. Wer verliert, jeht zo Fuß nach Hus.' },
        { type: 'hansahochhaus', seg: 8, u: 0.2, side: -1, dist: 55, keep: 60, story: 'Dat Hansahochhaus. 1925 dat höchste Haus in Europa. Heut nur noch dat höchste am Ring. Wie ich.' },
        { type: 'spielclub', seg: 10, u: 0.2, side: -1, dist: 24, keep: 40, story: 'Spiel-Club. Hee hab ich ming Vermögen jemaat. Un hee hab ich et och wieder verzockt. Alles op Rot. Wie de Ampel.' },
        { type: 'neon', seg: 0, u: 0.8, side: -1, dist: 14, text: 'ZUM LANGEN – KÖLSCH & KREDIT', color: '#ffd400' },
        { type: 'gangster', seg: 0, u: 0.85, side: -1, dist: 9 },
        { type: 'gangster', seg: 0, u: 0.87, side: -1, dist: 11 },
        { type: 'kripo', seg: 0, u: 0.6, side: 1, dist: 10, story: 'Kripo Köln. 50.000 Straftaten im Johr, e Drittel jeklärt. Der Rest fährt heut met dir im Rennen.' },
        { type: 'blitzer', seg: 0, u: 0.9, side: 1, dist: 8 },
        { type: 'bude', seg: 0, u: 0.5, side: 1, dist: 11, text: 'NACHTIMBISS · HALVE HAHN' },
        { type: 'zeppelin', seg: 0, u: 0.5, side: 1, dist: 60, face: false },
        { type: 'rain', seg: 0, u: 0.5, side: 0, dist: 0, face: false },
        { type: 'fireworks', seg: 5, u: 0.5, side: 1, dist: 100, face: false },
        { type: 'palm', seg: 0, u: 0.3, side: -1, dist: 9, h: 8 },
        { type: 'palm', seg: 0, u: 0.36, side: -1, dist: 9, h: 7 },
        { type: 'hahnentor', seg: 2, u: 0.5, side: 1, dist: 26, keep: 40, story: 'Hahnentor, Rudolfplatz. Da kome früher de Könige durch. Heut de Jecke. Un du, wenn de nit bremst.' },
        { type: 'sartory', seg: 4, u: 0.5, side: 1, dist: 30, keep: 50, story: 'Sartory-Säle. Boxnächte, Prunksitzunge, Schlägereien. Manchmal alles an einem Abend.' },
        { type: 'neon', seg: 4, u: 0.5, side: -1, dist: 13, text: 'KIOSK', color: '#00e5ff', light: false },
        { type: 'koelnturm', seg: 17, u: 0.5, side: -1, dist: 90, keep: 60 },
        { type: 'kirche', seg: 19, u: 0.5, side: -1, dist: 60, h: 44, color: 0xc4ad8c, story: 'St. Gereon. Zwölf romanische Kirche hät Kölle, die hee is die met dem Zehneck. Ich hann mol ne Zocker drin jefunge. Beim Bete. För Rot.' },
        { type: 'rails', seg: 7, u: 0.55, side: 0, dist: 0 },
        { type: 'loversclub', seg: 8, u: 0.5, side: 1, dist: 24, keep: 40, story: 'Lovers Club. Ming erste Tür, 1961. Reejel Nummer eins: Wer hee nit reinkütt, kütt nirjendwo rein. Du kütts rein. Ausnahmsweise.' },
        { type: 'tram', seg: 8, u: 0.5, side: -1, dist: 14 },
        { type: 'neon', seg: 8, u: 0.8, side: -1, dist: 14, text: 'KLÜNGEL & SÖHNE – BAU · RAT · ZOCH', color: '#00e5ff' },
        { type: 'neon', seg: 10, u: 0.5, side: 1, dist: 13, text: 'CASINO', color: '#ffd400' },
        { type: 'blitzer', seg: 10, u: 0.8, side: -1, dist: 8 },
        { type: 'kripo', seg: 11, u: 0.5, side: 1, dist: 10 },
        { type: 'neon', seg: 13, u: 0.3, side: -1, dist: 13, text: 'VICE · KÖLLE', color: '#00e5ff', small: true },
        { type: 'neon', seg: 13, u: 0.7, side: 1, dist: 13, text: 'FLAMINGO BAR', color: '#ff2d95', small: true },
        { type: 'koelsch', seg: 13, u: 0.5, side: 1, dist: 20 },
        { type: 'eigelsteintor', seg: 14, u: 0.5, side: -1, dist: 28, keep: 40, story: 'Eigelsteintor. Hee hört de Ring op un de Eigelstein fängt an. Da wor et noch e bessje ehrlicher. Also weniger.' },
        { type: 'expresskiosk', seg: 17, u: 0.2, side: -1, dist: 11, text: 'DÄ SCHNELLE: DOMSCHATZ JEKLAUT – WER WOR ET?' },
        { type: 'neon', seg: 17, u: 0.3, side: 1, dist: 14, text: 'MAN KENNT SICH · MAN HILFT SICH', color: '#ff2d95' },
        { type: 'neon', seg: 17, u: 0.7, side: -1, dist: 13, text: 'DISCO', color: '#c04dff', light: false },
        { type: 'buedchen', seg: 17, u: 0.85, side: 1, dist: 11 },
        { type: 'tramline', seg: 17, u: 0.5, side: 1, dist: 14, len: 100, face: false },
        { type: 'gangster', seg: 21, u: 0.6, side: 1, dist: 9 },
        { type: 'blitzer', seg: 21, u: 0.9, side: -1, dist: 8 },
        { type: 'bude', seg: 21, u: 0.2, side: 1, dist: 11, text: 'CURRYWURST BEI JUPP' },
        { type: 'neon', seg: 21, u: 0.4, side: -1, dist: 14, text: 'ET HÄTT NOCH IMMER JOT JEJANGE', color: '#7fff00', light: false },
        { type: 'crowd', seg: 21, u: 0.8, side: -1, dist: 10 }
      ]
    },
    {
      id: 'zoch', name: 'Karneval Krawall', district: 'Altstadt Rallye', tag: 'TAG', order: 5,
      waypoints: ['Chlodwigplatz', 'Severinstor', 'Heumarkt', 'Alter Markt', 'Rathaus', 'Rudolfplatz'],
      diff: 3, laps: 3, scale: 1.45,
      desc: 'Der Zochweg als Rennstrecke: Heumarkt, Alter Markt, Rathaus, durchs Severinstor. Hügel, Sprung, Konfetti, Kamelle. Alaaf! Die Bahn ist gesperrt, die Jecken nicht.',
      theme: { sky: 0x8fc0ff, fog: 0xffe6f5, ground: 0xb5ada0, sun: 0xfff0ff, road: [0x5a5a5a, 0x4c4c4c], night: false, water: 0x3f7fc0, confetti: true, street: 'gruenderzeit', catenary: true,
        streets: ['SEVERINSTRASSE', 'CHLODWIGPLATZ', 'HOHE PFORTE', 'WAIDMARKT', 'ALTER MARKT', 'HEUMARKT', 'NEUMARKT', 'SCHILDERGASSE', 'HOHE STRASSE', 'RUDOLFPLATZ', 'ZOCHWEG'],
        shops: ['KAMELLE', 'KOSTÜME', 'STRÜSSJER', 'KÖLSCH', 'BÜTZJE-BAR', 'FUNKENMARIECHEN', 'ALAAF-SHOP', 'BRAUHAUS'],
        far: [{ type: 'dom', angle: 80, dist: 160 }, { type: 'colonius', angle: 150, dist: 260 }] },
      // 0 str,1 hill,2 L,3 str,4 jump,5 str,6 L,7 hill,8 R,9 str,10 L,11 hill,12 L,13 str,14 R,15 dip,16 L,17 str,18 L,19 str
      segments: [
        { t: 'straight', len: 100 },
        { t: 'hill', len: 50, pitch: 14 },
        { t: 'curve', angle: 90, r: 40, bank: 10 },
        { t: 'straight', len: 30 },
        { t: 'jump', ramp: 26, angle: 16, gap: 30, over: 'house' },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 40, bank: 10 },
        { t: 'hill', len: 50, pitch: 14 },
        { t: 'curve', angle: -90, r: 30 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 30 },
        { t: 'hill', len: 40, pitch: 12 },
        { t: 'curve', angle: 90, r: 30 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: -90, r: 30 },
        { t: 'dip', len: 40, pitch: 12 },
        { t: 'curve', angle: 90, r: 40, bank: 10 },
        { t: 'straight', len: 80 },
        { t: 'loop', r: 13, shift: 14 },
        { t: 'curve', angle: 90, r: 40, bank: 10 },
        { t: 'straight', len: 40 }
      ],
      props: [
        { type: 'tuenn', seg: 0, u: 0.02, side: 1, dist: 9 },
        { type: 'crowd', seg: 0, u: 0.15, side: -1, dist: 10 },
        { type: 'tribuene', seg: 0, u: 0.3, side: 1, dist: 12, keep: 30 },
        { type: 'zochwagen', seg: 0, u: 0.5, side: -1, dist: 13 },
        { type: 'tribuene', seg: 9, u: 0.3, side: -1, dist: 12, keep: 30 },
        { type: 'zochwagen', seg: 13, u: 0.6, side: 1, dist: 13 },
        { type: 'tribuene', seg: 17, u: 0.5, side: -1, dist: 12, keep: 30 },
        { type: 'kirche', seg: 8, u: 0.5, side: 1, dist: 45, h: 40 },
        { type: 'bunting', seg: 0, u: 0.4, side: 0, dist: 0 },
        { type: 'billboard', seg: 0, u: 0.6, side: -1, dist: 14, text: 'KÖLLE ALAAF – KAMELLE!' },
        { type: 'haltestelle', seg: 0, u: 0.8, side: 1, dist: 10 },
        { type: 'severinstor', seg: 3, u: 0.5, side: 0, dist: 0, face: false, story: 'Severinstor. Hee kütt der Zoch durch. Un an Rosenmontag bin ich ausnahmsweise nüchtern. Nä, Spaß.' },
        { type: 'bude', seg: 0, u: 0.7, side: 1, dist: 11, text: 'KAMELLE & KÖLSCH' },
        { type: 'blitzer', seg: 0, u: 0.9, side: -1, dist: 8 },
        { type: 'zeppelin', seg: 5, u: 0.5, side: 1, dist: 60, face: false },
        { type: 'polizei', seg: 9, u: 0.2, side: -1, dist: 10 },
        { type: 'blitzer', seg: 17, u: 0.5, side: 1, dist: 8 },
        { type: 'crowd', seg: 5, u: 0.4, side: 1, dist: 10 },
        { type: 'crowd', seg: 5, u: 0.7, side: -1, dist: 10 },
        { type: 'bunting', seg: 5, u: 0.55, side: 0, dist: 0 },
        { type: 'altstadt', seg: 9, u: 0.5, side: 1, dist: 24, seed: 11, n: 6 },
        { type: 'reiter', seg: 5, u: 0.55, side: 1, dist: 18 },
        { type: 'rathaus', seg: 9, u: 0.5, side: -1, dist: 46, keep: 70, story: 'Rathaus. An Wieverfastelovend stürme de Wiever dat Ding. Ich hann einmol versucht, se draußen zo halde. Einmol.' },
        { type: 'stmartin', seg: 9, u: 0.85, side: 1, dist: 52, keep: 60 },
        { type: 'koelsch', seg: 9, u: 0.5, side: -1, dist: 18 },
        { type: 'bunting', seg: 9, u: 0.5, side: 0, dist: 0 },
        { type: 'billboard', seg: 13, u: 0.5, side: 1, dist: 14, text: 'D’R ZOCH KÜTT!' },
        { type: 'crowd', seg: 13, u: 0.3, side: -1, dist: 10 },
        { type: 'crowd', seg: 13, u: 0.7, side: 1, dist: 10 },
        { type: 'bunting', seg: 13, u: 0.5, side: 0, dist: 0 },
        { type: 'hahnentor', seg: 17, u: 0.5, side: 1, dist: 30 },
        { type: 'billboard', seg: 17, u: 0.3, side: -1, dist: 14, text: 'RING KÖLSCH – DRINK DOCH ENE MET' },
        { type: 'bunting', seg: 17, u: 0.7, side: 0, dist: 0 },
        { type: 'crowd', seg: 17, u: 0.8, side: 1, dist: 10 },
        { type: 'crowd', seg: 20, u: 0.5, side: -1, dist: 10 },
        { type: 'bunting', seg: 20, u: 0.4, side: 0, dist: 0 }
      ]
    },
    {
      id: 'poller', name: 'Poller Wiesen Stunt-Park', district: 'Nachts op de Poller Wiesen', tag: 'NACHT', order: 7,
      waypoints: ['Poller Wiesen', 'Lanxess Arena', 'Deutzer Werft', 'Südbrücke', 'Rheinpark'],
      diff: 5, laps: 3, scale: 1.45,
      desc: 'Drei Loopings, ein Korkenzieher, zwei Sprünge (einer übers Brauhaus), ein Tunnel unter der Deutzer Brücke und Steilkurven wie im Boxring. Die Poller Wiesen als Stunt-Arena: Tribünen, Kölsch-Stände, Riesenrad, Rhing. Wer hier bremst, hat verloren.',
      theme: { sky: 0x070a24, fog: 0x1e1a3a, ground: 0x28402a, sun: 0x9fb4ff, road: [0x2c2e3a, 0x25272f], night: true, water: 0x102040, street: 'park', arena: true,
        streets: ['POLLER WIESEN', 'ROLSHOVER STR.', 'POLLER KIRCHWEG', 'ALFRED-SCHÜTTE-ALLEE', 'DEUTZER WERFT', 'AM RHEINPARK', 'ARENASTRASSE'],
        posters: ['STUNT-NACHT', 'LOOPING-CUP', 'KÖLSCH-FEST', 'LAMBOGINA', 'FC HEIMSPIEL'],
        far: [{ type: 'dom', angle: 200, dist: 150 }, { type: 'stmartin', angle: 215, dist: 120 }, { type: 'colonius', angle: 240, dist: 260 }, { type: 'archbridge', angle: 180, dist: 60 }, { type: 'kranhaus', angle: 160, dist: 100 }, { type: 'triangle', angle: 190, dist: 90 }] },
      // 0 str,1 L,2 str,3 loop,4 str,5 jump,6 str,7 L,8 hill,9 R,10 str,11 loop,12 str,13 L,14 tunnel,15 L,16 str,17 jump,18 str,19 L,20 str,21 loop,22 str,23 L,24 str
      segments: [
        { t: 'straight', len: 100 },
        { t: 'curve', angle: 90, r: 45, bank: 15 },
        { t: 'straight', len: 40 },
        { t: 'loop', r: 14, shift: 14 },
        { t: 'straight', len: 60 },
        { t: 'jump', ramp: 28, angle: 15, gap: 28 },
        { t: 'straight', len: 50 },
        { t: 'curve', angle: 90, r: 40, bank: 15 },
        { t: 'hill', len: 60, pitch: 16 },
        { t: 'curve', angle: -90, r: 40 },
        { t: 'straight', len: 30 },
        { t: 'loop', r: 13, shift: 14 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 40, bank: 15 },
        { t: 'tunnel', len: 70 },
        { t: 'curve', angle: 90, r: 40, bank: 15 },
        { t: 'straight', len: 60 },
        { t: 'jump', ramp: 30, angle: 16, gap: 32, over: 'brauhaus' },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 45, bank: 15 },
        { t: 'straight', len: 30 },
        { t: 'corkscrew', len: 64, r: 9, turns: 1, dir: -1 },
        { t: 'loop', r: 14, shift: 14 },
        { t: 'straight', len: 70 },
        { t: 'straight', len: 70 }
      ],
      props: [
        { type: 'tuenn', seg: 0, u: 0.02, side: 1, dist: 9 },
        { type: 'tribuene', seg: 0, u: 0.3, side: -1, dist: 14, story: 'Poller Wiesen. Hee hann se fröher Fußball jespillt, jetz flieje hee Autos. Beides ohne Regeln.' },
        { type: 'crowd', seg: 0, u: 0.5, side: 1, dist: 10 },
        { type: 'koelsch', seg: 0, u: 0.7, side: -1, dist: 18 },
        { type: 'billboard', seg: 0, u: 0.85, side: 1, dist: 14, text: 'STUNT-PARK POLLER WIESEN – ET JEHT OP UN AV' },
        { type: 'arena', seg: 1, u: 0.5, side: -1, dist: 95, keep: 80, story: 'Die Arena. 18.000 Lück un alle wolle an mir vorbei. Hee kütt keiner rein ohne Kaat. Ich hann se alle jezählt.' },
        { type: 'crowd', seg: 2, u: 0.5, side: -1, dist: 10 },
        { type: 'tribuene', seg: 4, u: 0.3, side: 1, dist: 14, story: 'Looping. Einmol rund wie ne Zocker-Abend: oben bes de König, unten fällt et Kölsch us der Täsch.' },
        { type: 'marktstand', seg: 4, u: 0.8, side: -1, dist: 12 },
        { type: 'moewen', seg: 5, u: 0.5, side: 1, dist: 20 },
        { type: 'bude', seg: 6, u: 0.4, side: 1, dist: 11, text: 'KÖLSCH & KAMELLE' },
        { type: 'riesenrad', seg: 6, u: 0.7, side: -1, dist: 40, keep: 40, story: 'Riesenrad. Do sitz der Schäl drin un wartet, dat de Wagen rund kütt. Wie im Looping, nur langsamer.' },
        { type: 'zeppelin', seg: 8, u: 0.5, side: -1, dist: 40 },
        { type: 'flag', seg: 8, u: 0.2, side: 1, dist: 9 },
        { type: 'polizei', seg: 10, u: 0.5, side: 1, dist: 10 },
        { type: 'crowd', seg: 12, u: 0.3, side: -1, dist: 10 },
        { type: 'blitzer', seg: 12, u: 0.8, side: 1, dist: 8 },
        { type: 'rhineSide', seg: 16, u: 0.5, side: 1, dist: 110, w: 200, l: 700 },
        { type: 'promenade', seg: 16, u: 0.5, side: 1, dist: 30 },
        { type: 'boat', seg: 16, u: 0.4, side: 1, dist: 130 },
        { type: 'barge', seg: 16, u: 0.7, side: 1, dist: 110 },
        { type: 'litfass', seg: 16, u: 0.2, side: -1, dist: 10 },
        { type: 'archbridge', seg: 16, u: 0.5, side: 1, dist: 230, face: false, story: 'Südbrück. Nur för de Zöch. Ich wollt mol drüvver, zo Fuß, nachts. Der Lokführer hät jewunke. Nit freundlich.' },
        { type: 'fireworks', seg: 16, u: 0.5, side: 1, dist: 130, face: false },
        { type: 'neon', seg: 0, u: 0.6, side: -1, dist: 14, text: 'STUNT-PARK · NACHTSCHICHT', color: '#ff2d95' },
        { type: 'haltestelle', seg: 18, u: 0.5, side: -1, dist: 10 },
        { type: 'bude', seg: 20, u: 0.5, side: 1, dist: 11, text: 'RIEVKOOCHE · APFELMUS · KÖLSCH' },
        { type: 'tanzbrunnen', seg: 23, u: 0.5, side: -1, dist: 34, story: 'Tanzbrunnen. 1957 hann se hee jetanzt, ich hann an der Tür jestanden. Manche stonn immer noch dovör.' },
        { type: 'koelsch', seg: 23, u: 0.8, side: 1, dist: 18 },
        { type: 'crowd', seg: 23, u: 0.3, side: 1, dist: 12 },
        { type: 'billboard', seg: 24, u: 0.5, side: -1, dist: 14, text: 'WER BREMST, ZAHLT DE KÖLSCH' },
        { type: 'tribuene', seg: 24, u: 0.8, side: 1, dist: 14 }
      ]
    }
    ,{
      id: 'heist', name: 'Domschatz-Raub 1975', district: 'Fluchtfahrt durch Chicago am Rhein', tag: 'NACHT', order: 8,
      waypoints: ['Domschatzkammer', 'Hauptbahnhof', 'Eigelstein', 'Ebertplatz', 'Zoobrücke', 'Rheinpark', 'Hohenzollernbrücke'],
      diff: 4, laps: 3, scale: 1.4,
      desc: 'Der Domschatz liegt im Kofferraum, die Kripo klebt ab der ersten Sekunde im Rückspiegel. Über die Gleise am Hauptbahnhof, Looping am Ebertplatz, rüber über die Zoobrücke, Korkenzieher im Rheinpark und über die Hohenzollernbrücke zurück zum Dom. 1975. Nix für Ehrliche.',
      theme: { sky: 0x05071c, fog: 0x1e1638, ground: 0x23232e, sun: 0x9fb4ff, road: [0x2c2e3a, 0x25272f], night: true, wet: true, water: 0x0e1e3e, street: 'gruenderzeit', catenary: true, heist: true,
        streets: ['TRANKGASSE', 'BRESLAUER PLATZ', 'EIGELSTEIN', 'EBERTPLATZ', 'THEODOR-HEUSS-RING', 'ZOOBRÜCKE', 'AM RHEINPARK', 'MESSEPLATZ', 'HEINRICH-BÖLL-PLATZ'],
        shops: ['JUWELIER', 'PFANDLEIHE', 'AN- UND VERKAUF', 'NACHTCAFÉ', 'SPÄTI', 'BILLARD', 'HEHLER & SÖHNE', 'KÖLSCH', 'TRESORBAU', 'DOM-SOUVENIRS'],
        far: [{ type: 'colonius', angle: 220, dist: 220 }, { type: 'stmartin', angle: 150, dist: 100 }, { type: 'flatbridge', angle: 60, dist: 80 }],
        intro: ['1975, Jung. Domschatzkammer, drei Mann, ne Leiter un e Auto. Du bes et Auto.', 'Der Domschatz im Kofferraum, de Kripo im Nacken. Wer hee anhält, hät verlore. Wer nit anhält, och. Ävver später.', 'Chicago am Rhein, die Nacht vum Domschatz. Ich hann an der Tür jestande un nix jesinn. Ehrlich.'] },
      // 0 str,1 jump (Hbf tracks),2 str,3 R,4 str (Eigelstein),5 loop (Ebertplatz),6 str,7 R,8 str,9 L,10 bridge (Zoobrücke),11 R,12 cork (Rheinpark),13 str,14 R,15 str,16 bridge (Hohenzollern),17 R,18 str
      segments: [
        { t: 'straight', len: 120 },
        { t: 'jump', ramp: 26, angle: 15, gap: 28 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: -90, r: 40, bank: 10 },
        { t: 'straight', len: 70 },
        { t: 'loop', r: 13, shift: 14 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: -90, r: 45, bank: 12 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 40 },
        { t: 'bridge', len: 140 },
        { t: 'curve', angle: -90, r: 40, bank: 10 },
        { t: 'corkscrew', len: 64, r: 9, turns: 1 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: -90, r: 40 },
        { t: 'straight', len: 30 },
        { t: 'bridge', len: 150 },
        { t: 'curve', angle: -90, r: 35 },
        { t: 'straight', len: 40 }
      ],
      props: [
        { type: 'tuenn', seg: 0, u: 0.02, side: 1, dist: 9 },
        { type: 'dom', seg: 0, u: 0.1, side: -1, dist: 80, keep: 120, story: 'Domschatzkammer. 1975 sin se durch et Fenster rin un met dem Schatz rus. Ich hann de Leiter jehalde. Also fast.' },
        { type: 'kripo', seg: 0, u: 0.25, side: 1, dist: 10, story: 'Kripo Köln. Die han schon jewartet. Die wisse alles. Nur nit, wo de hinfährs.' },
        { type: 'polizei', seg: 0, u: 0.45, side: -1, dist: 10 },
        { type: 'expresskiosk', seg: 0, u: 0.6, side: 1, dist: 11, text: 'DÄ SCHNELLE: DOMSCHATZ JEKLAUT – 1975' },
        { type: 'hbf', seg: 0, u: 0.85, side: 1, dist: 70, keep: 90, story: 'Hauptbahnhof. Über de Gleise, unter dem Bahnhof durch. Der Schaffner pfeift. Nit för dich.' },
        { type: 'rails', seg: 1, u: 0.55, side: 0, dist: 0 },
        { type: 'neon', seg: 2, u: 0.5, side: -1, dist: 14, text: 'PFANDLEIHE · OFFEN', color: '#ffd400' },
        { type: 'blitzer', seg: 2, u: 0.8, side: 1, dist: 8 },
        { type: 'eigelsteintor', seg: 4, u: 0.5, side: 1, dist: 28, keep: 40, story: 'Eigelsteintor. Hee wor et immer e bessje krummer. Perfekt för ne Fluchtweg.' },
        { type: 'gangster', seg: 4, u: 0.3, side: -1, dist: 9 },
        { type: 'gangster', seg: 4, u: 0.34, side: -1, dist: 11 },
        { type: 'zockertisch', seg: 4, u: 0.75, side: -1, dist: 11, story: 'De Zocker vum Eigelstein. Die han op dich jewettet. Op de Kripo och. Die jewinne immer.' },
        { type: 'neon', seg: 6, u: 0.5, side: 1, dist: 14, text: 'HEHLER & SÖHNE', color: '#ff2d95' },
        { type: 'kripo', seg: 8, u: 0.5, side: -1, dist: 10 },
        { type: 'rhine', seg: 10, u: 0.5, side: 0, dist: 0 },
        { type: 'zoobruecke', seg: 10, u: 0.5, side: -1, dist: 44, face: false, story: 'Zoobrück. Unger dir der Rhing, üvver dir de Seilbahn, hinger dir de Kripo. Vor dir: nix. Jas.' },
        { type: 'seilbahn', seg: 10, u: 0.2, side: 0, dist: 0 },
        { type: 'barge', seg: 10, u: 0.6, side: 1, dist: 70 },
        { type: 'boat', seg: 10, u: 0.35, side: -1, dist: 60 },
        { type: 'tanzbrunnen', seg: 11, u: 0.5, side: 1, dist: 50, keep: 40 },
        { type: 'park', seg: 13, u: 0.5, side: 1, dist: 40, seed: 9, w: 40, d: 40, keep: 30, story: 'Rheinpark. Hee han se der Schatz verjrave wolle. Han se nit. Zo viele Hunde.' },
        { type: 'messeturm', seg: 14, u: 0.5, side: -1, dist: 70 },
        { type: 'blitzer', seg: 15, u: 0.5, side: 1, dist: 8 },
        { type: 'rhine', seg: 16, u: 0.5, side: 0, dist: 0 },
        { type: 'hbarch', seg: 16, u: 0.5, side: 0, dist: 0, story: 'Hohenzollernbrück. Die Zöch fahre, de Kripo fährt, du fährs. Nur der Schatz liegt still.' },
        { type: 'boat', seg: 16, u: 0.3, side: 1, dist: 60 },
        { type: 'museum', seg: 17, u: 0.5, side: -1, dist: 42, keep: 50 },
        { type: 'musicaldome', seg: 17, u: 0.2, side: 1, dist: 60 },
        { type: 'rain', seg: 0, u: 0.5, side: 0, dist: 0, face: false },
        { type: 'zeppelin', seg: 7, u: 0.5, side: 1, dist: 60, face: false },
        { type: 'crowd', seg: 18, u: 0.6, side: 1, dist: 10 },
        { type: 'neon', seg: 18, u: 0.4, side: -1, dist: 14, text: 'DOM-SOUVENIRS · ORIGINAL', color: '#00e5ff' }
      ]
    },
    {
      id: 'zuelpicher', name: 'Zülpicher 11.11.', district: 'Kwartier Latäng um 11 Uhr 11', tag: 'TAG', order: 9,
      waypoints: ['Zülpicher Platz', 'Barbarossaplatz', 'Luxemburger Straße', 'Uni', 'Aachener Weiher', 'Hohenstaufenring'],
      diff: 2, laps: 3, scale: 1.35,
      desc: 'Elfter im Elften, 11 Uhr 11, Zülpicher Straße. Studenten, Kostüme, Kölsch an jeder Ecke. Sprung über die Kneipen im Kwartier Latäng, Looping an der Mensa, Unterführung, Aachener Weiher. Wer fünf Kölsch in einer Runde nimmt, fährt Schlangenlinie. Wie alle anderen auch.',
      theme: { sky: 0x8fc0ff, fog: 0xffe6f5, ground: 0xa9a49c, sun: 0xfff0ff, road: [0x5a5a5a, 0x4c4c4c], night: false, water: 0x3f7fc0, confetti: true, street: 'gruenderzeit', catenary: true, koelschRich: true,
        streets: ['ZÜLPICHER STRASSE', 'ZÜLPICHER PLATZ', 'BARBAROSSAPLATZ', 'LUXEMBURGER STR.', 'ZÜLPICHER WALL', 'UNIVERSITÄTSSTR.', 'HOHENSTAUFENRING', 'RATHENAUPLATZ'],
        shops: ['KÖLSCH', 'KOSTÜME', 'STUDENTENFUTTER', 'MENSA', 'COPYSHOP', 'BÜTZJE-BAR', 'KAMELLE', 'DÖNER', 'PLATTENLADEN', 'ALAAF-SHOP', 'BÄCKEREI MERZENICH', 'KIOSK · KÖLSCH 1,50'],
        far: [{ type: 'dom', angle: 40, dist: 180 }, { type: 'colonius', angle: 320, dist: 160 }],
        intro: ['Elfter im Elften, elf Uhr elf. Die Studente han seit sechs Uhr Kölsch im Blut un noch keine Abschluss.', 'Zülpicher Stroß. Hee bruchs de kein Ausweis, nur e Kostüm. Un e Auto, dat jeradeaus fährt.', 'Kwartier Latäng. Latein kann hee keiner, ävver alle kenne dat Wort Kölsch.'] },
      // 0 str,1 L,2 str,3 jump (Kneipen),4 str,5 L,6 hill,7 loop (Mensa),8 str,9 L,10 str (Aachener Weiher),11 R,12 str,13 L,14 dip,15 str,16 L,17 str
      segments: [
        { t: 'straight', len: 100 },
        { t: 'curve', angle: 90, r: 40, bank: 10 },
        { t: 'straight', len: 60 },
        { t: 'jump', ramp: 26, angle: 16, gap: 30, over: 'buedchen' },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 35 },
        { t: 'hill', len: 50, pitch: 12 },
        { t: 'loop', r: 13, shift: 14 },
        { t: 'straight', len: 40 },
        { t: 'curve', angle: 90, r: 40, bank: 12 },
        { t: 'straight', len: 60 },
        { t: 'curve', angle: -90, r: 30 },
        { t: 'straight', len: 20 },
        { t: 'curve', angle: 90, r: 30 },
        { t: 'dip', len: 40, pitch: 12 },
        { t: 'straight', len: 50 },
        { t: 'curve', angle: 90, r: 40 },
        { t: 'straight', len: 60 }
      ],
      props: [
        { type: 'tuenn', seg: 0, u: 0.02, side: 1, dist: 9 },
        { type: 'crowd', seg: 0, u: 0.1, side: -1, dist: 10 }, { type: 'crowd', seg: 0, u: 0.14, side: 1, dist: 10 }, { type: 'crowd', seg: 0, u: 0.4, side: -1, dist: 10 },
        { type: 'tribuene', seg: 0, u: 0.3, side: 1, dist: 12, keep: 30, story: 'Zülpicher Stroß. Tribün för de Studente. Die sitze hee seit dem ersten Semester. Immer noch.' },
        { type: 'bunting', seg: 0, u: 0.5, side: 0, dist: 0 },
        { type: 'koelsch', seg: 0, u: 0.6, side: -1, dist: 18 },
        { type: 'bude', seg: 0, u: 0.75, side: 1, dist: 11, text: 'KÖLSCH · 11.11. · 11 UHR 11' },
        { type: 'blitzer', seg: 0, u: 0.9, side: -1, dist: 8 },
        { type: 'kirche', seg: 1, u: 0.5, side: 1, dist: 46, h: 34, color: 0x9a4a34 },
        { type: 'platz', seg: 2, u: 0.3, side: -1, dist: 21, seed: 4, keep: 16, story: 'Barbarossaplatz. Der schönste Platz vun Kölle, sagt keiner. Ävver de Bahn hält, un dat is hee schon vill.' },
        { type: 'neon', seg: 2, u: 0.6, side: 1, dist: 14, text: 'BÜTZJE-BAR · KOSTÜM-PFLICHT', color: '#ff2d95', light: false },
        { type: 'crowd', seg: 2, u: 0.85, side: -1, dist: 10 },
        { type: 'buedchen', seg: 4, u: 0.4, side: 1, dist: 11 },
        { type: 'zochwagen', seg: 4, u: 0.7, side: -1, dist: 13 },
        { type: 'halle', seg: 5, u: 0.5, side: 1, dist: 60, keep: 60, story: 'Die Uni. Hee lernt mer, wie mer Kölsch bestellt, op Latein. Un wie mer et nit bezahlt, op Kölsch.' },
        { type: 'kirche', seg: 6, u: 0.5, side: -1, dist: 48, h: 30 },
        { type: 'tribuene', seg: 8, u: 0.4, side: 1, dist: 12, keep: 30, story: 'Mensa-Looping. Einmol rund, wie de Schlang an der Essensausgab. Nur schneller un ohne Erbsesupp.' },
        { type: 'koelsch', seg: 8, u: 0.7, side: -1, dist: 18 },
        { type: 'pond', seg: 10, u: 0.5, side: 1, dist: 40, seed: 3, keep: 30, story: 'Aachener Weiher. An Wieverfastelovend schwemme hee de Krawatte. An 11.11. de Studente.' },
        { type: 'park', seg: 10, u: 0.3, side: -1, dist: 44, seed: 6, w: 40, d: 40, keep: 30 },
        { type: 'crowd', seg: 10, u: 0.8, side: 1, dist: 10 },
        { type: 'polizei', seg: 12, u: 0.5, side: 1, dist: 10 },
        { type: 'bunting', seg: 15, u: 0.4, side: 0, dist: 0 },
        { type: 'tribuene', seg: 15, u: 0.6, side: -1, dist: 12, keep: 30 },
        { type: 'koelsch', seg: 15, u: 0.85, side: 1, dist: 18 },
        { type: 'haltestelle', seg: 17, u: 0.3, side: 1, dist: 10 },
        { type: 'tram', seg: 17, u: 0.6, side: 1, dist: 12 },
        { type: 'crowd', seg: 17, u: 0.8, side: -1, dist: 10 },
        { type: 'billboard', seg: 17, u: 0.5, side: -1, dist: 14, text: 'KÖLLE ALAAF – ELF UHR ELF' },
        { type: 'zeppelin', seg: 9, u: 0.5, side: 1, dist: 60, face: false }
      ]
    },
    {
      id: 'rodenkirchen', name: 'Rodenkirchen Rheinbad', district: 'Sommer am Rhing, Südbrücke bis Weiß', tag: 'TAG', order: 10,
      waypoints: ['Rheinuferweg', 'Rodenkirchener Brücke', 'Weiß', 'Rheinstrand', 'Sürther Bootshaus'],
      diff: 3, laps: 3, scale: 1.5,
      desc: 'Sommer in Rodenkirchen: Rheinuferweg, drei Sprünge über den Rhing, Looping am Strand, Korkenzieher am Bootshaus, rüber über die Rodenkirchener Brücke. Wer zu kurz springt, badet. Wer zu weit springt, badet in Weiß.',
      theme: { sky: 0x5fa8ff, fog: 0xd8ecff, ground: 0x5e9a4a, sun: 0xffffff, road: [0x585858, 0x4a4a4a], night: false, water: 0x3f8fc8, street: 'park',
        streets: ['RHEINUFERWEG', 'UFERSTRASSE', 'HAUPTSTRASSE', 'WEISSER STRASSE', 'SÜRTHER STRASSE', 'AM RHEINSTRAND', 'MAINSTRASSE'],
        shops: ['BOOTSHAUS', 'EISCAFÉ', 'KÖLSCH', 'STRANDBAR', 'FISCHBRÖTCHEN', 'YACHTCLUB', 'FÄHRE'],
        far: [{ type: 'dom', angle: 20, dist: 220 }, { type: 'colonius', angle: 40, dist: 260 }, { type: 'kranhaus', angle: 10, dist: 160 }],
        intro: ['Rodenkirchen. Hee wohne die, die et jeschafft han. Un die, die et versucht han. Beide am Rhing.', 'Sommer, Rhing, Strand. Un du fährs Auto drüvver. Dat is Kölle, Jung: schön, un keiner hät et jeplant.', 'Rheinbad. Dat Wasser is kalt, de Strömung is stark, un de Fähre wartet nit. Also spring richtig.'] },
      // 0 str,1 jump (Rheinarm),2 str,3 R,4 str,5 loop (Strand),6 str,7 R,8 bridge (Rodenkirchener),9 R,10 str (Weiß),11 jump (Strand),12 str,13 cork (Bootshaus),14 L,15 str,16 R,17 str,18 R,19 str
      segments: [
        { t: 'straight', len: 140 },
        { t: 'jump', ramp: 30, angle: 16, gap: 34 },
        { t: 'straight', len: 50 },
        { t: 'curve', angle: -90, r: 45, bank: 15 },
        { t: 'straight', len: 40 },
        { t: 'loop', r: 14, shift: 14 },
        { t: 'straight', len: 50 },
        { t: 'curve', angle: -90, r: 45 },
        { t: 'bridge', len: 150 },
        { t: 'curve', angle: -90, r: 40, bank: 12 },
        { t: 'straight', len: 60 },
        { t: 'jump', ramp: 28, angle: 15, gap: 30 },
        { t: 'straight', len: 40 },
        { t: 'corkscrew', len: 64, r: 9, turns: 1, dir: -1 },
        { t: 'curve', angle: 90, r: 35 },
        { t: 'straight', len: 30 },
        { t: 'curve', angle: -90, r: 35 },
        { t: 'straight', len: 60 },
        { t: 'curve', angle: -90, r: 40 },
        { t: 'straight', len: 40 }
      ],
      props: [
        { type: 'tuenn', seg: 0, u: 0.02, side: 1, dist: 9 },
        { type: 'crowd', seg: 0, u: 0.08, side: -1, dist: 10 },
        { type: 'rhineSide', seg: 0, u: 0.5, side: 1, dist: 150, l: 700, w: 220 },
        { type: 'promenade', seg: 0, u: 0.5, side: 1, dist: 40 },
        { type: 'boat', seg: 0, u: 0.3, side: 1, dist: 90 }, { type: 'barge', seg: 0, u: 0.7, side: 1, dist: 120 }, { type: 'speedboat', seg: 0, u: 0.5, side: 1, dist: 100, face: false },
        { type: 'bude', seg: 0, u: 0.35, side: -1, dist: 11, text: 'EISCAFÉ · KÖLSCH · FÄHRE' },
        { type: 'koelsch', seg: 0, u: 0.6, side: -1, dist: 18 },
        { type: 'blitzer', seg: 0, u: 0.9, side: -1, dist: 8 },
        { type: 'rhine', seg: 1, u: 0.55, side: 0, dist: 0 },
        { type: 'moewen', seg: 1, u: 0.5, side: 1, dist: 30, face: false },
        { type: 'beach', seg: 4, u: 0.5, side: 1, dist: 62, keep: 60, story: 'Rheinstrand Rodenkirchen. Sand, Sonn, Strömung. Jedes Johr holt der Rhing sich einen. Nit dich. Heut nit.' },
        { type: 'palm', seg: 4, u: 0.3, side: 1, dist: 12, h: 8 }, { type: 'palm', seg: 4, u: 0.7, side: 1, dist: 12, h: 7, seed: 3 },
        { type: 'tribuene', seg: 6, u: 0.4, side: -1, dist: 14, story: 'Strand-Looping. Oben der Himmel, unten der Rhing, dazwische du. Un e Kölsch, dat rausfällt.' },
        { type: 'kirche', seg: 7, u: 0.5, side: -1, dist: 50, h: 30, color: 0xc4ad8c },
        { type: 'rhine', seg: 8, u: 0.5, side: 0, dist: 0 },
        { type: 'suspension', seg: 8, u: 0.5, side: 1, dist: 60, face: false, story: 'Rodenkirchener Brück. Autobahn nach Bonn. Da wollt noch nie einer hin. Dat is Klüngel op Bundesebene.' },
        { type: 'boat', seg: 8, u: 0.3, side: -1, dist: 55 }, { type: 'barge', seg: 8, u: 0.7, side: 1, dist: 70 },
        { type: 'row', seg: 10, u: 0.5, side: -1, dist: 24, style: 'wiederaufbau', seed: 3, n: 4, story: 'Weiß. Villa an Villa. Hee wohnt der Klüngel, wenn er in Rente is.' },
        { type: 'kirche', seg: 10, u: 0.8, side: -1, dist: 44, h: 26 },
        { type: 'rhine', seg: 11, u: 0.55, side: 0, dist: 0 },
        { type: 'speedboat', seg: 11, u: 0.5, side: 1, dist: 60, face: false },
        { type: 'bude', seg: 12, u: 0.5, side: 1, dist: 11, text: 'BOOTSHAUS · FISCHBRÖTCHEN' },
        { type: 'hafenkran', seg: 15, u: 0.5, side: 1, dist: 36, story: 'Sürther Bootshaus. Hee liegt ming Boot. Also dat Boot, dat ich beim Zocke jewonne hann. Der Vorbesitzer sucht et noch.' },
        { type: 'koelsch', seg: 17, u: 0.5, side: -1, dist: 18 },
        { type: 'riesenrad', seg: 17, u: 0.5, side: 1, dist: 50, keep: 50 },
        { type: 'crowd', seg: 19, u: 0.5, side: 1, dist: 10 },
        { type: 'billboard', seg: 19, u: 0.3, side: -1, dist: 14, text: 'RHEINBAD RODENKIRCHEN – NUR MIT BADEHOSE' },
        { type: 'moewen', seg: 8, u: 0.5, side: -1, dist: 40, face: false }
      ]
    }
  ];

  // ---------------- the host: dä Lange, doorman of the Ringe (no real names) ----------------
  const TUENN = {
    name: 'Dä Lange', emoji: '🎩',
    intro: [
      'He, wor et wirklich gefährlich es, da wächsste über dich hinaus. Also: Gas, Hätz un Verstand.',
      'Willkomme in Chicago am Rhein, Jung. Hee jilt nur eins: schneller sin als ich.',
      'Ich bin dä Lange. Zwei Meter zehn an der Tür. Mir jehört die Streck, der Asphalt un dat Kölsch danach.',
      'Kölle is keine Stadt. Kölle is e Jeföhl. Un heut Nacht is et schnell.'
    ],
    countdown: ['Drei…', 'Zwei…', 'Eins…', 'FOTT DOMET!'],
    crash: [
      'Jung, dat wor nix.',
      'Do fährs wie ne Kamellebüggel im Wind.',
      'Ich kenn ne juten Blechschmied. Ming Schwager. Kost extra.',
      'Et hätz schlecht, ävver et kütt! Weiter, Jung.',
      'Mer nennt dat Klüngel-Kurve: alle wissen et, keiner fährt se richtig.',
      'Schäl hätt dat besser jemaat. Un der sieht doppelt.'
    ],
    heist: ['Domschatz im Kofferraum, Kripo im Rückspiejel. Jetz jeht et lös, Jung. Un zwar schnell.', 'Kripo Kölle, direkt vum Start. Die han op dich jewartet. Zeig ihne de Zoobrück.', 'Der Kommissar hät en Zigarett an un et Blaulicht. Beides brennt för dich.'],
    roof: ['Dat wor et Dach, Jung. Der Schornsteinfeger schickt de Rechnung.', 'Zo kurz jesprunge. Jetz wohns de im Dachjeschoss. Ohne Miete.', 'Durch et Dach in de Stuff. Die Lück han jrad jejesse. Sag wenigstens Mahlzeit.', 'Wer üvver et Haus will, bruch Anlauf. Wer durch et Haus will, bruch ne Anwalt.'],
    water: ['Un plumps in der Rhing. Der Schokoladenmuseum-Kapitän fischt dich raus.', 'Dat wor kein Sprung, dat wor ne Taufe.', 'Du solls über de Rhing, nit in de Rhing, Jung!'],
    loopFall: ['Vom Looping jefalle wie ne Kamellebüggel. Jas jeben, Jung!', 'Im Looping bremst mer nit. Dat is wie Kölsch ohne Deckel.', 'Die Elefanten im Zoo han jelacht. Beide.'],
    loopOk: ['Sauber durch de Looping! Dat kriegt en Deckelstrich.', 'Alaaf! Kopfüber un trotzdem jerade.'],
    jumpOk: ['Dat wor ne Sprung! Chicago am Rhein hat en neuen Stuntman.', 'Üvver et Dach! Die Lück drin han et nit mol jemerkt. Die kucke Fernsehen.', 'Jesprunge wie ne Jeck vum Balkon an Wieverfastelovend. Nur jelandet.', 'Jeflogen wie ne Taube vum Dom. Nur mit mieh Stil.'],
    lap: ['Noch en Rund, Jung. Kölsch is kalt jestellt.', 'Rund vorbei. Der Köbes zählt mit.', 'Letzte Rund! Fott domet!'],
    win: ['Jewonne! Do bes jetz offiziell en Kölsche Jung. Oder Mädche. Ejal, Kölsch is för alle.', 'Ne Sieg in Chicago am Rhein. Ich hätt mich fast jefreut.', 'Alaaf, Jung! Dat kütt in de Express. Un ich kassier de Wette.'],
    lose: ['Verlore. Aber et hätt noch immer jot jejange. Meistens.', 'Et hätz schlecht, ävver et kütt! Nächstes Mol.', 'Nächstes Mol, Jung. Ming Streck läuft nit fott.'],
    overtake: ['Do bes vorbei! Jetz nit einschlofe.', 'Überholt wie de KVB am Ebertplatz.'],
    overtaken: ['Un fott is er. Wie ming Steuererklärung.', 'Der zieht an dir vorbei wie de Rhing bei Hochwasser.'],
    record: ['NEUE BESTZEIT! Dat schreib ich uff de Deckel.', 'Streckenrekord! Ich lass dich uff ne Bierdeckel drucke.'],
    turbo: ['Turbo! Jetz brennt de Asphalt.', 'Nitro, Jung! Dat riecht nach Kölsch un Benzin.'],
    damage: ['Totalschaden. Heinzel schraubt dich nachts wieder zesamme.', 'Dat Auto is fott. Dat nächste is uff Deckel.'],
    events: [
      'Ne Taube op der Windschutzscheibe. Typisch Domplatte.',
      'Der Köbes reicht dir im Vorbeifahre e Kölsch. Deckelstrich!',
      'Baustelle! Seit 1998. Fertig: irjendwann.',
      'Fräulein Anna wirft Kamelle. Direkt in dinge Kühler.',
      'Ne Möwe klaut dir de Fischbrötchen. Willkomme am Rhing.',
      'Klüngel Tom winkt. Dat kost dich später wat.',
      'Ne Zocker wirft ne Würfel op de Stroß. Sechs. Du fährs drüber.',
      'Im Rückspiegel: der Nachtportier vum Sartory. Winkt. Oder droht.',
      'Ne Dame im Pelz steigt in et Taxi. Willi, dat wird teuer.',
      'Der Boxer vum Klein Köln joggt neben dir her. Un is schneller.',
      'Kripo-Funk: „Verdächtiger fährt rot.“ Alle fahre rot. Kölle.',
      'Ne Kranz Kölsch fliegt vum Balkon. Der Köbes hät jezielt.',
      'Der Nachtwächter vum Dom kuckt op de Uhr. Er hät keine. Er kuckt trotzdem.'
    ],
    door: ['Du kütts hee nit rein! ... Ausnahmsweise doch.', 'Krawatte? Nä. Kölsch? Jo. Dann kütts de rein.', 'Ich hab 40 Johr an der Tür jestande. Ich kenn dich. Rein.', 'Turnschuh, Jung? Ejal. Heut Nacht is Rennen.'],
    tuennsTelefon: ['Man kennt sich, man hilft sich. Ming Türsteher stonn jetz op der Streck. Die andere kumme hee nit durch.', 'Ich hab telefoniert. Sechs Sekunde Ruhe vor dä Jecke. Kost dich e Kölsch.', 'Klüngel, Jung. De Ampeln sin jrün, nur för dich.'],
    express: [
      'DÄ SCHNELLE: KÖLN – CHICAGO AM RHEIN! 50.000 Straftaten, e Drittel jeklärt.',
      'DÄ SCHNELLE: Domschatz jeklaut! Dä Lange hät e Alibi: Kölsch.',
      'DÄ SCHNELLE: Banküberfall am Dom! Geiseln, Kripo, Kamelle.',
      'DÄ SCHNELLE: Zocker verliert Villa in Marienburg. Jewinnt se an der Tür zurück.',
      'DÄ SCHNELLE: Boxnacht im Sartory – Sieger: dä Köbes met dem Kranz.',
      'DÄ SCHNELLE: Türsteher-Legende schreibt Kolumne. Redaktion hät Angst.',
      'DÄ SCHNELLE: FC Johnny – de Zuhälter han eijene Fußballclub. Abstieg wie der FC.',
      'DÄ SCHNELLE: Kölner Klüngel: Ampeln op der Ringe seit 1968 jrün för Bekannte.'
    ],
    grundgesetz: [
      'Artikel 1: Et es wie et es. Also fahr.',
      'Artikel 2: Et kütt wie et kütt. Meistens Klüngel Tom.',
      'Artikel 3: Et hätt noch immer jot jejange. Bes jetz.',
      'Artikel 4: Wat fott es, es fott. Dinge Führerschein zum Beispiel.',
      'Artikel 5: Et bliev nix wie et wor. Außer de Baustelle.',
      'Artikel 6: Kenne mer nit, bruche mer nit, fott domet. Sagt der Türsteher.',
      'Artikel 7: Wat wells de maache? Jas jeben.',
      'Artikel 8: Mach et jot, ävver nit zo off. Der Turbo.',
      'Artikel 9: Wat soll dä Quatsch? Der Blitzer.',
      'Artikel 10: Drinks de eine met? Kölsch = Turbo.',
      'Artikel 11: Do laachs de dich kapott. Über de Rhing jesprunge un in de Rhing jelandet.'
    ],
    radio: [
      'RADIO KÖLLE: Stau am Ebertplatz. Wie immer. Seit 1974.',
      'RADIO KÖLLE: Blitzer op der Zoobrücke. Dä Lange vum Ring hät ihn selbst opjestellt.',
      'RADIO KÖLLE: Der FC hät jewonne. Nä, Spaß. Weiter im Programm.',
      'RADIO KÖLLE: Die Oper is fertig! Ha, ha. Verkehrsmeldung: nä.',
      'RADIO KÖLLE: KVB-Streik. Die Bahn steht, die Jecke laufe.',
      'RADIO KÖLLE: Tauben op der Domplatte. Fahrt bitte vorsichtig durch de Kamelle.',
      'RADIO KÖLLE: Hochwasser. Der Rhing kütt. Der Schäl och.',
      'RADIO KÖLLE: Jetz LamboGina, danach de Verkehr. Oder umjekehrt.',
      'RADIO KÖLLE: Klüngel Tom hät de Ampeln jekauft. Alle jrün. Für ihn.',
      'RADIO KÖLLE: Wetter: Kölsch. Aussicht: noch mieh Kölsch.',
      'RADIO KÖLLE: Ne Zeppelin über dem Dom. Nä, dat is der Köbes met ner Runde.',
      'RADIO KÖLLE: Fräulein Anna fährt op der Ringe. Rettet üch, Jecke.',
      'RADIO KÖLLE: Die Polizei bittet: fahrt nit schneller als dä Lange an der Tür. Der hät Freunde.',
      'RADIO KÖLLE: In Düsseldorf hät et jeregnet. Wie schade.',
      'RADIO KÖLLE: Neonlicht op der Ringe, Palmen am Rhing. Miami? Nä. Kölle.'
    ],
    blitzer: [
      'BLITZ! Dat Foto kütt an de Bierdeckel. Knöllchen: 60 Euro.',
      'BLITZ! Klüngel Tom regelt dat. Für 40 Euro un e Kölsch.',
      'BLITZ! Lächel, Jung. Dat Bild hängt bald am Dom.',
      'BLITZ! De Stadt bedankt sich. Die Oper muss ja bezahlt werde.'
    ],
    tips: [
      'TIPP: Im Looping nit bremse. Dat is wie Kölsch ohne Deckel.',
      'TIPP: Turbo lädt beim Drifte. Also: quer is mieh.',
      'TIPP: Blitzer blitze ab 120. Klüngel Tom kennt jemand, der jemand kennt.',
      'TIPP: Steilkurve = Gas. Flachkurve = Hätz. Sonntagsfahrer = Tünnes.',
      'TIPP: Bei 100 % Schaden schraubt Heinzel nachts. Kost dich 3 Sekunde.',
      'TIPP: Kamera C: Cockpit. Fühlt sich an wie Taxi Willi um drei Uhr nachts.',
      'TIPP: Rheinsprung mit unter 90 = Rheinbad. Handtuch nit verjesse.'
    ],
    // place anecdotes: told when you pass a Brauhaus, Büdchen, Blitzer, church ... (the doorman knows every door in town)
    places: {
      brauhaus: ['Brauhaus. Der Köbes bringt Kölsch, bis de ne Deckel op et Glas lächs. Ich hann noch nie ne Deckel jebruch.', 'Hee drin hann ich mieh Lück rausjeschmisse als reinjelosse. Wor e jutes Jeschäft.', 'Kölsch is dat einzije Bier, dat mer och versteht, wenn mer et nit trinkt.', 'Der Wirt schuldet mir noch e Kölsch vun 1974. Ich wart. Ich hann Zick.', 'Die stonn vor der Tür, weil se drinne nit mieh stonn künne.'],
      buedchen: ['Büdchen. Dat Kölner Wohnzimmer. Kölsch, Zigaretten, Klüngel. Alles zum Mitnehmen.', 'Am Büdchen hann ich mieh jelernt als op der Schull. Vor allem rechne. Met Deckel.', 'Der Büdchen-Mann kennt jeden. Ich kenn ihn. Also kenn ich jeden.'],
      blitzer: ['Blitzer. Der einzije in Kölle, der pünktlich is.', 'Dat Ding hät mieh Fotos vun mir als ming Mutter.', 'Blitzer? Hee? Dat hät mir keiner jesaht. Ich kenn jemand, der dat wegmacht.'],
      polizei: ['Kripo. Die kenne mich, ich kenn die. Mer nicke sich zo. Mieh nit.', 'Peterwagen. Jrön-wieß wie de Ampel: erst jrön, dann wieß mer nix mieh.', 'Die Polizei is ming Freund un Helfer. Meistens Helfer. Beim Rausjonn.'],
      kirche: ['Kirch. Do jeht mer sonntags rein, wenn mer samstags nit reinjekumme is.', 'Zwölf romanische Kirche hät Kölle. Ich hann an elf Türe jestanden. Die zwölfte hät ne Pastor.', 'Der Pastor un ich hann dat selbe Jeschäft: mer entscheide, wer reinkütt.'],
      haltestelle: ['KVB. Kütt, wann se will. Wie de Schäl.', 'Die Bahn steht, die Lück laufe. Kölle funktioniert trotzdem. Irjendwie.', 'Linie 1 nach Weiden West. Do wollt noch nie einer hin. Fährt trotzdem.'],
      park: ['Jrön in Kölle. Hee lieje sonntags de Lück, die samstags bei mir nit reinjekumme sin.', 'Bäume. Die stonn och de janze Nacht. Ohne Kölsch. Respekt.', 'Park. Hee wor mol e Spielcasino. Nä, Spaß. Ävver et hät sich so anjefühlt.'],
      taxi: ['Taxi. Der Fahrer kennt de Stadt un ding Jeheimnisse. Beides fährt er nach Hus.', 'Hellelfenbein, dat Taxi. Wie ming Zähn nach dreißig Johr Zigarre.'],
      platz: ['Ne Platz in Kölle: Marktstand, Kölsch-Stand, Büdchen. Un e Denkmal, dat keiner kennt.', 'Op dem Platz hann se mich mol jefragt, ob ich der Bürjermeister bin. Ich hann nä jesaht. Wor jelogen.'],
      tram: ['Die Bahn. Wieß-rut wie der FC. Un jenau so pünktlich.'],
      tunnel: ['Tunnel. Dunkel, eng, laut. Wie der Boxkeller om Samstag.'],
      loop: ['Looping. Einmol rund, wie ne Zocker-Abend: oben bes de König, unten fällt et Kölsch us der Täsch.', 'Kopp unge, Jas oben. Dat es dat einzije, wat ich in der Schull jelernt hann.'],
      cork: ['Korkenzieher. Einmol um de eijene Achs, wie ich nach dem zwölfte Kölsch. Nur schneller.', 'Der Korkenzieher. Links Himmel, rechts Kölle, oben Stroß. Dat is Stunts, Jung, nit de KVB.', 'Hee dreht sich de Stroß, nit dinge Kopp. Meistens.'],
      jump: ['Sprung. Wer hee bremst, badet. Wer nit bremst, badet vielleicht och. Ävver met Stil.']
    },
    // wall wisdom for graffiti, billboards and posters
    walls: ['DU KÜTTS HEE NIT REIN', 'MAN KENNT SICH · MAN HILFT SICH', 'ET HÄTT NOCH IMMER JOT JEJANGE', 'WER ZOLETZ KÜTT, ZAHLT DE KÖLSCH', 'KREDIT? NUR OP DECKEL', 'SEIT 1961 AN DER TÜR', 'KÖLSCH IS KEIN BIER, KÖLSCH IS NE HALTUNG', 'CHICAGO AM RHEIN – MER SIN DIE JUTE', 'GLÜCKSSPIEL: JEWINNE DEIT NUR DER TÜRSTEHER', 'DRINK DOCH ENE MET', 'HÄTZ UN VERSTAND – MEISTENS HÄTZ', 'KÖLLE IS E JEFÖHL', 'HEE RÄJIERT DER KLÜNGEL', 'DIE OPER KÜTT. IRJENDWANN.', 'JECK BLIEV JECK', 'KEIN EINLASS FÜR DÜSSELDORF', 'ZWEI METER ZEHN – UN KEINER KÜTT VORBEI', 'ET ES WIE ET ES', 'WAT FOTT ES, ES FOTT'],
    // shop signs with a wink
    shops: ['TÜRSTEHER-BEDARF', 'ZOCKERSTUBE', 'KLÜNGEL & SÖHNE', 'NACHTPORTIER-SCHULE', 'KREDIT & KÖLSCH', 'DECKEL-VERLEIH', 'ANWALT FÜR KNÖLLCHEN', 'BLECHSCHMIED · MING SCHWAGER', 'BÜTZJE-SERVICE', 'HÄTZ & VERSTAND GBR', 'FRISEUR ZUM LANGEN · 2,10 M', 'KAMELLE-GROSSHANDEL', 'HALVE HAHN – OHNE HAHN', 'DÜSSELDORF? NÄ.', 'AN- UND VERKAUF · FRAGEN SIE NICHT', 'CHANGE · WECHSELSTUBE · 1968', 'BOXSCHULE AM RING', 'SPIELCLUB · EINTRITT NUR MIT MIR'],
    // greeting by the time of day (real clock)
    // said a few seconds after the start, matching the scenery's time of day
    scene: {
      dawn: ['Morjens am Dom. Die Taube schlofe noch, die Zocker jrad erst. Nur du un ich sin wach.', 'Sonnenopjang üvver Deutz. Ich hann de janze Nacht an der Tür jestande. Jetz fahr ich hemm. Üvver de Brück, met Vollgas.', 'Fröhschicht, Jung. Der Köbes fegt noch de Deckel vun jestern zosamme. Bes de zoröck bes, hät er jezählt.', 'Um die Zick sin de Ringe leer un de Kripo müd. Beste Zick för e Rennen.'],
      dusk: ['Blaue Stund in Ehrenfeld. De Lichter jonn an, de Kassettenladen zo. Jetz fängt ming Schicht an.', 'Feieromend op der Venloer. Alle wolle noch fott, keiner will hemm. Wie op de Ringe, nur met Hafermilch.', 'Dämmerung. Um die Zick hann ich immer de erste Kölsch jetrunke. Un dat letzte. Dazwische wor Arbeit.', 'De Sonn jeht unger, de Neon jeht an. Ehrenfeld wechselt de Schicht. Du och.'],
      night: ['Nachts op de Poller Wiesen. Fröher Zelt, Lagerfüür un Kölsch. Heut Loopings. Un Kölsch.', 'Kölner Lichter üvver dem Rhing. Un du fährs kopfüvver drunger durch. Dat hät nit mol der Zeppelin jeschafft.', 'Nachtschicht, Jung. De Kranhäuser leuchte, de Arena leuchte, ich leuchte nit. Ich stonn im Dunkle un zähl.', 'Um Mitternacht sin de Poller Wiesen ming. Un de Kripo schlöf. Meistens.']
    },
    daytime: {
      night: ['Et is {h} Uhr, Jung. Um die Zick stonn ich normal an der Tür. Heut stonn ich am Streckenrand.', '{h} Uhr nachts. Chicago am Rhein wach op. Du och.'],
      morning: ['{h} Uhr morjens? Ich bin noch jar nit im Bett jewese. Fahr leise.', 'Fröh op, Jung. Der Bäcker hät noch zo. Der Rennen nit.'],
      day: ['{h} Uhr. Tagsüber fahre nur Touriste un Taxi Willi. Un du.', 'Mittags op de Ringe. Die Zocker schlofe noch. Du hass de Stroß för dich.'],
      evening: ['{h} Uhr. Jetz jeht de Nacht los. Un ming Schicht.', 'Feierabend för de andere. För uns fängt et an.']
    },
    // Razzia on the Ringe: everybody ducks, you keep driving
    // Klüngel-Auftrag: dä Lange needs something carried from A to B, fast and without a dent
    auftrag: {
      what: ['dä Umschlag', 'de Kölsch-Kiste', 'dä Aktenkoffer', 'dä Bierdeckel-Stapel', 'dä Ersatzschlüssel vum Sartory', 'dä Brief an de Kripo (unjeöffnet)', 'de Zockerkasse', 'dä Hut vum Kommissar', 'e Kilo Kamelle', 'de Pokalspende för dä FC'],
      where: ['SARTORY', 'KLEIN KÖLN', 'RESIDENZ-KINO', 'LOVERS CLUB', 'SPIELCLUB', 'ZOCKERTISCH', 'BOXRING', 'BRAUHAUS', 'BÜDCHEN AN DER ECKE', 'HAUPTBAHNHOF, SCHLIESSFACH 68', 'NACHTPORTIER'],
      start: ['Auftrag, Jung: {what} liegt op der Streck. Bring en zum {where}. Frag nit, fahr.', 'Man kennt sich, man hilft sich: {what} zum {where}. Un kein Kratzer, verstanden?', 'Der Klüngel ruft. {what} abhole, zum {where} bringe. Die Uhr läuft, dat Kölsch och.', 'Kleiner Jefallen: {what} zum {where}. Wenn de Kripo fragt: du kennst mich nit.'],
      pick: ['Do häs et. Jetz nur noch heil zum {where}. Un nit im Rhing bade.', 'Jot. Un jetz Gas, dat Ding hät en Termin.', 'Im Kofferraum. Wenn de jetz crashst, weiß dat janze Veedel Bescheid.'],
      done: ['Abjeliefert! Dat jibt fünf Striche op dä Deckel un e Kölsch vum Haus.', 'Sauber. Der {where} lässt jrüße. Un de Kripo hät nix jemerkt.', 'Dat nenn ich Klüngel. Fünf Striche, un ich vergess dat mit dem Turnschuh.', 'Pünktlich wie de Bahn – also nit. Aber heil. Fünf Striche!'],
      late: ['Zu spät, Jung. Der {where} hät zujemacht. Zwei Striche weniger.', 'Die Uhr wor schneller. Dat kost dich zwei Striche un ming Laune.', 'Zu langsam. Der Umschlag jeht jetz mit der Post. Mit Briefmarke, Jung.'],
      lost: ['Un fott is et. Bei dem Crash liegt {what} jetz op der Straße. Zwei Striche, un ich sach nix mehr.', 'Verlore. Dat Veedel redet morjen über dich. Nit jut.', 'Kratzer im Lack, Umschlag im Rinnstein. Klüngel kann jeder, du nit.']
    },
    // the Vorspann: what the arcade cabinet tells while nobody plays
    vorspann: [
      'KÖLN, 1968.',
      'Die Ringe glühen. Im Klein Köln wird gezockt, im Sartory getanzt, in der Friesenstraße geflüstert.',
      'Die Zeitungen nennen es CHICAGO AM RHEIN.',
      'An der Tür steht einer, den keiner überredet. Zwei Meter zehn, Hut, Handschuhe. Dä Lange.',
      'Er entscheidet, wer reinkommt. Und heute Nacht entscheidet er, wer am schnellsten durch Kölle kommt.',
      'Zehn Strecken. Fünf Karren. Loopings über dem Rhein, Sprünge über die Büdchen. Die Kripo hat den Motor schon an.',
      'Du kütts hee nit rein? Doch. Ausnahmsweise.',
      'FOTT DOMET.'
    ],
    razzia: ['RAZZIA! Kripo im Klein Köln. Alle unter de Tisch. Du nit, du fährs.', 'Blaulicht op de Ringe. Die Zocker verstecke sich. De Rivale och. Jas!', 'Razzia im Spielclub. Der Kommissar sucht mich. Ich bin hee. Fahr weiter.'],
    razziaEnd: ['Razzia vorbei. Die Zocker kumme wieder us de Löcher.', 'Kripo is weg. Ich hann jesaht, ich kenn keine.'],
    // five Kölsch in one lap: the Kölsch-Kurve
    promille: ['Jung, dat wor dat fünfte in einer Rund. Fahr jerade. Oder versuch et.', 'Fünf Kölsch, eine Rund. Jetz fährt dat Auto Schlangenlinie. Wie ich nach der Sitzung.', 'Kölsch-Kurve! Der Köbes hät dich jut versorgt. Zo jut.'],
    promilleEnd: ['Wieder nüchtern. Sagt der Türsteher. Also nit janz.'],
    // Kripo Kölle: the Peterwagen that shows up after three Knöllchen
    kripo: {
      start: ['Kripo Kölle! Drei Knöllchen, Jung. Jetz kütt der Peterwagen.', 'Hier spricht die Polizei Köln. Rechts ranfahren. Oder schneller werden, wie de wells.', 'Dat is die Kripo. Dä Lange hät nix jesaht. Noch nit.'],
      hit: ['Rammstoß! Dat jibt Punkte in Flensburg. Un ne Beule.', 'Der Peterwagen küsst dich. Ohne Bützje.', 'Kripo: „Anhalten!“ Du: „Später.“'],
      off: ['Ich hab met dem Kommissar telefoniert. Mer kenne uns vum Kegeln. Die Kripo dreht ab.', 'Klüngel, Jung. Der Peterwagen hät plötzlich Feierabend.', 'Dat wor der Hauptkommissar. Ich hann ihm 1974 an der Tür jeholfe. Erledigt.'],
      giveup: ['Kripo: „Schichtwechsel.“ Der Peterwagen dreht ab. Dat wor knapp.', 'Die Kripo hät dich verlore. Oder Hunger. Beides jut för dich.'],
      caught: ['Die Kripo hät dich zerlegt. Der Blechschmied freut sich. Ming Schwager.']
    },
    // the doorman's bet before the race
    wette: {
      offer: ['Ich wett {n} Kölsch, dat de vor {r} ins Ziel kütts. Zocker-Ehrenwort.', 'Wette? {n} Kölsch, du bes vor {r}. Ich hab ne jute Nas för sowat.', 'Op de Ringe wett mer. {n} Kölsch op dich jejen {r}. Enttäusch mich nit.'],
      won: ['Wette jewonne! {r} hinter dir. Ich schuld dir {n} Kölsch – kütt op der Deckel.', 'Jesaht, jetan: vor {r}. {n} Kölsch für dich. Ich zahl. Ausnahmsweise.'],
      lost: ['Wette verlore. {r} wor vor dir. Du schuldest mir {n} Kölsch. Ich hann Zick, ävver ich verjess nix.', '{r} vor dir. Dat kost dich {n} Kölsch. Der Zocker jewinnt immer. Dat bin ich.']
    },
    // Köbes hands you a Kölsch on the road
    koelschPick: ['Kölsch! Deckelstrich.', 'Ene met? Jo. Turbo!', 'Der Köbes kütt ungefragt. Wie immer.', 'Kölsch im Vorbeifahre. Dat kann nur Kölle.', 'Prost, Jung. Nit kleckern.', 'Deckel voll? Mer mache ne neue.'],
    // the beer-mat ranks
    ranks: [[0, 'LAUFKUNDSCHAFT'], [20, 'STAMMGAST'], [60, 'DECKELKÖNIG'], [150, 'EHRENMITGLIED VUM RING'], [400, 'LEGENDE VUM RING']],
    // Kölsch-Cup
    cup: {
      next: ['Nächste Streck, Jung. Der Cup wartet nit.', 'Weiter jeht et. Sieben Strecke, ein Kölsch-Cup. Kein Ausruhen.', 'Punkte notiert. Op der Deckel. Weiter.'],
      champion: ['KÖLSCH-CUP JEWONNE! Du bes jetz Stammgast vum Ring. Die Tür steht offe. Für immer.', 'Cup-Sieger! Selbst Klüngel Tom hät jeklatscht. Kurz.'],
      podium: ['Podium im Kölsch-Cup. Fast ne Legende. Dat Kölsch jeht op mich.'],
      loser: ['Cup vorbei. Nit jewonne, ävver jefahre. Dat is mieh als de meiste.', 'Der Cup is rum. Nächstes Johr, Jung. Ich stonn dann immer noch an der Tür.']
    },
    // DÄ SCHNELLE headlines about your own race
    express2: {
      record: 'DÄ SCHNELLE: NEUER STRECKENREKORD {track}! DÄ LANGE: „MING SCHULD.“',
      win: 'DÄ SCHNELLE: UNBEKANNTER RASER JEWINNT – KLÜNGEL TOM FORDERT UNTERSUCHUNGSAUSSCHUSS',
      kripoCaught: 'DÄ SCHNELLE: KRIPO STOPPT {car} OP DE RINGE – „ET WOR NOTWEHR“',
      kripo: 'DÄ SCHNELLE: VERFOLGUNGSJAGD OP DE RINGE – PETERWAGEN VERLIERT {car} IM VEEDEL',
      knoellchen: 'DÄ SCHNELLE: {n} KNÖLLCHEN IN DREI RUNDE – STADTKASSE SANIERT, OPER BEZAHLT',
      water: 'DÄ SCHNELLE: {car} BADET IM RHING – TAUCHER SUCHE NOCH DE DECKEL',
      crashes: 'DÄ SCHNELLE: BLECHSCHMIED MELDET REKORDUMSATZ – „MING SCHWAGER“, SAGT DÄ LANGE',
      last: 'DÄ SCHNELLE: LETZTER PLATZ – „ICH HANN MIR DE KÖLSCH-STÄND ANJEKUCK“',
      koelsch: 'DÄ SCHNELLE: {n} KÖLSCH IM VORBEIFAHRE – KÖBES: „DER HÄT NIT MOL JEBREMST“',
      podium: 'DÄ SCHNELLE: PLATZ {p} – KÖLLE HÄT EN NEUE HOFFNUNG',
      default: 'DÄ SCHNELLE: PLATZ {p} – KÖLLE HÄT SCHLIMMERES JESINN'
    },
    slogans: ['KÖLLE IST KEINE STADT. KÖLLE IST EIN GEFÜHL.', 'WILLKOMME IN KÖLN. GAS, HÄTZ UN VERSTAND – DAT ES KÖLLE 4D.', 'ET HÄTZ SCHLECHT, ÄVVER ET KÜTT!', 'WENN ET NACHT WIRD IN KÖLLE, VERZÄLLT DÄ LANGE VUM RING.', 'CHICAGO AM RHEIN, 1968. DU KÜTTS HEE NIT REIN.']
  };

  root.GameData = { CARS, DRIVERS, RIVALS, TRACKS, TUENN };
})(typeof window !== 'undefined' ? window : module.exports);
